Credit Scoring Fairness Criteria

Load the dataset

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.cm as cm

Load the dataset

In [2]:
import os
BANK_PATH = os.path.join(os.getcwd(), 'ML fairness/ml bank dataset/bankfullclean.csv') # Assign this to the location of the dataset
print(os.getcwd())
print(BANK_PATH)

# 5254 number of rows have 'biY' == 1
# 39787 number of rows have 'biY' == 0


/Users/xinyu/Desktop/Research/Machine-Learning-Fairness--main
/Users/xinyu/Desktop/Research/Machine-Learning-Fairness--main/ML fairness/ml bank dataset/bankfullclean.csv


In [3]:
bank = pd.read_csv(BANK_PATH)
df = pd.DataFrame(bank)
df.head()
dummy = df[['catAge', 'job', 'marital','education','balance','day', 'month', 'duration', 'campaign', 'pdays', 'previous', 'Fmonth', 'biDefault', 'biHousing', 'biLoan']]
# dummy.columns.values
dummy = pd.get_dummies(data=dummy)
# dummy.head()
dummy.columns.values
# df['marital'].unique()

# df['biY'].replace({0: False, 1: True}, inplace=True)
# print(df['biY'])


array(['balance', 'day', 'duration', 'campaign', 'pdays', 'previous',
       'biDefault', 'biHousing', 'biLoan', 'catAge_30-40', 'catAge_40-50',
       'catAge_<=30', 'catAge_>=50', 'job_admin.', 'job_blue-collar',
       'job_entrepreneur', 'job_housemaid', 'job_management',
       'job_retired', 'job_self-employed', 'job_services', 'job_student',
       'job_technician', 'job_unemployed', 'marital_divorced',
       'marital_married', 'marital_single', 'education_primary',
       'education_secondary', 'education_tertiary', 'month_apr',
       'month_aug', 'month_dec', 'month_feb', 'month_jan', 'month_jul',
       'month_jun', 'month_mar', 'month_may', 'month_nov', 'month_oct',
       'month_sep', 'Fmonth_apr', 'Fmonth_aug', 'Fmonth_dec',
       'Fmonth_feb', 'Fmonth_jan', 'Fmonth_jul', 'Fmonth_jun',
       'Fmonth_mar', 'Fmonth_may', 'Fmonth_nov', 'Fmonth_oct'],
      dtype=object)

Machine Learning Classification Model

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import LeaveOneOut

In [5]:
def get_naive_dataset(dataset):
    dataset = dataset.sample(frac=1).reset_index(drop=True)
    X = dummy
    y = dataset['biY']
    x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
    
    return (x_train, y_train), (x_test, y_test)

In [6]:
(x_train, y_train), (x_test, y_test) = get_naive_dataset(df)

In [7]:
x_train.columns.values

array(['balance', 'day', 'duration', 'campaign', 'pdays', 'previous',
       'biDefault', 'biHousing', 'biLoan', 'catAge_30-40', 'catAge_40-50',
       'catAge_<=30', 'catAge_>=50', 'job_admin.', 'job_blue-collar',
       'job_entrepreneur', 'job_housemaid', 'job_management',
       'job_retired', 'job_self-employed', 'job_services', 'job_student',
       'job_technician', 'job_unemployed', 'marital_divorced',
       'marital_married', 'marital_single', 'education_primary',
       'education_secondary', 'education_tertiary', 'month_apr',
       'month_aug', 'month_dec', 'month_feb', 'month_jan', 'month_jul',
       'month_jun', 'month_mar', 'month_may', 'month_nov', 'month_oct',
       'month_sep', 'Fmonth_apr', 'Fmonth_aug', 'Fmonth_dec',
       'Fmonth_feb', 'Fmonth_jan', 'Fmonth_jul', 'Fmonth_jun',
       'Fmonth_mar', 'Fmonth_may', 'Fmonth_nov', 'Fmonth_oct'],
      dtype=object)

In [8]:
y_train.values

array([0, 1, 1, ..., 0, 0, 0])

In [9]:
x_test.columns.values

array(['balance', 'day', 'duration', 'campaign', 'pdays', 'previous',
       'biDefault', 'biHousing', 'biLoan', 'catAge_30-40', 'catAge_40-50',
       'catAge_<=30', 'catAge_>=50', 'job_admin.', 'job_blue-collar',
       'job_entrepreneur', 'job_housemaid', 'job_management',
       'job_retired', 'job_self-employed', 'job_services', 'job_student',
       'job_technician', 'job_unemployed', 'marital_divorced',
       'marital_married', 'marital_single', 'education_primary',
       'education_secondary', 'education_tertiary', 'month_apr',
       'month_aug', 'month_dec', 'month_feb', 'month_jan', 'month_jul',
       'month_jun', 'month_mar', 'month_may', 'month_nov', 'month_oct',
       'month_sep', 'Fmonth_apr', 'Fmonth_aug', 'Fmonth_dec',
       'Fmonth_feb', 'Fmonth_jan', 'Fmonth_jul', 'Fmonth_jun',
       'Fmonth_mar', 'Fmonth_may', 'Fmonth_nov', 'Fmonth_oct'],
      dtype=object)

In [10]:
y_test.values

array([1, 0, 0, ..., 1, 0, 1])

Naive Bayes Model

In [11]:
%%time
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb_pred = gnb.fit(x_train, y_train).predict(x_test)

Result

In [12]:
test_df = x_test.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(gnb_pred, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])
test_df.columns.values

array(['balance', 'day', 'duration', 'campaign', 'pdays', 'previous',
       'biDefault', 'biHousing', 'biLoan', 'catAge_30-40', 'catAge_40-50',
       'catAge_<=30', 'catAge_>=50', 'job_admin.', 'job_blue-collar',
       'job_entrepreneur', 'job_housemaid', 'job_management',
       'job_retired', 'job_self-employed', 'job_services', 'job_student',
       'job_technician', 'job_unemployed', 'marital_divorced',
       'marital_married', 'marital_single', 'education_primary',
       'education_secondary', 'education_tertiary', 'month_apr',
       'month_aug', 'month_dec', 'month_feb', 'month_jan', 'month_jul',
       'month_jun', 'month_mar', 'month_may', 'month_nov', 'month_oct',
       'month_sep', 'Fmonth_apr', 'Fmonth_aug', 'Fmonth_dec',
       'Fmonth_feb', 'Fmonth_jan', 'Fmonth_jul', 'Fmonth_jun',
       'Fmonth_mar', 'Fmonth_may', 'Fmonth_nov', 'Fmonth_oct', 'biY',
       'pred', 'accurate'], dtype=object)

In [13]:
from sklearn.metrics import confusion_matrix

In [14]:

confusion_matrix = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix

array([[7702,  298],
       [ 961,   48]])

In [15]:
# Accuracy
# "Accuracy: ", test_df.accurate.mean()
accuracy_naive_bayes = (confusion_matrix[0][0] + confusion_matrix[1][1]) / (confusion_matrix[0][0] + confusion_matrix[0][1] + confusion_matrix[1][0] + confusion_matrix[1][1])
accuracy_naive_bayes



0.8602508602508603

In [16]:
# Split dataset based on marital status
test_df.columns.values
test_l30 = x_test[x_test['catAge_<=30'] == 1]
test_30to40 = x_test[x_test['catAge_30-40'] == 1]
test_40to50 = x_test[x_test['catAge_40-50'] == 1]
test_g50 = x_test[x_test['catAge_>=50'] == 1]

In [17]:
# Test on l30 subset
gnb_pred_l30 = gnb.fit(x_train, y_train).predict(test_l30)

test_df = test_l30.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(gnb_pred_l30, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_l30 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_l30


array([[1185,   64],
       [ 157,    7]])

In [18]:
accuracy_naive_bayes_l30 = (confusion_matrix_l30[0][0] + confusion_matrix_l30[1][1]) / (confusion_matrix_l30[0][0] + confusion_matrix_l30[0][1] + confusion_matrix_l30[1][0] + confusion_matrix_l30[1][1])
accuracy_naive_bayes_l30

0.8435951875442321

In [19]:
# Test on 30to40 subset
gnb_pred_30to40 = gnb.fit(x_train, y_train).predict(test_30to40)

test_df = test_30to40.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(gnb_pred_30to40, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_30to40 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_30to40

array([[3037,  100],
       [ 392,   16]])

In [20]:
accuracy_naive_bayes_30to40 = (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[1][1]) / (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[0][1] + confusion_matrix_30to40[1][0] + confusion_matrix_30to40[1][1])
accuracy_naive_bayes_30to40

0.861212976022567

In [21]:
# Test on 40to50 subset
gnb_pred_40to50 = gnb.fit(x_train, y_train).predict(test_40to50)

test_df = test_40to50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(gnb_pred_40to50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_40to50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_40to50

array([[1898,   64],
       [ 229,   11]])

In [22]:
accuracy_naive_bayes_40to50 = (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[1][1]) / (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[0][1] + confusion_matrix_40to50[1][0] + confusion_matrix_40to50[1][1])
accuracy_naive_bayes_40to50 # 0.8718606782768102

0.8669391462306993

In [23]:
# Test on g50 subset
gnb_pred_g50 = gnb.fit(x_train, y_train).predict(test_g50)

test_df = test_g50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(gnb_pred_g50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_g50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_g50

array([[1582,   70],
       [ 183,   14]])

In [24]:
accuracy_naive_bayes_g50 = (confusion_matrix_g50[0][0] + confusion_matrix_g50[1][1]) / (confusion_matrix_g50[0][0] + confusion_matrix_g50[0][1] + confusion_matrix_g50[1][0] + confusion_matrix_g50[1][1])
accuracy_naive_bayes_g50 # 0.8718606782768102

0.8631692806922661

In [25]:
#Demographic Parity
# positive rate = TP + TN
PR_Naive_Bayes_l30 = confusion_matrix_l30[0,0] +confusion_matrix_l30[1,1]

PR_Naive_Bayes_l30 


1192

In [26]:
PR_Naive_Bayes_30to40 = confusion_matrix_30to40[0,0] +confusion_matrix_30to40[1,1]
PR_Naive_Bayes_30to40

3053

In [27]:
PR_Naive_Bayes_40to50 = confusion_matrix_40to50[0,0] +confusion_matrix_40to50[1,1]
PR_Naive_Bayes_40to50 

1909

In [28]:
PR_Naive_Bayes_g50 = confusion_matrix_g50[0,0] +confusion_matrix_g50[1,1]
PR_Naive_Bayes_g50 

1596

In [29]:
# Equalized Opportunity
#TPR = TP/TP+FN

TPR_Naive_Bayes_l30 = confusion_matrix_l30[0,0] / (confusion_matrix_l30[0,0] + confusion_matrix_l30[1,0])

TPR_Naive_Bayes_l30


0.88301043219076

In [30]:
TPR_Naive_Bayes_30to40 = confusion_matrix_30to40[0,0] / (confusion_matrix_30to40[0,0] + confusion_matrix_30to40[1,0])

TPR_Naive_Bayes_30to40

0.8856809565470983

In [31]:
TPR_Naive_Bayes_40to50 = confusion_matrix_40to50[0,0] / (confusion_matrix_40to50[0,0] + confusion_matrix_40to50[1,0])

TPR_Naive_Bayes_40to50 

0.8923366243535495

In [32]:
TPR_Naive_Bayes_g50 = confusion_matrix_g50[0,0] / (confusion_matrix_g50[0,0] + confusion_matrix_g50[1,0])

TPR_Naive_Bayes_g50 # 0.8925619834710744

0.8963172804532578

In [33]:
# Equalized Odds
#TPR = TP/TP+FN
#FNR = FN/FN+TP


FNR_Naive_Bayes_l30 = confusion_matrix_l30[1,0] / (confusion_matrix_l30[1,0] + confusion_matrix_l30[0,0])

FNR_Naive_Bayes_l30



0.11698956780923994

In [34]:
FNR_Naive_Bayes_30to40 = confusion_matrix_30to40[1,0] / (confusion_matrix_30to40[1,0] + confusion_matrix_30to40[0,0])

FNR_Naive_Bayes_30to40

0.11431904345290173

In [35]:
FNR_Naive_Bayes_40to50 = confusion_matrix_40to50[1,0] / (confusion_matrix_40to50[1,0] + confusion_matrix_40to50[0,0])

FNR_Naive_Bayes_40to50

0.1076633756464504

In [36]:
FNR_Naive_Bayes_g50 = confusion_matrix_g50[1,0] / (confusion_matrix_g50[1,0] + confusion_matrix_g50[0,0])

FNR_Naive_Bayes_g50

0.10368271954674221

In [37]:
# Fairness Through Unwareness
x_train_unawareness = x_train.copy()
x_train_unawareness
x_train_unawareness.drop('catAge_<=30', inplace=True, axis=1)
x_train_unawareness.drop('catAge_30-40', inplace=True, axis=1)
x_train_unawareness.drop('catAge_40-50', inplace=True, axis=1)
x_train_unawareness.drop('catAge_>=50', inplace=True, axis=1)

# x_train_unawareness.columns.values
# x_train.columns.values






In [38]:
#Fairness through unawareness

x_test_unawareness = x_test.copy()
x_test_unawareness
x_test_l30 = x_test_unawareness[x_test_unawareness['catAge_<=30'] == 1]
x_test_30to40 = x_test_unawareness[x_test_unawareness['catAge_30-40'] == 1]
x_test_40to50 = x_test_unawareness[x_test_unawareness['catAge_40-50'] == 1]
x_test_g50 = x_test_unawareness[x_test_unawareness['catAge_>=50'] == 1]


x_test_l30.drop('catAge_<=30', inplace=True, axis=1)
x_test_l30.drop('catAge_30-40', inplace=True, axis=1)
x_test_l30.drop('catAge_40-50', inplace=True, axis=1)
x_test_l30.drop('catAge_>=50', inplace=True, axis=1)

x_test_30to40.drop('catAge_<=30', inplace=True, axis=1)
x_test_30to40.drop('catAge_30-40', inplace=True, axis=1)
x_test_30to40.drop('catAge_40-50', inplace=True, axis=1)
x_test_30to40.drop('catAge_>=50', inplace=True, axis=1)

x_test_40to50.drop('catAge_<=30', inplace=True, axis=1)
x_test_40to50.drop('catAge_30-40', inplace=True, axis=1)
x_test_40to50.drop('catAge_40-50', inplace=True, axis=1)
x_test_40to50.drop('catAge_>=50', inplace=True, axis=1)

x_test_g50.drop('catAge_<=30', inplace=True, axis=1)
x_test_g50.drop('catAge_30-40', inplace=True, axis=1)
x_test_g50.drop('catAge_40-50', inplace=True, axis=1)
x_test_g50.drop('catAge_>=50', inplace=True, axis=1)




# x_test_unawareness.columns.values
# x_test.columns.values
# test_married

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/core/frame.py:4163: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


In [39]:
# Test on l30 set
gnb_pred_l30 = gnb.fit(x_train_unawareness, y_train).predict(x_test_l30)

test_df = x_test_l30.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(gnb_pred_l30, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_l30 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_l30



array([[1189,   60],
       [ 157,    7]])

In [40]:
accuracy_naive_bayes_l30 = (confusion_matrix_l30[0][0] + confusion_matrix_l30[1][1]) / (confusion_matrix_l30[0][0] + confusion_matrix_l30[0][1] + confusion_matrix_l30[1][0] + confusion_matrix_l30[1][1])
accuracy_naive_bayes_l30 

0.8464260438782731

In [41]:
# Test on 30to40 set
gnb_pred_30to40 = gnb.fit(x_train_unawareness, y_train).predict(x_test_30to40)

test_df = x_test_30to40.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(gnb_pred_30to40, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_30to40 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_30to40



array([[3045,   92],
       [ 394,   14]])

In [42]:
accuracy_naive_bayes_30to40 = (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[1][1]) / (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[0][1] + confusion_matrix_30to40[1][0] + confusion_matrix_30to40[1][1])
accuracy_naive_bayes_30to40 

0.8629055007052187

In [43]:
# Test on 40to50 set
gnb_pred_40to50 = gnb.fit(x_train_unawareness, y_train).predict(x_test_40to50)

test_df = x_test_40to50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(gnb_pred_40to50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_40to50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_40to50

array([[1894,   68],
       [ 228,   12]])

In [44]:
accuracy_naive_bayes_40to50 = (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[1][1]) / (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[0][1] + confusion_matrix_40to50[1][0] + confusion_matrix_40to50[1][1])
accuracy_naive_bayes_40to50 # 0.8718606782768102

0.8655767484105359

In [45]:
# Test on g50 set
gnb_pred_g50 = gnb.fit(x_train_unawareness, y_train).predict(x_test_g50)

test_df = x_test_g50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(gnb_pred_g50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_g50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_g50

array([[1575,   77],
       [ 179,   18]])

In [46]:
accuracy_naive_bayes_g50 = (confusion_matrix_g50[0][0] + confusion_matrix_g50[1][1]) / (confusion_matrix_g50[0][0] + confusion_matrix_g50[0][1] + confusion_matrix_g50[1][0] + confusion_matrix_g50[1][1])
accuracy_naive_bayes_g50 # 0.8718606782768102

0.8615467820443483

Random Forest Model

In [1]:
%%time
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(max_depth=5, random_state=0, class_weight='balanced')
rf_pred = rf.fit(x_train, y_train).predict(x_test)

NameError: name 'x_train' is not defined

In [48]:
test_df = x_test.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(rf_pred, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])
test_df.columns.values

array(['balance', 'day', 'duration', 'campaign', 'pdays', 'previous',
       'biDefault', 'biHousing', 'biLoan', 'catAge_30-40', 'catAge_40-50',
       'catAge_<=30', 'catAge_>=50', 'job_admin.', 'job_blue-collar',
       'job_entrepreneur', 'job_housemaid', 'job_management',
       'job_retired', 'job_self-employed', 'job_services', 'job_student',
       'job_technician', 'job_unemployed', 'marital_divorced',
       'marital_married', 'marital_single', 'education_primary',
       'education_secondary', 'education_tertiary', 'month_apr',
       'month_aug', 'month_dec', 'month_feb', 'month_jan', 'month_jul',
       'month_jun', 'month_mar', 'month_may', 'month_nov', 'month_oct',
       'month_sep', 'Fmonth_apr', 'Fmonth_aug', 'Fmonth_dec',
       'Fmonth_feb', 'Fmonth_jan', 'Fmonth_jul', 'Fmonth_jun',
       'Fmonth_mar', 'Fmonth_may', 'Fmonth_nov', 'Fmonth_oct', 'biY',
       'pred', 'accurate'], dtype=object)

In [49]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix

array([[4772, 3228],
       [ 617,  392]])

In [50]:
# Accuracy
# "Accuracy: ", test_df.accurate.mean()
accuracy_rf = (confusion_matrix[0][0] + confusion_matrix[1][1]) / (confusion_matrix[0][0] + confusion_matrix[0][1] + confusion_matrix[1][0] + confusion_matrix[1][1])
accuracy_rf


0.5732045732045732

In [51]:
# Split dataset based on marital status
test_df.columns.values
test_l30 = x_test[x_test['catAge_<=30'] == 1]
test_30to40 = x_test[x_test['catAge_30-40'] == 1]
test_40to50 = x_test[x_test['catAge_40-50'] == 1]
test_g50 = x_test[x_test['catAge_>=50'] == 1]

In [52]:
# Test on single subset
rf_pred_l30 = rf.fit(x_train, y_train).predict(test_l30)

test_df = test_l30.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(rf_pred_l30, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_l30 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_l30

array([[785, 464],
       [103,  61]])

In [53]:
accuracy_rf_l30 = (confusion_matrix_l30[0][0] + confusion_matrix_l30[1][1]) / (confusion_matrix_l30[0][0] + confusion_matrix_l30[0][1] + confusion_matrix_l30[1][0] + confusion_matrix_l30[1][1])
accuracy_rf_l30

0.5987261146496815

In [54]:
# Test on 30to40 subset
rf_pred_30to40 = rf.fit(x_train, y_train).predict(test_30to40)

test_df = test_30to40.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(rf_pred_30to40, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_30to40 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_30to40

array([[1757, 1380],
       [ 234,  174]])

In [55]:
accuracy_rf_30to40 = (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[1][1]) / (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[0][1] + confusion_matrix_30to40[1][0] + confusion_matrix_30to40[1][1])
accuracy_rf_30to40

0.5447108603667137

In [56]:
# Test on 40to50 subset
rf_pred_40to50 = rf.fit(x_train, y_train).predict(test_40to50)
 
test_df = test_40to50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(rf_pred_40to50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])
 
from sklearn.metrics import confusion_matrix
 
confusion_matrix_40to50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_40to50


array([[1230,  732],
       [ 158,   82]])

In [57]:
accuracy_rf_40to50 = (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[1][1]) / (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[0][1] + confusion_matrix_40to50[1][0] + confusion_matrix_40to50[1][1])
accuracy_rf_40to50 

0.5958219800181653

In [58]:
# Test on g50 subset
rf_pred_g50 = rf.fit(x_train, y_train).predict(test_g50)
 
test_df = test_g50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(rf_pred_g50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])
 
from sklearn.metrics import confusion_matrix
 
confusion_matrix_g50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_g50

array([[1000,  652],
       [ 122,   75]])

In [59]:
accuracy_rf_g50 = (confusion_matrix_g50[0][0] + confusion_matrix_g50[1][1]) / (confusion_matrix_g50[0][0] + confusion_matrix_g50[0][1] + confusion_matrix_g50[1][0] + confusion_matrix_g50[1][1])
accuracy_rf_g50 

0.5813953488372093

In [60]:
#Demographic Parity
# positive rate = TP + TN
PR_rf_l30 = confusion_matrix_l30[0,0] +confusion_matrix_l30[1,1]
PR_rf_l30 # 4756

846

In [61]:
PR_rf_30to40 = confusion_matrix_30to40[0,0] +confusion_matrix_30to40[1,1]
PR_rf_30to40 # 2136

1931

In [62]:
PR_rf_40to50 = confusion_matrix_40to50[0,0] +confusion_matrix_40to50[1,1]
PR_rf_40to50 # 2136

1312

In [63]:
PR_rf_g50 = confusion_matrix_g50[0,0] +confusion_matrix_g50[1,1]
PR_rf_g50 # 2136

1075

In [64]:
# Equalized Opportunity
#TPR = TP/TP+FN

TPR_rf_l30 = confusion_matrix_l30[0,0] / (confusion_matrix_l30[0,0] + confusion_matrix_l30[1,0])

TPR_rf_l30

0.884009009009009

In [65]:
TPR_rf_30to40 = confusion_matrix_30to40[0,0] / (confusion_matrix_30to40[0,0] + confusion_matrix_30to40[1,0])

TPR_rf_30to40  

0.8824711200401808

In [66]:
TPR_rf_40to50  = confusion_matrix_40to50[0,0] / (confusion_matrix_40to50[0,0] + confusion_matrix_40to50[1,0])

TPR_rf_40to50 

0.8861671469740634

In [67]:
TPR_rf_g50  = confusion_matrix_g50[0,0] / (confusion_matrix_g50[0,0] + confusion_matrix_g50[1,0])

TPR_rf_g50 

0.8912655971479501

In [68]:
# Equalized Odds
#TPR = TP/TP+FN
#FNR = FN/FN+TP


FNR_rf_l30 = confusion_matrix_l30[1,0] / (confusion_matrix_l30[1,0] + confusion_matrix_l30[0,0])

FNR_rf_l30 # 0.11652109273369263


0.11599099099099099

In [69]:
FNR_rf_30to40 = confusion_matrix_30to40[1,0] / (confusion_matrix_30to40[1,0] + confusion_matrix_30to40[0,0])

FNR_rf_30to40

0.11752887995981919

In [70]:
FNR_rf_40to50 = confusion_matrix_40to50[1,0] / (confusion_matrix_40to50[1,0] + confusion_matrix_40to50[0,0])

FNR_rf_40to50

0.1138328530259366

In [71]:
FNR_rf_g50 = confusion_matrix_g50[1,0] / (confusion_matrix_g50[1,0] + confusion_matrix_g50[0,0])

FNR_rf_g50

0.10873440285204991

In [72]:
# Fairness Through Unwareness
x_train_unawareness = x_train.copy()
x_train_unawareness
x_train_unawareness.drop('catAge_<=30', inplace=True, axis=1)
x_train_unawareness.drop('catAge_30-40', inplace=True, axis=1)
x_train_unawareness.drop('catAge_40-50', inplace=True, axis=1)
x_train_unawareness.drop('catAge_>=50', inplace=True, axis=1)

# x_train_unawareness.columns.values
# x_train.columns.values

In [73]:
#Fairness through unawareness

x_test_unawareness = x_test.copy()
x_test_unawareness
x_test_l30 = x_test_unawareness[x_test_unawareness['catAge_<=30'] == 1]
x_test_30to40 = x_test_unawareness[x_test_unawareness['catAge_30-40'] == 1]
x_test_40to50 = x_test_unawareness[x_test_unawareness['catAge_40-50'] == 1]
x_test_g50 = x_test_unawareness[x_test_unawareness['catAge_>=50'] == 1]


x_test_l30.drop('catAge_<=30', inplace=True, axis=1)
x_test_l30.drop('catAge_30-40', inplace=True, axis=1)
x_test_l30.drop('catAge_40-50', inplace=True, axis=1)
x_test_l30.drop('catAge_>=50', inplace=True, axis=1)

x_test_30to40.drop('catAge_<=30', inplace=True, axis=1)
x_test_30to40.drop('catAge_30-40', inplace=True, axis=1)
x_test_30to40.drop('catAge_40-50', inplace=True, axis=1)
x_test_30to40.drop('catAge_>=50', inplace=True, axis=1)

x_test_40to50.drop('catAge_<=30', inplace=True, axis=1)
x_test_40to50.drop('catAge_30-40', inplace=True, axis=1)
x_test_40to50.drop('catAge_40-50', inplace=True, axis=1)
x_test_40to50.drop('catAge_>=50', inplace=True, axis=1)

x_test_g50.drop('catAge_<=30', inplace=True, axis=1)
x_test_g50.drop('catAge_30-40', inplace=True, axis=1)
x_test_g50.drop('catAge_40-50', inplace=True, axis=1)
x_test_g50.drop('catAge_>=50', inplace=True, axis=1)



# x_test_unawareness.columns.values
# x_test.columns.values

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/core/frame.py:4163: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


In [74]:
# Test on l30 set
rf_pred_l30 = rf.fit(x_train_unawareness, y_train).predict(x_test_l30)

test_df = x_test_l30.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(rf_pred_l30, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_l30 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_l30


array([[760, 489],
       [106,  58]])

In [75]:
accuracy_rf_l30 = (confusion_matrix_l30[0][0] + confusion_matrix_l30[1][1]) / (confusion_matrix_l30[0][0] + confusion_matrix_l30[0][1] + confusion_matrix_l30[1][0] + confusion_matrix_l30[1][1])
accuracy_rf_l30

0.5789101203113942

In [76]:
# Test on 30to40 set
rf_pred_30to40 = rf.fit(x_train_unawareness, y_train).predict(x_test_30to40)

test_df = x_test_30to40.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(rf_pred_30to40, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_30to40 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_30to40


array([[1879, 1258],
       [ 246,  162]])

In [77]:
accuracy_rf_30to40 = (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[1][1]) / (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[0][1] + confusion_matrix_30to40[1][0] + confusion_matrix_30to40[1][1])
accuracy_rf_30to40 

0.57574047954866

In [78]:
# Test on 40to50 set
rf_pred_40to50 = rf.fit(x_train_unawareness, y_train).predict(x_test_40to50)

test_df = x_test_40to50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(rf_pred_40to50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_40to50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_40to50

array([[1116,  846],
       [ 140,  100]])

In [79]:
accuracy_rf_40to50 = (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[1][1]) / (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[0][1] + confusion_matrix_40to50[1][0] + confusion_matrix_40to50[1][1])
accuracy_rf_40to50 # 0.8718606782768102

0.5522252497729337

In [80]:
# Test on g50 set
rf_pred_g50 = rf.fit(x_train_unawareness, y_train).predict(x_test_g50)

test_df = x_test_g50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(rf_pred_g50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_g50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_g50

array([[868, 784],
       [106,  91]])

In [81]:
accuracy_rf_g50 = (confusion_matrix_g50[0][0] + confusion_matrix_g50[1][1]) / (confusion_matrix_g50[0][0] + confusion_matrix_g50[0][1] + confusion_matrix_g50[1][0] + confusion_matrix_g50[1][1])
accuracy_rf_g50 # 0.8718606782768102

0.5186587344510546

Support Vector Machine

In [82]:
%%time
from sklearn import svm as svm_model
svm = svm_model.SVC(class_weight='balanced') # add class_weight='balanced' is to avoid classifying all data as 0
svm_pred = svm.fit(x_train, y_train).predict(x_test)

In [83]:
test_df = x_test.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(svm_pred, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])
test_df.columns.values

array(['balance', 'day', 'duration', 'campaign', 'pdays', 'previous',
       'biDefault', 'biHousing', 'biLoan', 'catAge_30-40', 'catAge_40-50',
       'catAge_<=30', 'catAge_>=50', 'job_admin.', 'job_blue-collar',
       'job_entrepreneur', 'job_housemaid', 'job_management',
       'job_retired', 'job_self-employed', 'job_services', 'job_student',
       'job_technician', 'job_unemployed', 'marital_divorced',
       'marital_married', 'marital_single', 'education_primary',
       'education_secondary', 'education_tertiary', 'month_apr',
       'month_aug', 'month_dec', 'month_feb', 'month_jan', 'month_jul',
       'month_jun', 'month_mar', 'month_may', 'month_nov', 'month_oct',
       'month_sep', 'Fmonth_apr', 'Fmonth_aug', 'Fmonth_dec',
       'Fmonth_feb', 'Fmonth_jan', 'Fmonth_jul', 'Fmonth_jun',
       'Fmonth_mar', 'Fmonth_may', 'Fmonth_nov', 'Fmonth_oct', 'biY',
       'pred', 'accurate'], dtype=object)

In [84]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix

array([[4664, 3336],
       [ 609,  400]])

In [85]:
# Accuracy
# "Accuracy: ", test_df.accurate.mean()
accuracy_svm = (confusion_matrix[0][0] + confusion_matrix[1][1]) / (confusion_matrix[0][0] + confusion_matrix[0][1] + confusion_matrix[1][0] + confusion_matrix[1][1])
accuracy_svm


0.562104562104562

In [86]:
# Split dataset based on marital status
test_df.columns.values
test_l30 = x_test[x_test['catAge_<=30'] == 1]
test_30to40 = x_test[x_test['catAge_30-40'] == 1]
test_40to50 = x_test[x_test['catAge_40-50'] == 1]
test_g50 = x_test[x_test['catAge_>=50'] == 1]

In [87]:
# Test on l30 subset
svm_pred_l30 = svm.fit(x_train, y_train).predict(test_l30)

test_df = test_l30.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(svm_pred_l30, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_l30 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_l30

array([[791, 458],
       [108,  56]])

In [88]:
accuracy_svm_l30 = (confusion_matrix_l30[0][0] + confusion_matrix_l30[1][1]) / (confusion_matrix_l30[0][0] + confusion_matrix_l30[0][1] + confusion_matrix_l30[1][0] + confusion_matrix_l30[1][1])
accuracy_svm_l30

0.5994338287331918

In [89]:
# Test on married subset
svm_pred_30to40 = svm.fit(x_train, y_train).predict(test_30to40)

test_df = test_30to40.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(svm_pred_30to40, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_30to40 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_30to40

array([[1892, 1245],
       [ 258,  150]])

In [90]:
accuracy_svm_30to40 = (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[1][1]) / (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[0][1] + confusion_matrix_30to40[1][0] + confusion_matrix_30to40[1][1])
accuracy_svm_30to40 # 0.8718606782768102

0.5760225669957687

In [91]:
# Test on 40to50 subset
svm_pred_40to50 = svm.fit(x_train, y_train).predict(test_40to50)

test_df = test_40to50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(svm_pred_40to50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_40to50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_40to50

array([[1134,  828],
       [ 142,   98]])

In [92]:
accuracy_svm_40to50 = (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[1][1]) / (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[0][1] + confusion_matrix_40to50[1][0] + confusion_matrix_40to50[1][1])
accuracy_svm_40to50 

0.5594913714804723

In [93]:
# Test on g50 subset
svm_pred_g50 = svm.fit(x_train, y_train).predict(test_g50)

test_df = test_g50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(svm_pred_g50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_g50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_g50

array([[847, 805],
       [101,  96]])

In [94]:
accuracy_svm_g50 = (confusion_matrix_g50[0][0] + confusion_matrix_g50[1][1]) / (confusion_matrix_g50[0][0] + confusion_matrix_g50[0][1] + confusion_matrix_g50[1][0] + confusion_matrix_g50[1][1])
accuracy_svm_g50 # 0.8718606782768102

0.5100054083288263

In [95]:
#Demographic Parity
# positive rate = TP + TN
PR_svm_l30 = confusion_matrix_l30[0,0] +confusion_matrix_l30[1,1]

PR_svm_l30

847

In [96]:
PR_svm_30to40 = confusion_matrix_30to40[0,0] +confusion_matrix_30to40[1,1]
PR_svm_30to40

2042

In [97]:
PR_svm_40to50 = confusion_matrix_40to50[0,0] +confusion_matrix_40to50[1,1]
PR_svm_40to50

1232

In [98]:
PR_svm_g50 = confusion_matrix_g50[0,0] +confusion_matrix_g50[1,1]
PR_svm_g50

943

In [99]:
# Equalized Opportunity
#TPR = TP/TP+FN

TPR_svm_l30 = confusion_matrix_l30[0,0] / (confusion_matrix_l30[0,0] + confusion_matrix_l30[1,0])

TPR_svm_l30

0.8798665183537263

In [100]:
TPR_svm_30to40 = confusion_matrix_30to40[0,0] / (confusion_matrix_30to40[0,0] + confusion_matrix_30to40[1,0])

TPR_svm_30to40 

0.88

In [101]:
TPR_svm_40to50 = confusion_matrix_40to50[0,0] / (confusion_matrix_40to50[0,0] + confusion_matrix_40to50[1,0])

TPR_svm_40to50 

0.8887147335423198

In [102]:
TPR_svm_g50 = confusion_matrix_g50[0,0] / (confusion_matrix_g50[0,0] + confusion_matrix_g50[1,0])

TPR_svm_g50 

0.8934599156118144

In [103]:
# Equalized Odds
#TPR = TP/TP+FN
#FNR = FN/FN+TP


FNR_svm_l30 = confusion_matrix_l30[1,0] / (confusion_matrix_l30[1,0] + confusion_matrix_l30[0,0])

FNR_svm_l30

0.12013348164627363

In [104]:
FNR_svm_30to40 = confusion_matrix_30to40[1,0] / (confusion_matrix_30to40[1,0] + confusion_matrix_30to40[0,0])

FNR_svm_30to40 

0.12

In [105]:
FNR_svm_40to50 = confusion_matrix_40to50[1,0] / (confusion_matrix_40to50[1,0] + confusion_matrix_40to50[0,0])

FNR_svm_40to50 

0.11128526645768025

In [106]:
FNR_svm_g50 = confusion_matrix_g50[1,0] / (confusion_matrix_g50[1,0] + confusion_matrix_g50[0,0])

FNR_svm_g50 

0.10654008438818566

In [107]:
# Fairness Through Unwareness
x_train_unawareness = x_train.copy()
x_train_unawareness
x_train_unawareness.drop('catAge_<=30', inplace=True, axis=1)
x_train_unawareness.drop('catAge_30-40', inplace=True, axis=1)
x_train_unawareness.drop('catAge_40-50', inplace=True, axis=1)
x_train_unawareness.drop('catAge_>=50', inplace=True, axis=1)


# x_train_unawareness.columns.values
# x_train.columns.values

In [108]:
#Fairness through unawareness


x_test_unawareness = x_test.copy()
x_test_unawareness
x_test_l30 = x_test_unawareness[x_test_unawareness['catAge_<=30'] == 1]
x_test_30to40 = x_test_unawareness[x_test_unawareness['catAge_30-40'] == 1]
x_test_40to50 = x_test_unawareness[x_test_unawareness['catAge_40-50'] == 1]
x_test_g50 = x_test_unawareness[x_test_unawareness['catAge_>=50'] == 1]


x_test_l30.drop('catAge_<=30', inplace=True, axis=1)
x_test_l30.drop('catAge_30-40', inplace=True, axis=1)
x_test_l30.drop('catAge_40-50', inplace=True, axis=1)
x_test_l30.drop('catAge_>=50', inplace=True, axis=1)

x_test_30to40.drop('catAge_<=30', inplace=True, axis=1)
x_test_30to40.drop('catAge_30-40', inplace=True, axis=1)
x_test_30to40.drop('catAge_40-50', inplace=True, axis=1)
x_test_30to40.drop('catAge_>=50', inplace=True, axis=1)

x_test_40to50.drop('catAge_<=30', inplace=True, axis=1)
x_test_40to50.drop('catAge_30-40', inplace=True, axis=1)
x_test_40to50.drop('catAge_40-50', inplace=True, axis=1)
x_test_40to50.drop('catAge_>=50', inplace=True, axis=1)

x_test_g50.drop('catAge_<=30', inplace=True, axis=1)
x_test_g50.drop('catAge_30-40', inplace=True, axis=1)
x_test_g50.drop('catAge_40-50', inplace=True, axis=1)
x_test_g50.drop('catAge_>=50', inplace=True, axis=1)



/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/core/frame.py:4163: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


In [109]:
# Test on l30 set
svm_pred_l30 = svm.fit(x_train_unawareness, y_train).predict(x_test_l30)

test_df = x_test_l30.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(svm_pred_l30, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_l30 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_l30


array([[791, 458],
       [108,  56]])

In [110]:
accuracy_svm_l30 = (confusion_matrix_l30[0][0] + confusion_matrix_l30[1][1]) / (confusion_matrix_l30[0][0] + confusion_matrix_l30[0][1] + confusion_matrix_l30[1][0] + confusion_matrix_l30[1][1])
accuracy_svm_l30

0.5994338287331918

In [111]:
# Test on 30to40 set
svm_pred_30to40 = svm.fit(x_train_unawareness, y_train).predict(x_test_30to40)

test_df = x_test_30to40.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(svm_pred_30to40, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_30to40 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_30to40

array([[1892, 1245],
       [ 258,  150]])

In [112]:
accuracy_svm_30to40 = (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[1][1]) / (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[0][1] + confusion_matrix_30to40[1][0] + confusion_matrix_30to40[1][1])
accuracy_svm_30to40 # 0.8718606782768102

0.5760225669957687

In [113]:
# Test on 40to50 subset
svm_pred_40to50 = svm.fit(x_train_unawareness, y_train).predict(x_test_40to50)

test_df = x_test_40to50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(svm_pred_40to50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_40to50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_40to50

array([[1134,  828],
       [ 142,   98]])

In [114]:
accuracy_svm_40to50 = (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[1][1]) / (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[0][1] + confusion_matrix_40to50[1][0] + confusion_matrix_40to50[1][1])
accuracy_svm_40to50 

0.5594913714804723

In [115]:
# Test on g50 subset
svm_pred_g50 = svm.fit(x_train_unawareness, y_train).predict(x_test_g50)

test_df = x_test_g50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(svm_pred_g50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_g50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_g50

array([[847, 805],
       [101,  96]])

In [116]:
accuracy_svm_g50 = (confusion_matrix_g50[0][0] + confusion_matrix_g50[1][1]) / (confusion_matrix_g50[0][0] + confusion_matrix_g50[0][1] + confusion_matrix_g50[1][0] + confusion_matrix_g50[1][1])
accuracy_svm_g50 

0.5100054083288263

Logistic Regression Model

In [117]:
%%time
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(random_state=0, class_weight='balanced')
clf_pred = clf.fit(x_train, y_train).predict(x_test)

In [118]:
test_df = x_test.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(clf_pred, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])
test_df.columns.values

array(['balance', 'day', 'duration', 'campaign', 'pdays', 'previous',
       'biDefault', 'biHousing', 'biLoan', 'catAge_30-40', 'catAge_40-50',
       'catAge_<=30', 'catAge_>=50', 'job_admin.', 'job_blue-collar',
       'job_entrepreneur', 'job_housemaid', 'job_management',
       'job_retired', 'job_self-employed', 'job_services', 'job_student',
       'job_technician', 'job_unemployed', 'marital_divorced',
       'marital_married', 'marital_single', 'education_primary',
       'education_secondary', 'education_tertiary', 'month_apr',
       'month_aug', 'month_dec', 'month_feb', 'month_jan', 'month_jul',
       'month_jun', 'month_mar', 'month_may', 'month_nov', 'month_oct',
       'month_sep', 'Fmonth_apr', 'Fmonth_aug', 'Fmonth_dec',
       'Fmonth_feb', 'Fmonth_jan', 'Fmonth_jul', 'Fmonth_jun',
       'Fmonth_mar', 'Fmonth_may', 'Fmonth_nov', 'Fmonth_oct', 'biY',
       'pred', 'accurate'], dtype=object)

In [119]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix

array([[3147, 4853],
       [ 388,  621]])

In [120]:
# Accuracy
# "Accuracy: ", test_df.accurate.mean()
accuracy_clf = (confusion_matrix[0][0] + confusion_matrix[1][1]) / (confusion_matrix[0][0] + confusion_matrix[0][1] + confusion_matrix[1][0] + confusion_matrix[1][1])
accuracy_clf

0.41824841824841824

In [121]:
# Split dataset based on marital status
test_df.columns.values
test_l30 = x_test[x_test['catAge_<=30'] == 1]
test_30to40 = x_test[x_test['catAge_30-40'] == 1]
test_40to50 = x_test[x_test['catAge_40-50'] == 1]
test_g50 = x_test[x_test['catAge_>=50'] == 1]

In [122]:
# Test on l30 subset
clf_pred_l30 = clf.fit(x_train, y_train).predict(test_l30)

test_df = test_l30.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(clf_pred_l30, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_l30 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_l30

array([[462, 787],
       [ 58, 106]])

In [123]:
accuracy_clf_l30 = (confusion_matrix_l30[0][0] + confusion_matrix_l30[1][1]) / (confusion_matrix_l30[0][0] + confusion_matrix_l30[0][1] + confusion_matrix_l30[1][0] + confusion_matrix_l30[1][1])
accuracy_clf_l30

0.4019815994338287

In [124]:
# Test on 30to40 subset
clf_pred_30to40 = clf.fit(x_train, y_train).predict(test_30to40)

test_df = test_30to40.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(clf_pred_30to40, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_30to40 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_30to40

array([[1255, 1882],
       [ 163,  245]])

In [125]:
accuracy_clf_30to40 = (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[1][1]) / (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[0][1] + confusion_matrix_30to40[1][0] + confusion_matrix_30to40[1][1])
accuracy_clf_30to40

0.4231311706629055

In [126]:
# Test on 40to50 subset
clf_pred_40to50 = clf.fit(x_train, y_train).predict(test_40to50)
 
test_df = test_40to50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(clf_pred_40to50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])
 
from sklearn.metrics import confusion_matrix
 
confusion_matrix_40to50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_40to50

array([[ 808, 1154],
       [ 100,  140]])

In [127]:
accuracy_clf_40to50 = (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[1][1]) / (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[0][1] + confusion_matrix_40to50[1][0] + confusion_matrix_40to50[1][1])
accuracy_clf_40to50 

0.4305177111716621

In [128]:
# Test on g50 subset
clf_pred_g50 = clf.fit(x_train, y_train).predict(test_g50)
 
test_df = test_g50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(clf_pred_g50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])
 
from sklearn.metrics import confusion_matrix
 
confusion_matrix_g50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_g50

array([[ 622, 1030],
       [  67,  130]])

In [129]:
accuracy_clf_g50 = (confusion_matrix_g50[0][0] + confusion_matrix_g50[1][1]) / (confusion_matrix_g50[0][0] + confusion_matrix_g50[0][1] + confusion_matrix_g50[1][0] + confusion_matrix_g50[1][1])
accuracy_clf_g50 

0.40670632774472687

In [130]:
#Demographic Parity
# positive rate = TP + TN
PR_clf_l30 = confusion_matrix_l30[0,0] +confusion_matrix_l30[1,1]
PR_clf_l30 # 4756

568

In [131]:
PR_clf_30to40 = confusion_matrix_30to40[0,0] +confusion_matrix_30to40[1,1]
PR_clf_30to40 # 2136

1500

In [132]:
PR_clf_40to50 = confusion_matrix_40to50[0,0] +confusion_matrix_40to50[1,1]
PR_clf_40to50 # 2136

948

In [133]:
PR_clf_g50 = confusion_matrix_g50[0,0] +confusion_matrix_g50[1,1]
PR_clf_g50 # 2136

752

In [134]:
# Equalized Opportunity
#TPR = TP/TP+FN

TPR_clf_l30 = confusion_matrix_l30[0,0] / (confusion_matrix_l30[0,0] + confusion_matrix_l30[1,0])

TPR_clf_l30

0.8884615384615384

In [135]:
TPR_clf_30to40 = confusion_matrix_30to40[0,0] / (confusion_matrix_30to40[0,0] + confusion_matrix_30to40[1,0])

TPR_clf_30to40  

0.885049365303244

In [136]:
TPR_clf_40to50  = confusion_matrix_40to50[0,0] / (confusion_matrix_40to50[0,0] + confusion_matrix_40to50[1,0])

TPR_clf_40to50 

0.8898678414096917

In [137]:
TPR_clf_g50  = confusion_matrix_g50[0,0] / (confusion_matrix_g50[0,0] + confusion_matrix_g50[1,0])

TPR_clf_g50 

0.9027576197387518

In [138]:
# Equalized Odds
#TPR = TP/TP+FN
#FNR = FN/FN+TP


FNR_clf_l30 = confusion_matrix_l30[1,0] / (confusion_matrix_l30[1,0] + confusion_matrix_l30[0,0])

FNR_clf_l30 # 0.11652109273369263

0.11153846153846154

In [139]:
FNR_clf_30to40 = confusion_matrix_30to40[1,0] / (confusion_matrix_30to40[1,0] + confusion_matrix_30to40[0,0])

FNR_clf_30to40

0.114950634696756

In [140]:
FNR_clf_40to50 = confusion_matrix_40to50[1,0] / (confusion_matrix_40to50[1,0] + confusion_matrix_40to50[0,0])

FNR_clf_40to50

0.11013215859030837

In [141]:
FNR_clf_g50 = confusion_matrix_g50[1,0] / (confusion_matrix_g50[1,0] + confusion_matrix_g50[0,0])

FNR_clf_g50

0.09724238026124818

In [142]:
# Fairness Through Unwareness
x_train_unawareness = x_train.copy()
x_train_unawareness
x_train_unawareness.drop('catAge_<=30', inplace=True, axis=1)
x_train_unawareness.drop('catAge_30-40', inplace=True, axis=1)
x_train_unawareness.drop('catAge_40-50', inplace=True, axis=1)
x_train_unawareness.drop('catAge_>=50', inplace=True, axis=1)

# x_train_unawareness.columns.values
# x_train.columns.values

In [143]:
#Fairness through unawareness

x_test_unawareness = x_test.copy()
x_test_unawareness
x_test_l30 = x_test_unawareness[x_test_unawareness['catAge_<=30'] == 1]
x_test_30to40 = x_test_unawareness[x_test_unawareness['catAge_30-40'] == 1]
x_test_40to50 = x_test_unawareness[x_test_unawareness['catAge_40-50'] == 1]
x_test_g50 = x_test_unawareness[x_test_unawareness['catAge_>=50'] == 1]


x_test_l30.drop('catAge_<=30', inplace=True, axis=1)
x_test_l30.drop('catAge_30-40', inplace=True, axis=1)
x_test_l30.drop('catAge_40-50', inplace=True, axis=1)
x_test_l30.drop('catAge_>=50', inplace=True, axis=1)

x_test_30to40.drop('catAge_<=30', inplace=True, axis=1)
x_test_30to40.drop('catAge_30-40', inplace=True, axis=1)
x_test_30to40.drop('catAge_40-50', inplace=True, axis=1)
x_test_30to40.drop('catAge_>=50', inplace=True, axis=1)

x_test_40to50.drop('catAge_<=30', inplace=True, axis=1)
x_test_40to50.drop('catAge_30-40', inplace=True, axis=1)
x_test_40to50.drop('catAge_40-50', inplace=True, axis=1)
x_test_40to50.drop('catAge_>=50', inplace=True, axis=1)

x_test_g50.drop('catAge_<=30', inplace=True, axis=1)
x_test_g50.drop('catAge_30-40', inplace=True, axis=1)
x_test_g50.drop('catAge_40-50', inplace=True, axis=1)
x_test_g50.drop('catAge_>=50', inplace=True, axis=1)



# x_test_unawareness.columns.values
# x_test.columns.values

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/core/frame.py:4163: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


In [144]:
# Test on l30 set
clf_pred_l30 = clf.fit(x_train_unawareness, y_train).predict(x_test_l30)

test_df = x_test_l30.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(clf_pred_l30, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_l30 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_l30

array([[541, 708],
       [ 61, 103]])

In [145]:
accuracy_clf_l30 = (confusion_matrix_l30[0][0] + confusion_matrix_l30[1][1]) / (confusion_matrix_l30[0][0] + confusion_matrix_l30[0][1] + confusion_matrix_l30[1][0] + confusion_matrix_l30[1][1])
accuracy_clf_l30

0.4557678697806086

In [146]:
# Test on 30to40 set
clf_pred_30to40 = clf.fit(x_train_unawareness, y_train).predict(x_test_30to40)

test_df = x_test_30to40.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(clf_pred_30to40, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_30to40 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_30to40


array([[1517, 1620],
       [ 188,  220]])

In [147]:
accuracy_clf_30to40 = (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[1][1]) / (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[0][1] + confusion_matrix_30to40[1][0] + confusion_matrix_30to40[1][1])
accuracy_clf_30to40 

0.48998589562764455

In [148]:
# Test on 40to50 set
clf_pred_40to50 = clf.fit(x_train_unawareness, y_train).predict(x_test_40to50)

test_df = x_test_40to50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(clf_pred_40to50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_40to50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_40to50

array([[ 923, 1039],
       [ 110,  130]])

In [149]:
accuracy_clf_40to50 = (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[1][1]) / (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[0][1] + confusion_matrix_40to50[1][0] + confusion_matrix_40to50[1][1])
accuracy_clf_40to50 # 0.8718606782768102

0.4782016348773842

In [150]:
# Test on g50 set
clf_pred_g50 = clf.fit(x_train_unawareness, y_train).predict(x_test_g50)

test_df = x_test_g50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(clf_pred_g50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_g50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_g50

array([[688, 964],
       [ 63, 134]])

In [151]:
accuracy_clf_g50 = (confusion_matrix_g50[0][0] + confusion_matrix_g50[1][1]) / (confusion_matrix_g50[0][0] + confusion_matrix_g50[0][1] + confusion_matrix_g50[1][0] + confusion_matrix_g50[1][1])
accuracy_clf_g50 # 0.8718606782768102

0.4445646295294754

Linear Regression model

In [152]:
from sklearn import linear_model
linear_regression_model = linear_model.LinearRegression()
linear_regression_model.fit(x_train, y_train)
prediction = linear_regression_model.predict(x_test)

Result

In [153]:
test_df = x_test.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(prediction, index=test_df.index)

test_df['accurate'] = (test_df['pred'] == test_df['biY'])
test_df['pred']

34105    0.107862
9520     0.110701
28984    0.117581
40986    0.132641
32557    0.127812
           ...   
10227    0.129159
38243    0.119689
3337     0.108867
32501    0.113560
19183    0.118242
Name: pred, Length: 9009, dtype: float64