Credit Scoring Fairness Criteria

Load the dataset

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.cm as cm

Load the dataset

In [2]:
import os
BANK_PATH = os.path.join(os.getcwd(), 'ML fairness/ml bank dataset/bankfullclean.csv') # Assign this to the location of the dataset
print(os.getcwd())
print(BANK_PATH)

# 5254 number of rows have 'biY' == 1
# 39787 number of rows have 'biY' == 0


/Users/xinyu/Desktop/Research/Machine-Learning-Fairness--main
/Users/xinyu/Desktop/Research/Machine-Learning-Fairness--main/ML fairness/ml bank dataset/bankfullclean.csv


In [3]:
bank = pd.read_csv(BANK_PATH)
df = pd.DataFrame(bank)
df.head()
dummy = df[['catAge', 'job', 'marital','education','balance','day', 'month', 'duration', 'campaign', 'pdays', 'previous', 'Fmonth', 'biDefault', 'biHousing', 'biLoan']]
# dummy.columns.values
dummy = pd.get_dummies(data=dummy)
# dummy.head()
dummy.columns.values
# df['marital'].unique()

# df['biY'].replace({0: False, 1: True}, inplace=True)
# print(df['biY'])


array(['balance', 'day', 'duration', 'campaign', 'pdays', 'previous',
       'biDefault', 'biHousing', 'biLoan', 'catAge_30-40', 'catAge_40-50',
       'catAge_<=30', 'catAge_>=50', 'job_admin.', 'job_blue-collar',
       'job_entrepreneur', 'job_housemaid', 'job_management',
       'job_retired', 'job_self-employed', 'job_services', 'job_student',
       'job_technician', 'job_unemployed', 'marital_divorced',
       'marital_married', 'marital_single', 'education_primary',
       'education_secondary', 'education_tertiary', 'month_apr',
       'month_aug', 'month_dec', 'month_feb', 'month_jan', 'month_jul',
       'month_jun', 'month_mar', 'month_may', 'month_nov', 'month_oct',
       'month_sep', 'Fmonth_apr', 'Fmonth_aug', 'Fmonth_dec',
       'Fmonth_feb', 'Fmonth_jan', 'Fmonth_jul', 'Fmonth_jun',
       'Fmonth_mar', 'Fmonth_may', 'Fmonth_nov', 'Fmonth_oct'],
      dtype=object)

Machine Learning Classification Model

In [4]:
%%time
from sklearn.model_selection import train_test_split
from sklearn.model_selection import LeaveOneOut

CPU times: user 1.43 s, sys: 315 ms, total: 1.75 s
Wall time: 2.62 s


In [5]:
%%time
def get_naive_dataset(dataset):
    dataset = dataset.sample(frac=1).reset_index(drop=True)
    X = dummy
    y = dataset['biY']
    x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
    
    return (x_train, y_train), (x_test, y_test)

CPU times: user 12 µs, sys: 2 µs, total: 14 µs
Wall time: 26.9 µs


In [6]:
%%time
(x_train, y_train), (x_test, y_test) = get_naive_dataset(df)

CPU times: user 71.3 ms, sys: 23.4 ms, total: 94.7 ms
Wall time: 113 ms


In [7]:
%%time
x_train.columns.values

CPU times: user 40 µs, sys: 2 µs, total: 42 µs
Wall time: 51.3 µs


array(['balance', 'day', 'duration', 'campaign', 'pdays', 'previous',
       'biDefault', 'biHousing', 'biLoan', 'catAge_30-40', 'catAge_40-50',
       'catAge_<=30', 'catAge_>=50', 'job_admin.', 'job_blue-collar',
       'job_entrepreneur', 'job_housemaid', 'job_management',
       'job_retired', 'job_self-employed', 'job_services', 'job_student',
       'job_technician', 'job_unemployed', 'marital_divorced',
       'marital_married', 'marital_single', 'education_primary',
       'education_secondary', 'education_tertiary', 'month_apr',
       'month_aug', 'month_dec', 'month_feb', 'month_jan', 'month_jul',
       'month_jun', 'month_mar', 'month_may', 'month_nov', 'month_oct',
       'month_sep', 'Fmonth_apr', 'Fmonth_aug', 'Fmonth_dec',
       'Fmonth_feb', 'Fmonth_jan', 'Fmonth_jul', 'Fmonth_jun',
       'Fmonth_mar', 'Fmonth_may', 'Fmonth_nov', 'Fmonth_oct'],
      dtype=object)

In [8]:
%%time
y_train.values

CPU times: user 28 µs, sys: 2 µs, total: 30 µs
Wall time: 38.1 µs


array([0, 0, 0, ..., 0, 0, 0])

In [9]:
%%time
x_test.columns.values

CPU times: user 52 µs, sys: 14 µs, total: 66 µs
Wall time: 727 µs


array(['balance', 'day', 'duration', 'campaign', 'pdays', 'previous',
       'biDefault', 'biHousing', 'biLoan', 'catAge_30-40', 'catAge_40-50',
       'catAge_<=30', 'catAge_>=50', 'job_admin.', 'job_blue-collar',
       'job_entrepreneur', 'job_housemaid', 'job_management',
       'job_retired', 'job_self-employed', 'job_services', 'job_student',
       'job_technician', 'job_unemployed', 'marital_divorced',
       'marital_married', 'marital_single', 'education_primary',
       'education_secondary', 'education_tertiary', 'month_apr',
       'month_aug', 'month_dec', 'month_feb', 'month_jan', 'month_jul',
       'month_jun', 'month_mar', 'month_may', 'month_nov', 'month_oct',
       'month_sep', 'Fmonth_apr', 'Fmonth_aug', 'Fmonth_dec',
       'Fmonth_feb', 'Fmonth_jan', 'Fmonth_jul', 'Fmonth_jun',
       'Fmonth_mar', 'Fmonth_may', 'Fmonth_nov', 'Fmonth_oct'],
      dtype=object)

In [10]:
%%time
y_test.values

CPU times: user 20 µs, sys: 1e+03 ns, total: 21 µs
Wall time: 26 µs


array([0, 1, 1, ..., 0, 0, 1])

Naive Bayes Model

In [11]:
%%time
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb_pred = gnb.fit(x_train, y_train).predict(x_test)

CPU times: user 148 ms, sys: 71.4 ms, total: 219 ms
Wall time: 272 ms


Result

In [12]:
%%time
test_df = x_test.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(gnb_pred, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])
test_df.columns.values

CPU times: user 10.4 ms, sys: 2.02 ms, total: 12.4 ms
Wall time: 24.4 ms


array(['balance', 'day', 'duration', 'campaign', 'pdays', 'previous',
       'biDefault', 'biHousing', 'biLoan', 'catAge_30-40', 'catAge_40-50',
       'catAge_<=30', 'catAge_>=50', 'job_admin.', 'job_blue-collar',
       'job_entrepreneur', 'job_housemaid', 'job_management',
       'job_retired', 'job_self-employed', 'job_services', 'job_student',
       'job_technician', 'job_unemployed', 'marital_divorced',
       'marital_married', 'marital_single', 'education_primary',
       'education_secondary', 'education_tertiary', 'month_apr',
       'month_aug', 'month_dec', 'month_feb', 'month_jan', 'month_jul',
       'month_jun', 'month_mar', 'month_may', 'month_nov', 'month_oct',
       'month_sep', 'Fmonth_apr', 'Fmonth_aug', 'Fmonth_dec',
       'Fmonth_feb', 'Fmonth_jan', 'Fmonth_jul', 'Fmonth_jun',
       'Fmonth_mar', 'Fmonth_may', 'Fmonth_nov', 'Fmonth_oct', 'biY',
       'pred', 'accurate'], dtype=object)

In [13]:
%%time
from sklearn.metrics import confusion_matrix

CPU times: user 31 µs, sys: 52 µs, total: 83 µs
Wall time: 46.7 µs


In [14]:
%%time
confusion_matrix = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix

CPU times: user 29.3 ms, sys: 4.15 ms, total: 33.4 ms
Wall time: 39.6 ms


array([[7567,  354],
       [1030,   58]])

In [15]:
%%time
# Accuracy
# "Accuracy: ", test_df.accurate.mean()
accuracy_naive_bayes = (confusion_matrix[0][0] + confusion_matrix[1][1]) / (confusion_matrix[0][0] + confusion_matrix[0][1] + confusion_matrix[1][0] + confusion_matrix[1][1])
accuracy_naive_bayes



CPU times: user 116 µs, sys: 3 µs, total: 119 µs
Wall time: 133 µs


0.8463758463758464

In [16]:
%%time
# Split dataset based on marital status
test_df.columns.values
test_l30 = x_test[x_test['catAge_<=30'] == 1]
test_30to40 = x_test[x_test['catAge_30-40'] == 1]
test_40to50 = x_test[x_test['catAge_40-50'] == 1]
test_g50 = x_test[x_test['catAge_>=50'] == 1]

CPU times: user 15.8 ms, sys: 4.54 ms, total: 20.3 ms
Wall time: 32.5 ms


In [17]:
%%time
# Test on l30 subset
gnb_pred_l30 = gnb.fit(x_train, y_train).predict(test_l30)

test_df = test_l30.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(gnb_pred_l30, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_l30 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_l30


CPU times: user 114 ms, sys: 20.9 ms, total: 135 ms
Wall time: 193 ms


array([[1111,   67],
       [ 171,   15]])

In [18]:
%%time
accuracy_naive_bayes_l30 = (confusion_matrix_l30[0][0] + confusion_matrix_l30[1][1]) / (confusion_matrix_l30[0][0] + confusion_matrix_l30[0][1] + confusion_matrix_l30[1][0] + confusion_matrix_l30[1][1])
accuracy_naive_bayes_l30

CPU times: user 66 µs, sys: 1 µs, total: 67 µs
Wall time: 76.1 µs


0.8255131964809385

In [19]:
%%time
# Test on 30to40 subset
gnb_pred_30to40 = gnb.fit(x_train, y_train).predict(test_30to40)

test_df = test_30to40.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(gnb_pred_30to40, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_30to40 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_30to40

CPU times: user 117 ms, sys: 12.6 ms, total: 129 ms
Wall time: 208 ms


array([[2983,  134],
       [ 405,   19]])

In [20]:
%%time
accuracy_naive_bayes_30to40 = (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[1][1]) / (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[0][1] + confusion_matrix_30to40[1][0] + confusion_matrix_30to40[1][1])
accuracy_naive_bayes_30to40

CPU times: user 59 µs, sys: 1e+03 ns, total: 60 µs
Wall time: 67.9 µs


0.8477831121152217

In [21]:
%%time
# Test on 40to50 subset
gnb_pred_40to50 = gnb.fit(x_train, y_train).predict(test_40to50)

test_df = test_40to50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(gnb_pred_40to50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_40to50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_40to50

CPU times: user 116 ms, sys: 11.3 ms, total: 128 ms
Wall time: 262 ms


array([[1965,   61],
       [ 265,   13]])

In [22]:
%%time
accuracy_naive_bayes_40to50 = (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[1][1]) / (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[0][1] + confusion_matrix_40to50[1][0] + confusion_matrix_40to50[1][1])
accuracy_naive_bayes_40to50 # 0.8718606782768102

CPU times: user 100 µs, sys: 2 µs, total: 102 µs
Wall time: 115 µs


0.8585069444444444

In [23]:
%%time
# Test on g50 subset

gnb_pred_g50 = gnb.fit(x_train, y_train).predict(test_g50)

test_df = test_g50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(gnb_pred_g50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_g50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_g50

CPU times: user 86.3 ms, sys: 12.6 ms, total: 98.9 ms
Wall time: 103 ms


array([[1508,   92],
       [ 189,   11]])

In [24]:
%%time
accuracy_naive_bayes_g50 = (confusion_matrix_g50[0][0] + confusion_matrix_g50[1][1]) / (confusion_matrix_g50[0][0] + confusion_matrix_g50[0][1] + confusion_matrix_g50[1][0] + confusion_matrix_g50[1][1])
accuracy_naive_bayes_g50 # 0.8718606782768102

CPU times: user 57 µs, sys: 0 ns, total: 57 µs
Wall time: 64.1 µs


0.8438888888888889

In [25]:
%%time
#Demographic Parity
# positive rate = (TP + FP)/total
PR_Naive_Bayes_l30 = (confusion_matrix_l30[1,1] +confusion_matrix_l30[0,1])/(confusion_matrix_l30[0][0] + confusion_matrix_l30[0][1] + confusion_matrix_l30[1][0] + confusion_matrix_l30[1][1])

PR_Naive_Bayes_l30 


CPU times: user 53 µs, sys: 1e+03 ns, total: 54 µs
Wall time: 61 µs


0.060117302052785926

In [26]:
%%time
PR_Naive_Bayes_30to40 = (confusion_matrix_30to40[1,1] +confusion_matrix_30to40[0,1])/(confusion_matrix_30to40[0][0] + confusion_matrix_30to40[0][1] + confusion_matrix_30to40[1][0] + confusion_matrix_30to40[1][1])
PR_Naive_Bayes_30to40

CPU times: user 57 µs, sys: 1e+03 ns, total: 58 µs
Wall time: 64.8 µs


0.043208133295679185

In [27]:
%%time
PR_Naive_Bayes_40to50 = (confusion_matrix_40to50[1,1] +confusion_matrix_40to50[0,1])/(confusion_matrix_40to50[0][0] + confusion_matrix_40to50[0][1] + confusion_matrix_40to50[1][0] + confusion_matrix_40to50[1][1])
PR_Naive_Bayes_40to50 

CPU times: user 54 µs, sys: 1 µs, total: 55 µs
Wall time: 62 µs


0.03211805555555555

In [28]:
%%time
PR_Naive_Bayes_g50 = (confusion_matrix_g50[1,1] +confusion_matrix_g50[0,1])/(confusion_matrix_g50[0][0] + confusion_matrix_g50[0][1] + confusion_matrix_g50[1][0] + confusion_matrix_g50[1][1])
PR_Naive_Bayes_g50 

CPU times: user 56 µs, sys: 0 ns, total: 56 µs
Wall time: 62.9 µs


0.05722222222222222

In [29]:
%%time
# Equalized Opportunity
#TPR = TP/TP+FN

TPR_Naive_Bayes_l30 = confusion_matrix_l30[1,1] / (confusion_matrix_l30[1,1] + confusion_matrix_l30[1,0])

TPR_Naive_Bayes_l30


CPU times: user 49 µs, sys: 0 ns, total: 49 µs
Wall time: 57.2 µs


0.08064516129032258

In [30]:
%%time
TPR_Naive_Bayes_30to40 = confusion_matrix_30to40[1,1] / (confusion_matrix_30to40[1,1] + confusion_matrix_30to40[1,0])

TPR_Naive_Bayes_30to40

CPU times: user 51 µs, sys: 1e+03 ns, total: 52 µs
Wall time: 58.9 µs


0.04481132075471698

In [31]:
%%time
TPR_Naive_Bayes_40to50 = confusion_matrix_40to50[1,1] / (confusion_matrix_40to50[1,1] + confusion_matrix_40to50[1,0])

TPR_Naive_Bayes_40to50 

CPU times: user 45 µs, sys: 1e+03 ns, total: 46 µs
Wall time: 52 µs


0.046762589928057555

In [32]:
%%time
TPR_Naive_Bayes_g50 = confusion_matrix_g50[1,1] / (confusion_matrix_g50[1,1] + confusion_matrix_g50[1,0])

TPR_Naive_Bayes_g50 # 0.8925619834710744

CPU times: user 44 µs, sys: 1e+03 ns, total: 45 µs
Wall time: 50.8 µs


0.055

In [33]:
%%time
# Equalized Odds
#TPR = TP/TP+FN
#FNR = FN/FN+TP


FNR_Naive_Bayes_l30 = confusion_matrix_l30[1,0] / (confusion_matrix_l30[1,0] + confusion_matrix_l30[1,1])

FNR_Naive_Bayes_l30



CPU times: user 44 µs, sys: 1e+03 ns, total: 45 µs
Wall time: 51 µs


0.9193548387096774

In [34]:
%%time
FNR_Naive_Bayes_30to40 = confusion_matrix_30to40[1,0] / (confusion_matrix_30to40[1,0] + confusion_matrix_30to40[1,1])

FNR_Naive_Bayes_30to40

CPU times: user 45 µs, sys: 1 µs, total: 46 µs
Wall time: 53.2 µs


0.9551886792452831

In [35]:
%%time
FNR_Naive_Bayes_40to50 = confusion_matrix_40to50[1,0] / (confusion_matrix_40to50[1,0] + confusion_matrix_40to50[1,1])

FNR_Naive_Bayes_40to50

CPU times: user 48 µs, sys: 1e+03 ns, total: 49 µs
Wall time: 55.8 µs


0.9532374100719424

In [36]:
%%time
FNR_Naive_Bayes_g50 = confusion_matrix_g50[1,0] / (confusion_matrix_g50[1,0] + confusion_matrix_g50[1,1])

FNR_Naive_Bayes_g50

CPU times: user 84 µs, sys: 2 µs, total: 86 µs
Wall time: 101 µs


0.945

In [37]:
%%time
# Fairness Through Unwareness

x_train_unawareness = x_train.copy()
x_train_unawareness
x_train_unawareness.drop('catAge_<=30', inplace=True, axis=1)
x_train_unawareness.drop('catAge_30-40', inplace=True, axis=1)
x_train_unawareness.drop('catAge_40-50', inplace=True, axis=1)
x_train_unawareness.drop('catAge_>=50', inplace=True, axis=1)

# x_train_unawareness.columns.values
# x_train.columns.values






CPU times: user 22.5 ms, sys: 8.95 ms, total: 31.5 ms
Wall time: 29.2 ms


In [38]:
%%time
#Fairness through unawareness

x_test_unawareness = x_test.copy()
x_test_unawareness
x_test_l30 = x_test_unawareness[x_test_unawareness['catAge_<=30'] == 1]
x_test_30to40 = x_test_unawareness[x_test_unawareness['catAge_30-40'] == 1]
x_test_40to50 = x_test_unawareness[x_test_unawareness['catAge_40-50'] == 1]
x_test_g50 = x_test_unawareness[x_test_unawareness['catAge_>=50'] == 1]


x_test_l30.drop('catAge_<=30', inplace=True, axis=1)
x_test_l30.drop('catAge_30-40', inplace=True, axis=1)
x_test_l30.drop('catAge_40-50', inplace=True, axis=1)
x_test_l30.drop('catAge_>=50', inplace=True, axis=1)

x_test_30to40.drop('catAge_<=30', inplace=True, axis=1)
x_test_30to40.drop('catAge_30-40', inplace=True, axis=1)
x_test_30to40.drop('catAge_40-50', inplace=True, axis=1)
x_test_30to40.drop('catAge_>=50', inplace=True, axis=1)

x_test_40to50.drop('catAge_<=30', inplace=True, axis=1)
x_test_40to50.drop('catAge_30-40', inplace=True, axis=1)
x_test_40to50.drop('catAge_40-50', inplace=True, axis=1)
x_test_40to50.drop('catAge_>=50', inplace=True, axis=1)

x_test_g50.drop('catAge_<=30', inplace=True, axis=1)
x_test_g50.drop('catAge_30-40', inplace=True, axis=1)
x_test_g50.drop('catAge_40-50', inplace=True, axis=1)
x_test_g50.drop('catAge_>=50', inplace=True, axis=1)




# x_test_unawareness.columns.values
# x_test.columns.values
# test_married

CPU times: user 39.1 ms, sys: 4.61 ms, total: 43.8 ms
Wall time: 43.4 ms


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/core/frame.py:4163: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


In [39]:
%%time
# Test on l30 set

gnb_pred_l30 = gnb.fit(x_train_unawareness, y_train).predict(x_test_l30)

test_df = x_test_l30.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(gnb_pred_l30, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_l30 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_l30



CPU times: user 96.8 ms, sys: 15.9 ms, total: 113 ms
Wall time: 119 ms


array([[1117,   61],
       [ 172,   14]])

In [40]:
%%time
accuracy_naive_bayes_l30 = (confusion_matrix_l30[0][0] + confusion_matrix_l30[1][1]) / (confusion_matrix_l30[0][0] + confusion_matrix_l30[0][1] + confusion_matrix_l30[1][0] + confusion_matrix_l30[1][1])
accuracy_naive_bayes_l30 

CPU times: user 140 µs, sys: 12 µs, total: 152 µs
Wall time: 210 µs


0.8291788856304986

In [41]:
%%time
# Test on 30to40 set

gnb_pred_30to40 = gnb.fit(x_train_unawareness, y_train).predict(x_test_30to40)

test_df = x_test_30to40.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(gnb_pred_30to40, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_30to40 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_30to40



CPU times: user 140 ms, sys: 18.2 ms, total: 158 ms
Wall time: 282 ms


array([[2987,  130],
       [ 406,   18]])

In [42]:
%%time
accuracy_naive_bayes_30to40 = (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[1][1]) / (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[0][1] + confusion_matrix_30to40[1][0] + confusion_matrix_30to40[1][1])
accuracy_naive_bayes_30to40 

CPU times: user 56 µs, sys: 2 µs, total: 58 µs
Wall time: 63.9 µs


0.8486303304151369

In [43]:
%%time
# Test on 40to50 set

gnb_pred_40to50 = gnb.fit(x_train_unawareness, y_train).predict(x_test_40to50)

test_df = x_test_40to50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(gnb_pred_40to50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_40to50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_40to50

CPU times: user 110 ms, sys: 11.3 ms, total: 122 ms
Wall time: 177 ms


array([[1957,   69],
       [ 264,   14]])

In [44]:
%%time
accuracy_naive_bayes_40to50 = (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[1][1]) / (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[0][1] + confusion_matrix_40to50[1][0] + confusion_matrix_40to50[1][1])
accuracy_naive_bayes_40to50 # 0.8718606782768102

CPU times: user 128 µs, sys: 86 µs, total: 214 µs
Wall time: 135 µs


0.85546875

In [45]:
%%time
# Test on g50 set

gnb_pred_g50 = gnb.fit(x_train_unawareness, y_train).predict(x_test_g50)

test_df = x_test_g50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(gnb_pred_g50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_g50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_g50

CPU times: user 112 ms, sys: 14.2 ms, total: 126 ms
Wall time: 152 ms


array([[1511,   89],
       [ 190,   10]])

In [46]:
%%time
accuracy_naive_bayes_g50 = (confusion_matrix_g50[0][0] + confusion_matrix_g50[1][1]) / (confusion_matrix_g50[0][0] + confusion_matrix_g50[0][1] + confusion_matrix_g50[1][0] + confusion_matrix_g50[1][1])
accuracy_naive_bayes_g50 # 0.8718606782768102

CPU times: user 97 µs, sys: 44 µs, total: 141 µs
Wall time: 146 µs


0.845

Random Forest Model

In [47]:
%%time
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(max_depth=5, random_state=0, class_weight='balanced')
rf_pred = rf.fit(x_train, y_train).predict(x_test)

CPU times: user 4.58 s, sys: 163 ms, total: 4.74 s
Wall time: 11.7 s


In [48]:
%%time
test_df = x_test.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(rf_pred, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])
test_df.columns.values

CPU times: user 7.89 ms, sys: 1.54 ms, total: 9.44 ms
Wall time: 13.6 ms


array(['balance', 'day', 'duration', 'campaign', 'pdays', 'previous',
       'biDefault', 'biHousing', 'biLoan', 'catAge_30-40', 'catAge_40-50',
       'catAge_<=30', 'catAge_>=50', 'job_admin.', 'job_blue-collar',
       'job_entrepreneur', 'job_housemaid', 'job_management',
       'job_retired', 'job_self-employed', 'job_services', 'job_student',
       'job_technician', 'job_unemployed', 'marital_divorced',
       'marital_married', 'marital_single', 'education_primary',
       'education_secondary', 'education_tertiary', 'month_apr',
       'month_aug', 'month_dec', 'month_feb', 'month_jan', 'month_jul',
       'month_jun', 'month_mar', 'month_may', 'month_nov', 'month_oct',
       'month_sep', 'Fmonth_apr', 'Fmonth_aug', 'Fmonth_dec',
       'Fmonth_feb', 'Fmonth_jan', 'Fmonth_jul', 'Fmonth_jun',
       'Fmonth_mar', 'Fmonth_may', 'Fmonth_nov', 'Fmonth_oct', 'biY',
       'pred', 'accurate'], dtype=object)

In [49]:
%%time
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix

CPU times: user 27.1 ms, sys: 4.07 ms, total: 31.2 ms
Wall time: 46.8 ms


array([[5016, 2905],
       [ 674,  414]])

In [50]:
%%time
# Accuracy
# "Accuracy: ", test_df.accurate.mean()

accuracy_rf = (confusion_matrix[0][0] + confusion_matrix[1][1]) / (confusion_matrix[0][0] + confusion_matrix[0][1] + confusion_matrix[1][0] + confusion_matrix[1][1])
accuracy_rf


CPU times: user 77 µs, sys: 1e+03 ns, total: 78 µs
Wall time: 85.8 µs


0.6027306027306027

In [51]:
%%time
# Split dataset based on marital status

test_df.columns.values
test_l30 = x_test[x_test['catAge_<=30'] == 1]
test_30to40 = x_test[x_test['catAge_30-40'] == 1]
test_40to50 = x_test[x_test['catAge_40-50'] == 1]
test_g50 = x_test[x_test['catAge_>=50'] == 1]

CPU times: user 12.2 ms, sys: 3.44 ms, total: 15.7 ms
Wall time: 19.1 ms


In [52]:
%%time
# Test on single subset

rf_pred_l30 = rf.fit(x_train, y_train).predict(test_l30)

test_df = test_l30.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(rf_pred_l30, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_l30 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_l30

CPU times: user 3.68 s, sys: 76.7 ms, total: 3.76 s
Wall time: 5.16 s


array([[761, 417],
       [119,  67]])

In [53]:
%%time
accuracy_rf_l30 = (confusion_matrix_l30[0][0] + confusion_matrix_l30[1][1]) / (confusion_matrix_l30[0][0] + confusion_matrix_l30[0][1] + confusion_matrix_l30[1][0] + confusion_matrix_l30[1][1])
accuracy_rf_l30

CPU times: user 77 µs, sys: 1 µs, total: 78 µs
Wall time: 83.9 µs


0.6070381231671554

In [54]:
%%time
# Test on 30to40 subset

rf_pred_30to40 = rf.fit(x_train, y_train).predict(test_30to40)

test_df = test_30to40.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(rf_pred_30to40, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_30to40 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_30to40

CPU times: user 6.61 s, sys: 245 ms, total: 6.86 s
Wall time: 13.1 s


array([[1892, 1225],
       [ 247,  177]])

In [55]:
%%time
accuracy_rf_30to40 = (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[1][1]) / (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[0][1] + confusion_matrix_30to40[1][0] + confusion_matrix_30to40[1][1])
accuracy_rf_30to40

CPU times: user 125 µs, sys: 2 µs, total: 127 µs
Wall time: 142 µs


0.5842982208415701

In [56]:
%%time
# Test on 40to50 subset

rf_pred_40to50 = rf.fit(x_train, y_train).predict(test_40to50)
 
test_df = test_40to50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(rf_pred_40to50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])
 
from sklearn.metrics import confusion_matrix
 
confusion_matrix_40to50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_40to50


CPU times: user 4.46 s, sys: 88.2 ms, total: 4.55 s
Wall time: 8.48 s


array([[1451,  575],
       [ 191,   87]])

In [57]:
%%time
accuracy_rf_40to50 = (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[1][1]) / (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[0][1] + confusion_matrix_40to50[1][0] + confusion_matrix_40to50[1][1])
accuracy_rf_40to50 

CPU times: user 60 µs, sys: 1 µs, total: 61 µs
Wall time: 68.9 µs


0.6675347222222222

In [58]:
%%time
# Test on g50 subset

rf_pred_g50 = rf.fit(x_train, y_train).predict(test_g50)
 
test_df = test_g50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(rf_pred_g50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])
 
from sklearn.metrics import confusion_matrix
 
confusion_matrix_g50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_g50

CPU times: user 4.01 s, sys: 82.7 ms, total: 4.09 s
Wall time: 5.26 s


array([[912, 688],
       [117,  83]])

In [59]:
%%time
accuracy_rf_g50 = (confusion_matrix_g50[0][0] + confusion_matrix_g50[1][1]) / (confusion_matrix_g50[0][0] + confusion_matrix_g50[0][1] + confusion_matrix_g50[1][0] + confusion_matrix_g50[1][1])
accuracy_rf_g50 

CPU times: user 44 µs, sys: 1 µs, total: 45 µs
Wall time: 50.1 µs


0.5527777777777778

In [60]:
%%time
#Demographic Parity
# positive rate = (TP + FP)/total

PR_rf_l30 = (confusion_matrix_l30[1,1] +confusion_matrix_l30[0,1])/(confusion_matrix_l30[0][0] + confusion_matrix_l30[0][1] + confusion_matrix_l30[1][0] + confusion_matrix_l30[1][1])
PR_rf_l30 # 4756

CPU times: user 43 µs, sys: 0 ns, total: 43 µs
Wall time: 49.1 µs


0.3548387096774194

In [61]:
%%time
PR_rf_30to40 = (confusion_matrix_30to40[1,1] +confusion_matrix_30to40[0,1])/(confusion_matrix_30to40[0][0] + confusion_matrix_30to40[0][1] + confusion_matrix_30to40[1][0] + confusion_matrix_30to40[1][1])
PR_rf_30to40 # 2136

CPU times: user 44 µs, sys: 0 ns, total: 44 µs
Wall time: 48.9 µs


0.39593335216040665

In [62]:
%%time
PR_rf_40to50 = (confusion_matrix_40to50[1,1] +confusion_matrix_40to50[0,1])/(confusion_matrix_40to50[0][0] + confusion_matrix_40to50[0][1] + confusion_matrix_40to50[1][0] + confusion_matrix_40to50[1][1])
PR_rf_40to50 # 2136

CPU times: user 69 µs, sys: 1 µs, total: 70 µs
Wall time: 78.2 µs


0.2873263888888889

In [63]:
%%time
PR_rf_g50 = (confusion_matrix_g50[1,1] +confusion_matrix_g50[0,1])/(confusion_matrix_g50[0][0] + confusion_matrix_g50[0][1] + confusion_matrix_g50[1][0] + confusion_matrix_g50[1][1])
PR_rf_g50 # 2136

CPU times: user 365 µs, sys: 91 µs, total: 456 µs
Wall time: 835 µs


0.42833333333333334

In [64]:
%%time
# Equalized Opportunity
#TPR = TP/TP+FN

TPR_rf_l30 = confusion_matrix_l30[1,1] / (confusion_matrix_l30[1,1] + confusion_matrix_l30[1,0])

TPR_rf_l30

CPU times: user 54 µs, sys: 1 µs, total: 55 µs
Wall time: 64.1 µs


0.3602150537634409

In [65]:
%%time
TPR_rf_30to40 = confusion_matrix_30to40[1,1] / (confusion_matrix_30to40[1,1] + confusion_matrix_30to40[1,0])

TPR_rf_30to40  

CPU times: user 68 µs, sys: 1 µs, total: 69 µs
Wall time: 78.9 µs


0.41745283018867924

In [66]:
%%time
TPR_rf_40to50  = confusion_matrix_40to50[1,1] / (confusion_matrix_40to50[1,1] + confusion_matrix_40to50[1,0])

TPR_rf_40to50 

CPU times: user 58 µs, sys: 1 µs, total: 59 µs
Wall time: 69.1 µs


0.3129496402877698

In [67]:
%%time
TPR_rf_g50  = confusion_matrix_g50[1,1] / (confusion_matrix_g50[1,1] + confusion_matrix_g50[1,0])

TPR_rf_g50 

CPU times: user 66 µs, sys: 2 µs, total: 68 µs
Wall time: 77 µs


0.415

In [68]:
%%time
# Equalized Odds
#TPR = TP/TP+FN
#FNR = FN/FN+TP


FNR_rf_l30 = confusion_matrix_l30[1,0] / (confusion_matrix_l30[1,0] + confusion_matrix_l30[1,1])

FNR_rf_l30 # 0.11652109273369263


CPU times: user 57 µs, sys: 1e+03 ns, total: 58 µs
Wall time: 66 µs


0.6397849462365591

In [69]:
%%time
FNR_rf_30to40 = confusion_matrix_30to40[1,0] / (confusion_matrix_30to40[1,0] + confusion_matrix_30to40[1,1])

FNR_rf_30to40

CPU times: user 65 µs, sys: 1 µs, total: 66 µs
Wall time: 82 µs


0.5825471698113207

In [70]:
%%time
FNR_rf_40to50 = confusion_matrix_40to50[1,0] / (confusion_matrix_40to50[1,0] + confusion_matrix_40to50[1,1])

FNR_rf_40to50

CPU times: user 55 µs, sys: 2 µs, total: 57 µs
Wall time: 65.1 µs


0.6870503597122302

In [71]:
%%time
FNR_rf_g50 = confusion_matrix_g50[1,0] / (confusion_matrix_g50[1,0] + confusion_matrix_g50[1,1])

FNR_rf_g50

CPU times: user 91 µs, sys: 1 µs, total: 92 µs
Wall time: 102 µs


0.585

In [72]:
%%time
# Fairness Through Unwareness

x_train_unawareness = x_train.copy()
x_train_unawareness
x_train_unawareness.drop('catAge_<=30', inplace=True, axis=1)
x_train_unawareness.drop('catAge_30-40', inplace=True, axis=1)
x_train_unawareness.drop('catAge_40-50', inplace=True, axis=1)
x_train_unawareness.drop('catAge_>=50', inplace=True, axis=1)

# x_train_unawareness.columns.values
# x_train.columns.values

CPU times: user 52.3 ms, sys: 44 ms, total: 96.3 ms
Wall time: 114 ms


In [73]:
%%time
#Fairness through unawareness

x_test_unawareness = x_test.copy()
x_test_unawareness
x_test_l30 = x_test_unawareness[x_test_unawareness['catAge_<=30'] == 1]
x_test_30to40 = x_test_unawareness[x_test_unawareness['catAge_30-40'] == 1]
x_test_40to50 = x_test_unawareness[x_test_unawareness['catAge_40-50'] == 1]
x_test_g50 = x_test_unawareness[x_test_unawareness['catAge_>=50'] == 1]


x_test_l30.drop('catAge_<=30', inplace=True, axis=1)
x_test_l30.drop('catAge_30-40', inplace=True, axis=1)
x_test_l30.drop('catAge_40-50', inplace=True, axis=1)
x_test_l30.drop('catAge_>=50', inplace=True, axis=1)

x_test_30to40.drop('catAge_<=30', inplace=True, axis=1)
x_test_30to40.drop('catAge_30-40', inplace=True, axis=1)
x_test_30to40.drop('catAge_40-50', inplace=True, axis=1)
x_test_30to40.drop('catAge_>=50', inplace=True, axis=1)

x_test_40to50.drop('catAge_<=30', inplace=True, axis=1)
x_test_40to50.drop('catAge_30-40', inplace=True, axis=1)
x_test_40to50.drop('catAge_40-50', inplace=True, axis=1)
x_test_40to50.drop('catAge_>=50', inplace=True, axis=1)

x_test_g50.drop('catAge_<=30', inplace=True, axis=1)
x_test_g50.drop('catAge_30-40', inplace=True, axis=1)
x_test_g50.drop('catAge_40-50', inplace=True, axis=1)
x_test_g50.drop('catAge_>=50', inplace=True, axis=1)



# x_test_unawareness.columns.values
# x_test.columns.values

CPU times: user 44.5 ms, sys: 7.98 ms, total: 52.4 ms
Wall time: 58.6 ms


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/core/frame.py:4163: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


In [74]:
%%time
# Test on l30 set

rf_pred_l30 = rf.fit(x_train_unawareness, y_train).predict(x_test_l30)

test_df = x_test_l30.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(rf_pred_l30, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_l30 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_l30


CPU times: user 3.42 s, sys: 57.8 ms, total: 3.47 s
Wall time: 4.84 s


array([[868, 310],
       [126,  60]])

In [75]:
%%time
accuracy_rf_l30 = (confusion_matrix_l30[0][0] + confusion_matrix_l30[1][1]) / (confusion_matrix_l30[0][0] + confusion_matrix_l30[0][1] + confusion_matrix_l30[1][0] + confusion_matrix_l30[1][1])
accuracy_rf_l30

CPU times: user 86 µs, sys: 2 µs, total: 88 µs
Wall time: 98 µs


0.6803519061583577

In [76]:
%%time
# Test on 30to40 set

rf_pred_30to40 = rf.fit(x_train_unawareness, y_train).predict(x_test_30to40)

test_df = x_test_30to40.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(rf_pred_30to40, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_30to40 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_30to40


CPU times: user 3.33 s, sys: 43.7 ms, total: 3.38 s
Wall time: 3.65 s


array([[2013, 1104],
       [ 280,  144]])

In [77]:
%%time
accuracy_rf_30to40 = (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[1][1]) / (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[0][1] + confusion_matrix_30to40[1][0] + confusion_matrix_30to40[1][1])
accuracy_rf_30to40 

CPU times: user 59 µs, sys: 1e+03 ns, total: 60 µs
Wall time: 67.9 µs


0.609149957639085

In [78]:
%%time
# Test on 40to50 set

rf_pred_40to50 = rf.fit(x_train_unawareness, y_train).predict(x_test_40to50)

test_df = x_test_40to50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(rf_pred_40to50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_40to50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_40to50

CPU times: user 3.24 s, sys: 41.3 ms, total: 3.28 s
Wall time: 3.36 s


array([[1296,  730],
       [ 178,  100]])

In [79]:
%%time
accuracy_rf_40to50 = (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[1][1]) / (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[0][1] + confusion_matrix_40to50[1][0] + confusion_matrix_40to50[1][1])
accuracy_rf_40to50 # 0.8718606782768102

CPU times: user 58 µs, sys: 1 µs, total: 59 µs
Wall time: 65.1 µs


0.6059027777777778

In [80]:
%%time
# Test on g50 set

rf_pred_g50 = rf.fit(x_train_unawareness, y_train).predict(x_test_g50)

test_df = x_test_g50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(rf_pred_g50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_g50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_g50

CPU times: user 3.31 s, sys: 42.9 ms, total: 3.35 s
Wall time: 3.47 s


array([[1047,  553],
       [ 128,   72]])

In [81]:
%%time
accuracy_rf_g50 = (confusion_matrix_g50[0][0] + confusion_matrix_g50[1][1]) / (confusion_matrix_g50[0][0] + confusion_matrix_g50[0][1] + confusion_matrix_g50[1][0] + confusion_matrix_g50[1][1])
accuracy_rf_g50 # 0.8718606782768102

CPU times: user 60 µs, sys: 0 ns, total: 60 µs
Wall time: 68.2 µs


0.6216666666666667

Support Vector Machine

In [82]:
%%time
from sklearn import svm as svm_model
svm = svm_model.SVC(class_weight='balanced') # add class_weight='balanced' is to avoid classifying all data as 0
svm_pred = svm.fit(x_train, y_train).predict(x_test)

CPU times: user 6min 14s, sys: 4.18 s, total: 6min 18s
Wall time: 7min 20s


In [83]:
%%time
test_df = x_test.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(svm_pred, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])
test_df.columns.values

CPU times: user 10.6 ms, sys: 5.01 ms, total: 15.7 ms
Wall time: 17.2 ms


array(['balance', 'day', 'duration', 'campaign', 'pdays', 'previous',
       'biDefault', 'biHousing', 'biLoan', 'catAge_30-40', 'catAge_40-50',
       'catAge_<=30', 'catAge_>=50', 'job_admin.', 'job_blue-collar',
       'job_entrepreneur', 'job_housemaid', 'job_management',
       'job_retired', 'job_self-employed', 'job_services', 'job_student',
       'job_technician', 'job_unemployed', 'marital_divorced',
       'marital_married', 'marital_single', 'education_primary',
       'education_secondary', 'education_tertiary', 'month_apr',
       'month_aug', 'month_dec', 'month_feb', 'month_jan', 'month_jul',
       'month_jun', 'month_mar', 'month_may', 'month_nov', 'month_oct',
       'month_sep', 'Fmonth_apr', 'Fmonth_aug', 'Fmonth_dec',
       'Fmonth_feb', 'Fmonth_jan', 'Fmonth_jul', 'Fmonth_jun',
       'Fmonth_mar', 'Fmonth_may', 'Fmonth_nov', 'Fmonth_oct', 'biY',
       'pred', 'accurate'], dtype=object)

In [84]:
%%time
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix

CPU times: user 33.8 ms, sys: 4.52 ms, total: 38.3 ms
Wall time: 80.3 ms


array([[6873, 1048],
       [ 928,  160]])

In [85]:
%%time
# Accuracy
# "Accuracy: ", test_df.accurate.mean()

accuracy_svm = (confusion_matrix[0][0] + confusion_matrix[1][1]) / (confusion_matrix[0][0] + confusion_matrix[0][1] + confusion_matrix[1][0] + confusion_matrix[1][1])
accuracy_svm


CPU times: user 62 µs, sys: 1 µs, total: 63 µs
Wall time: 69.9 µs


0.7806637806637806

In [86]:
%%time
# Split dataset based on marital status

test_df.columns.values
test_l30 = x_test[x_test['catAge_<=30'] == 1]
test_30to40 = x_test[x_test['catAge_30-40'] == 1]
test_40to50 = x_test[x_test['catAge_40-50'] == 1]
test_g50 = x_test[x_test['catAge_>=50'] == 1]

CPU times: user 9.01 ms, sys: 2.59 ms, total: 11.6 ms
Wall time: 17.3 ms


In [87]:
%%time
# Test on l30 subset

svm_pred_l30 = svm.fit(x_train, y_train).predict(test_l30)

test_df = test_l30.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(svm_pred_l30, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_l30 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_l30

CPU times: user 5min 52s, sys: 4.8 s, total: 5min 57s
Wall time: 7min 18s


array([[1045,  133],
       [ 168,   18]])

In [88]:
%%time
accuracy_svm_l30 = (confusion_matrix_l30[0][0] + confusion_matrix_l30[1][1]) / (confusion_matrix_l30[0][0] + confusion_matrix_l30[0][1] + confusion_matrix_l30[1][0] + confusion_matrix_l30[1][1])
accuracy_svm_l30

CPU times: user 60 µs, sys: 1e+03 ns, total: 61 µs
Wall time: 67.9 µs


0.7793255131964809

In [89]:
%%time
# Test on married subset

svm_pred_30to40 = svm.fit(x_train, y_train).predict(test_30to40)

test_df = test_30to40.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(svm_pred_30to40, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_30to40 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_30to40

CPU times: user 6min 27s, sys: 7.74 s, total: 6min 35s
Wall time: 9min 22s


array([[2674,  443],
       [ 354,   70]])

In [90]:
%%time
accuracy_svm_30to40 = (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[1][1]) / (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[0][1] + confusion_matrix_30to40[1][0] + confusion_matrix_30to40[1][1])
accuracy_svm_30to40 # 0.8718606782768102

CPU times: user 74 µs, sys: 15 µs, total: 89 µs
Wall time: 97 µs


0.7749223383225078

In [91]:
%%time
# Test on 40to50 subset

svm_pred_40to50 = svm.fit(x_train, y_train).predict(test_40to50)

test_df = test_40to50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(svm_pred_40to50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_40to50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_40to50

CPU times: user 5min 56s, sys: 4.37 s, total: 6min
Wall time: 7min 20s


array([[1765,  261],
       [ 243,   35]])

In [92]:
%%time
accuracy_svm_40to50 = (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[1][1]) / (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[0][1] + confusion_matrix_40to50[1][0] + confusion_matrix_40to50[1][1])
accuracy_svm_40to50 

CPU times: user 95 µs, sys: 1 µs, total: 96 µs
Wall time: 108 µs


0.78125

In [93]:
%%time
# Test on g50 subset

svm_pred_g50 = svm.fit(x_train, y_train).predict(test_g50)

test_df = test_g50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(svm_pred_g50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_g50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_g50

CPU times: user 4min 44s, sys: 2.16 s, total: 4min 46s
Wall time: 5min 10s


array([[1389,  211],
       [ 163,   37]])

In [94]:
%%time
accuracy_svm_g50 = (confusion_matrix_g50[0][0] + confusion_matrix_g50[1][1]) / (confusion_matrix_g50[0][0] + confusion_matrix_g50[0][1] + confusion_matrix_g50[1][0] + confusion_matrix_g50[1][1])
accuracy_svm_g50 # 0.8718606782768102

CPU times: user 45 µs, sys: 0 ns, total: 45 µs
Wall time: 51.3 µs


0.7922222222222223

In [95]:
%%time
#Demographic Parity
# positive rate = (TP + FP)/total

PR_svm_l30 = (confusion_matrix_l30[1,1] +confusion_matrix_l30[0,1])/(confusion_matrix_l30[0][0] + confusion_matrix_l30[0][1] + confusion_matrix_l30[1][0] + confusion_matrix_l30[1][1])

PR_svm_l30

CPU times: user 47 µs, sys: 1 µs, total: 48 µs
Wall time: 54.1 µs


0.11070381231671554

In [96]:
%%time
PR_svm_30to40 = (confusion_matrix_30to40[1,1] +confusion_matrix_30to40[0,1])/(confusion_matrix_30to40[0][0] + confusion_matrix_30to40[0][1] + confusion_matrix_30to40[1][0] + confusion_matrix_30to40[1][1])
PR_svm_30to40

CPU times: user 73 µs, sys: 1 µs, total: 74 µs
Wall time: 82 µs


0.14487432928551255

In [97]:
%%time
PR_svm_40to50 = (confusion_matrix_40to50[1,1] +confusion_matrix_40to50[0,1])/(confusion_matrix_40to50[0][0] + confusion_matrix_40to50[0][1] + confusion_matrix_40to50[1][0] + confusion_matrix_40to50[1][1])
PR_svm_40to50

CPU times: user 71 µs, sys: 2 µs, total: 73 µs
Wall time: 80.8 µs


0.1284722222222222

In [98]:
%%time
PR_svm_g50 = (confusion_matrix_g50[1,1] +confusion_matrix_g50[0,1])/(confusion_matrix_g50[0][0] + confusion_matrix_g50[0][1] + confusion_matrix_g50[1][0] + confusion_matrix_g50[1][1])
PR_svm_g50

CPU times: user 63 µs, sys: 1 µs, total: 64 µs
Wall time: 70.1 µs


0.13777777777777778

In [99]:
%%time
# Equalized Opportunity
#TPR = TP/TP+FN

TPR_svm_l30 = confusion_matrix_l30[1,1] / (confusion_matrix_l30[1,1] + confusion_matrix_l30[1,0])

TPR_svm_l30

CPU times: user 41 µs, sys: 1 µs, total: 42 µs
Wall time: 47.9 µs


0.0967741935483871

In [100]:
%%time
TPR_svm_30to40 = confusion_matrix_30to40[1,1] / (confusion_matrix_30to40[1,1] + confusion_matrix_30to40[1,0])

TPR_svm_30to40 

CPU times: user 44 µs, sys: 0 ns, total: 44 µs
Wall time: 50.1 µs


0.1650943396226415

In [101]:
%%time
TPR_svm_40to50 = confusion_matrix_40to50[1,1] / (confusion_matrix_40to50[1,1] + confusion_matrix_40to50[1,0])

TPR_svm_40to50 

CPU times: user 61 µs, sys: 1 µs, total: 62 µs
Wall time: 68.9 µs


0.12589928057553956

In [102]:
%%time
TPR_svm_g50 = confusion_matrix_g50[1,1] / (confusion_matrix_g50[1,1] + confusion_matrix_g50[1,0])

TPR_svm_g50 

CPU times: user 59 µs, sys: 2 µs, total: 61 µs
Wall time: 69.1 µs


0.185

In [103]:
%%time
# Equalized Odds
#TPR = TP/TP+FN
#FNR = FN/FN+TP


FNR_svm_l30 = confusion_matrix_l30[1,0] / (confusion_matrix_l30[1,0] + confusion_matrix_l30[1,1])

FNR_svm_l30

CPU times: user 38 µs, sys: 1 µs, total: 39 µs
Wall time: 45.1 µs


0.9032258064516129

In [104]:
%%time
FNR_svm_30to40 = confusion_matrix_30to40[1,0] / (confusion_matrix_30to40[1,0] + confusion_matrix_30to40[1,1])

FNR_svm_30to40 

CPU times: user 63 µs, sys: 1 µs, total: 64 µs
Wall time: 73.2 µs


0.8349056603773585

In [105]:
%%time
FNR_svm_40to50 = confusion_matrix_40to50[1,0] / (confusion_matrix_40to50[1,0] + confusion_matrix_40to50[1,1])

FNR_svm_40to50 

CPU times: user 38 µs, sys: 0 ns, total: 38 µs
Wall time: 44.1 µs


0.8741007194244604

In [106]:
%%time
FNR_svm_g50 = confusion_matrix_g50[1,0] / (confusion_matrix_g50[1,0] + confusion_matrix_g50[1,1])

FNR_svm_g50 

CPU times: user 36 µs, sys: 1e+03 ns, total: 37 µs
Wall time: 42 µs


0.815

In [107]:
%%time
# Fairness Through Unwareness

x_train_unawareness = x_train.copy()
x_train_unawareness
x_train_unawareness.drop('catAge_<=30', inplace=True, axis=1)
x_train_unawareness.drop('catAge_30-40', inplace=True, axis=1)
x_train_unawareness.drop('catAge_40-50', inplace=True, axis=1)
x_train_unawareness.drop('catAge_>=50', inplace=True, axis=1)


# x_train_unawareness.columns.values
# x_train.columns.values

CPU times: user 23.6 ms, sys: 14.4 ms, total: 38 ms
Wall time: 36.1 ms


In [108]:
%%time
#Fairness through unawareness


x_test_unawareness = x_test.copy()
x_test_unawareness
x_test_l30 = x_test_unawareness[x_test_unawareness['catAge_<=30'] == 1]
x_test_30to40 = x_test_unawareness[x_test_unawareness['catAge_30-40'] == 1]
x_test_40to50 = x_test_unawareness[x_test_unawareness['catAge_40-50'] == 1]
x_test_g50 = x_test_unawareness[x_test_unawareness['catAge_>=50'] == 1]


x_test_l30.drop('catAge_<=30', inplace=True, axis=1)
x_test_l30.drop('catAge_30-40', inplace=True, axis=1)
x_test_l30.drop('catAge_40-50', inplace=True, axis=1)
x_test_l30.drop('catAge_>=50', inplace=True, axis=1)

x_test_30to40.drop('catAge_<=30', inplace=True, axis=1)
x_test_30to40.drop('catAge_30-40', inplace=True, axis=1)
x_test_30to40.drop('catAge_40-50', inplace=True, axis=1)
x_test_30to40.drop('catAge_>=50', inplace=True, axis=1)

x_test_40to50.drop('catAge_<=30', inplace=True, axis=1)
x_test_40to50.drop('catAge_30-40', inplace=True, axis=1)
x_test_40to50.drop('catAge_40-50', inplace=True, axis=1)
x_test_40to50.drop('catAge_>=50', inplace=True, axis=1)

x_test_g50.drop('catAge_<=30', inplace=True, axis=1)
x_test_g50.drop('catAge_30-40', inplace=True, axis=1)
x_test_g50.drop('catAge_40-50', inplace=True, axis=1)
x_test_g50.drop('catAge_>=50', inplace=True, axis=1)



CPU times: user 32.4 ms, sys: 12.7 ms, total: 45.1 ms
Wall time: 44.1 ms


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/core/frame.py:4163: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


In [109]:
%%time
# Test on l30 set

svm_pred_l30 = svm.fit(x_train_unawareness, y_train).predict(x_test_l30)

test_df = x_test_l30.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(svm_pred_l30, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_l30 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_l30


CPU times: user 4min 15s, sys: 1.67 s, total: 4min 17s
Wall time: 4min 32s


array([[1045,  133],
       [ 168,   18]])

In [110]:
%%time
accuracy_svm_l30 = (confusion_matrix_l30[0][0] + confusion_matrix_l30[1][1]) / (confusion_matrix_l30[0][0] + confusion_matrix_l30[0][1] + confusion_matrix_l30[1][0] + confusion_matrix_l30[1][1])
accuracy_svm_l30

CPU times: user 52 µs, sys: 1e+03 ns, total: 53 µs
Wall time: 58.9 µs


0.7793255131964809

In [111]:
%%time
# Test on 30to40 set

svm_pred_30to40 = svm.fit(x_train_unawareness, y_train).predict(x_test_30to40)

test_df = x_test_30to40.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(svm_pred_30to40, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_30to40 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_30to40

CPU times: user 4min 56s, sys: 3.44 s, total: 4min 59s
Wall time: 5min 51s


array([[2674,  443],
       [ 354,   70]])

In [112]:
%%time
accuracy_svm_30to40 = (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[1][1]) / (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[0][1] + confusion_matrix_30to40[1][0] + confusion_matrix_30to40[1][1])
accuracy_svm_30to40 # 0.8718606782768102

CPU times: user 52 µs, sys: 0 ns, total: 52 µs
Wall time: 61.3 µs


0.7749223383225078

In [113]:
%%time
# Test on 40to50 subset

svm_pred_40to50 = svm.fit(x_train_unawareness, y_train).predict(x_test_40to50)

test_df = x_test_40to50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(svm_pred_40to50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_40to50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_40to50

CPU times: user 3min 54s, sys: 2.25 s, total: 3min 56s
Wall time: 4min 25s


array([[1766,  260],
       [ 243,   35]])

In [114]:
%%time
accuracy_svm_40to50 = (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[1][1]) / (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[0][1] + confusion_matrix_40to50[1][0] + confusion_matrix_40to50[1][1])
accuracy_svm_40to50 

CPU times: user 61 µs, sys: 1 µs, total: 62 µs
Wall time: 69.1 µs


0.7816840277777778

In [115]:
%%time
# Test on g50 subset

svm_pred_g50 = svm.fit(x_train_unawareness, y_train).predict(x_test_g50)

test_df = x_test_g50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(svm_pred_g50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_g50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_g50

CPU times: user 3min 50s, sys: 2.75 s, total: 3min 53s
Wall time: 4min 26s


array([[1388,  212],
       [ 163,   37]])

In [116]:
%%time
accuracy_svm_g50 = (confusion_matrix_g50[0][0] + confusion_matrix_g50[1][1]) / (confusion_matrix_g50[0][0] + confusion_matrix_g50[0][1] + confusion_matrix_g50[1][0] + confusion_matrix_g50[1][1])
accuracy_svm_g50 

CPU times: user 59 µs, sys: 1e+03 ns, total: 60 µs
Wall time: 68.2 µs


0.7916666666666666

Logistic Regression Model

In [117]:
%%time
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(random_state=0, class_weight='balanced')
clf_pred = clf.fit(x_train, y_train).predict(x_test)

CPU times: user 962 ms, sys: 126 ms, total: 1.09 s
Wall time: 681 ms


In [118]:
%%time
test_df = x_test.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(clf_pred, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])
test_df.columns.values

CPU times: user 11.4 ms, sys: 4.41 ms, total: 15.8 ms
Wall time: 10.8 ms


array(['balance', 'day', 'duration', 'campaign', 'pdays', 'previous',
       'biDefault', 'biHousing', 'biLoan', 'catAge_30-40', 'catAge_40-50',
       'catAge_<=30', 'catAge_>=50', 'job_admin.', 'job_blue-collar',
       'job_entrepreneur', 'job_housemaid', 'job_management',
       'job_retired', 'job_self-employed', 'job_services', 'job_student',
       'job_technician', 'job_unemployed', 'marital_divorced',
       'marital_married', 'marital_single', 'education_primary',
       'education_secondary', 'education_tertiary', 'month_apr',
       'month_aug', 'month_dec', 'month_feb', 'month_jan', 'month_jul',
       'month_jun', 'month_mar', 'month_may', 'month_nov', 'month_oct',
       'month_sep', 'Fmonth_apr', 'Fmonth_aug', 'Fmonth_dec',
       'Fmonth_feb', 'Fmonth_jan', 'Fmonth_jul', 'Fmonth_jun',
       'Fmonth_mar', 'Fmonth_may', 'Fmonth_nov', 'Fmonth_oct', 'biY',
       'pred', 'accurate'], dtype=object)

In [119]:
%%time
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix

CPU times: user 22.6 ms, sys: 1.44 ms, total: 24.1 ms
Wall time: 43 ms


array([[5176, 2745],
       [ 709,  379]])

In [120]:
%%time
# Accuracy
# "Accuracy: ", test_df.accurate.mean()

accuracy_clf = (confusion_matrix[0][0] + confusion_matrix[1][1]) / (confusion_matrix[0][0] + confusion_matrix[0][1] + confusion_matrix[1][0] + confusion_matrix[1][1])
accuracy_clf

CPU times: user 65 µs, sys: 2 µs, total: 67 µs
Wall time: 73.9 µs


0.6166056166056166

In [121]:
%%time
# Split dataset based on marital status

test_df.columns.values
test_l30 = x_test[x_test['catAge_<=30'] == 1]
test_30to40 = x_test[x_test['catAge_30-40'] == 1]
test_40to50 = x_test[x_test['catAge_40-50'] == 1]
test_g50 = x_test[x_test['catAge_>=50'] == 1]

CPU times: user 17.3 ms, sys: 4.06 ms, total: 21.3 ms
Wall time: 162 ms


In [122]:
%%time
# Test on l30 subset

clf_pred_l30 = clf.fit(x_train, y_train).predict(test_l30)

test_df = test_l30.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(clf_pred_l30, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_l30 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_l30

CPU times: user 1.64 s, sys: 132 ms, total: 1.77 s
Wall time: 1.53 s


array([[804, 374],
       [120,  66]])

In [123]:
%%time
accuracy_clf_l30 = (confusion_matrix_l30[0][0] + confusion_matrix_l30[1][1]) / (confusion_matrix_l30[0][0] + confusion_matrix_l30[0][1] + confusion_matrix_l30[1][0] + confusion_matrix_l30[1][1])
accuracy_clf_l30

CPU times: user 2.41 ms, sys: 1.55 ms, total: 3.96 ms
Wall time: 2.97 ms


0.6378299120234604

In [124]:
%%time
# Test on 30to40 subset

clf_pred_30to40 = clf.fit(x_train, y_train).predict(test_30to40)

test_df = test_30to40.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(clf_pred_30to40, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_30to40 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_30to40

CPU times: user 934 ms, sys: 63.2 ms, total: 997 ms
Wall time: 616 ms


array([[1963, 1154],
       [ 268,  156]])

In [125]:
%%time
accuracy_clf_30to40 = (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[1][1]) / (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[0][1] + confusion_matrix_30to40[1][0] + confusion_matrix_30to40[1][1])
accuracy_clf_30to40

CPU times: user 118 µs, sys: 11 µs, total: 129 µs
Wall time: 72 µs


0.5984185258401582

In [126]:
%%time
# Test on 40to50 subset

clf_pred_40to50 = clf.fit(x_train, y_train).predict(test_40to50)
 
test_df = test_40to50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(clf_pred_40to50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])
 
from sklearn.metrics import confusion_matrix
 
confusion_matrix_40to50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_40to50

CPU times: user 990 ms, sys: 75.4 ms, total: 1.07 s
Wall time: 626 ms


array([[1356,  670],
       [ 186,   92]])

In [127]:
%%time
accuracy_clf_40to50 = (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[1][1]) / (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[0][1] + confusion_matrix_40to50[1][0] + confusion_matrix_40to50[1][1])
accuracy_clf_40to50 

CPU times: user 113 µs, sys: 8 µs, total: 121 µs
Wall time: 67 µs


0.6284722222222222

In [128]:
%%time
# Test on g50 subset

clf_pred_g50 = clf.fit(x_train, y_train).predict(test_g50)
 
test_df = test_g50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(clf_pred_g50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])
 
from sklearn.metrics import confusion_matrix
 
confusion_matrix_g50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_g50

CPU times: user 1.06 s, sys: 109 ms, total: 1.17 s
Wall time: 898 ms


array([[1053,  547],
       [ 135,   65]])

In [129]:
%%time
accuracy_clf_g50 = (confusion_matrix_g50[0][0] + confusion_matrix_g50[1][1]) / (confusion_matrix_g50[0][0] + confusion_matrix_g50[0][1] + confusion_matrix_g50[1][0] + confusion_matrix_g50[1][1])
accuracy_clf_g50 

CPU times: user 131 µs, sys: 21 µs, total: 152 µs
Wall time: 88.2 µs


0.6211111111111111

In [130]:
%%time
#Demographic Parity
# positive rate = (TP + FP)/total

PR_clf_l30 = (confusion_matrix_l30[1,1] +confusion_matrix_l30[0,1])/(confusion_matrix_l30[0][0] + confusion_matrix_l30[0][1] + confusion_matrix_l30[1][0] + confusion_matrix_l30[1][1])
PR_clf_l30 # 4756

CPU times: user 154 µs, sys: 14 µs, total: 168 µs
Wall time: 93.9 µs


0.3225806451612903

In [131]:
%%time
PR_clf_30to40 = (confusion_matrix_30to40[1,1] +confusion_matrix_30to40[0,1])/(confusion_matrix_30to40[0][0] + confusion_matrix_30to40[0][1] + confusion_matrix_30to40[1][0] + confusion_matrix_30to40[1][1])
PR_clf_30to40 # 2136

CPU times: user 42 µs, sys: 0 ns, total: 42 µs
Wall time: 50.1 µs


0.3699519909630048

In [132]:
%%time
PR_clf_40to50 = (confusion_matrix_40to50[1,1] +confusion_matrix_40to50[0,1])/(confusion_matrix_40to50[0][0] + confusion_matrix_40to50[0][1] + confusion_matrix_40to50[1][0] + confusion_matrix_40to50[1][1])
PR_clf_40to50 # 2136

CPU times: user 60 µs, sys: 1 µs, total: 61 µs
Wall time: 69.1 µs


0.3307291666666667

In [133]:
%%time
PR_clf_g50 = (confusion_matrix_g50[1,1] +confusion_matrix_g50[0,1])/(confusion_matrix_g50[0][0] + confusion_matrix_g50[0][1] + confusion_matrix_g50[1][0] + confusion_matrix_g50[1][1])
PR_clf_g50 # 2136

CPU times: user 43 µs, sys: 1e+03 ns, total: 44 µs
Wall time: 47.9 µs


0.34

In [134]:
%%time
# Equalized Opportunity
#TPR = TP/TP+FN

TPR_clf_l30 = confusion_matrix_l30[1,1] / (confusion_matrix_l30[1,1] + confusion_matrix_l30[1,0])

TPR_clf_l30

CPU times: user 423 µs, sys: 1.13 ms, total: 1.55 ms
Wall time: 2.75 ms


0.3548387096774194

In [135]:
%%time
TPR_clf_30to40 = confusion_matrix_30to40[1,1] / (confusion_matrix_30to40[1,1] + confusion_matrix_30to40[1,0])

TPR_clf_30to40  

CPU times: user 33 µs, sys: 1e+03 ns, total: 34 µs
Wall time: 39.8 µs


0.36792452830188677

In [136]:
%%time
TPR_clf_40to50  = confusion_matrix_40to50[1,1] / (confusion_matrix_40to50[1,1] + confusion_matrix_40to50[1,0])

TPR_clf_40to50 

CPU times: user 35 µs, sys: 1e+03 ns, total: 36 µs
Wall time: 41 µs


0.33093525179856115

In [137]:
%%time
TPR_clf_g50  = confusion_matrix_g50[1,1] / (confusion_matrix_g50[1,1] + confusion_matrix_g50[1,0])

TPR_clf_g50 

CPU times: user 51 µs, sys: 1e+03 ns, total: 52 µs
Wall time: 57.9 µs


0.325

In [138]:
%%time
# Equalized Odds
#TPR = TP/TP+FN
#FNR = FN/FN+TP


FNR_clf_l30 = confusion_matrix_l30[1,0] / (confusion_matrix_l30[1,0] + confusion_matrix_l30[1,1])

FNR_clf_l30 # 0.11652109273369263

CPU times: user 73 µs, sys: 1e+03 ns, total: 74 µs
Wall time: 82 µs


0.6451612903225806

In [139]:
%%time
FNR_clf_30to40 = confusion_matrix_30to40[1,0] / (confusion_matrix_30to40[1,0] + confusion_matrix_30to40[1,1])

FNR_clf_30to40

CPU times: user 333 µs, sys: 9 µs, total: 342 µs
Wall time: 407 µs


0.6320754716981132

In [140]:
%%time
FNR_clf_40to50 = confusion_matrix_40to50[1,0] / (confusion_matrix_40to50[1,0] + confusion_matrix_40to50[1,1])

FNR_clf_40to50

CPU times: user 113 µs, sys: 12 µs, total: 125 µs
Wall time: 143 µs


0.6690647482014388

In [141]:
%%time
FNR_clf_g50 = confusion_matrix_g50[1,0] / (confusion_matrix_g50[1,0] + confusion_matrix_g50[1,1])

FNR_clf_g50

CPU times: user 77 µs, sys: 2 µs, total: 79 µs
Wall time: 88.2 µs


0.675

In [142]:
%%time
# Fairness Through Unwareness

x_train_unawareness = x_train.copy()
x_train_unawareness
x_train_unawareness.drop('catAge_<=30', inplace=True, axis=1)
x_train_unawareness.drop('catAge_30-40', inplace=True, axis=1)
x_train_unawareness.drop('catAge_40-50', inplace=True, axis=1)
x_train_unawareness.drop('catAge_>=50', inplace=True, axis=1)

# x_train_unawareness.columns.values
# x_train.columns.values

CPU times: user 43 ms, sys: 18.7 ms, total: 61.7 ms
Wall time: 88.2 ms


In [143]:
%%time
#Fairness through unawareness

x_test_unawareness = x_test.copy()
x_test_unawareness
x_test_l30 = x_test_unawareness[x_test_unawareness['catAge_<=30'] == 1]
x_test_30to40 = x_test_unawareness[x_test_unawareness['catAge_30-40'] == 1]
x_test_40to50 = x_test_unawareness[x_test_unawareness['catAge_40-50'] == 1]
x_test_g50 = x_test_unawareness[x_test_unawareness['catAge_>=50'] == 1]


x_test_l30.drop('catAge_<=30', inplace=True, axis=1)
x_test_l30.drop('catAge_30-40', inplace=True, axis=1)
x_test_l30.drop('catAge_40-50', inplace=True, axis=1)
x_test_l30.drop('catAge_>=50', inplace=True, axis=1)

x_test_30to40.drop('catAge_<=30', inplace=True, axis=1)
x_test_30to40.drop('catAge_30-40', inplace=True, axis=1)
x_test_30to40.drop('catAge_40-50', inplace=True, axis=1)
x_test_30to40.drop('catAge_>=50', inplace=True, axis=1)

x_test_40to50.drop('catAge_<=30', inplace=True, axis=1)
x_test_40to50.drop('catAge_30-40', inplace=True, axis=1)
x_test_40to50.drop('catAge_40-50', inplace=True, axis=1)
x_test_40to50.drop('catAge_>=50', inplace=True, axis=1)

x_test_g50.drop('catAge_<=30', inplace=True, axis=1)
x_test_g50.drop('catAge_30-40', inplace=True, axis=1)
x_test_g50.drop('catAge_40-50', inplace=True, axis=1)
x_test_g50.drop('catAge_>=50', inplace=True, axis=1)



# x_test_unawareness.columns.values
# x_test.columns.values

CPU times: user 85 ms, sys: 12.6 ms, total: 97.6 ms
Wall time: 134 ms


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/core/frame.py:4163: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


In [144]:
%%time
# Test on l30 set

clf_pred_l30 = clf.fit(x_train_unawareness, y_train).predict(x_test_l30)

test_df = x_test_l30.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(clf_pred_l30, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_l30 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_l30

CPU times: user 2.99 s, sys: 258 ms, total: 3.25 s
Wall time: 3.03 s


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([[692, 486],
       [105,  81]])

In [145]:
%%time
accuracy_clf_l30 = (confusion_matrix_l30[0][0] + confusion_matrix_l30[1][1]) / (confusion_matrix_l30[0][0] + confusion_matrix_l30[0][1] + confusion_matrix_l30[1][0] + confusion_matrix_l30[1][1])
accuracy_clf_l30

CPU times: user 94 µs, sys: 2 µs, total: 96 µs
Wall time: 108 µs


0.5667155425219942

In [146]:
%%time
# Test on 30to40 set

clf_pred_30to40 = clf.fit(x_train_unawareness, y_train).predict(x_test_30to40)

test_df = x_test_30to40.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(clf_pred_30to40, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_30to40 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_30to40


CPU times: user 2.66 s, sys: 197 ms, total: 2.86 s
Wall time: 2.66 s


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([[1566, 1551],
       [ 204,  220]])

In [147]:
%%time
accuracy_clf_30to40 = (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[1][1]) / (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[0][1] + confusion_matrix_30to40[1][0] + confusion_matrix_30to40[1][1])
accuracy_clf_30to40 

CPU times: user 85 µs, sys: 2 µs, total: 87 µs
Wall time: 98 µs


0.5043772945495623

In [148]:
%%time
# Test on 40to50 set

clf_pred_40to50 = clf.fit(x_train_unawareness, y_train).predict(x_test_40to50)

test_df = x_test_40to50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(clf_pred_40to50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_40to50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_40to50

CPU times: user 2.31 s, sys: 148 ms, total: 2.46 s
Wall time: 2.04 s


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([[ 971, 1055],
       [ 126,  152]])

In [149]:
%%time
accuracy_clf_40to50 = (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[1][1]) / (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[0][1] + confusion_matrix_40to50[1][0] + confusion_matrix_40to50[1][1])
accuracy_clf_40to50 # 0.8718606782768102

CPU times: user 113 µs, sys: 8 µs, total: 121 µs
Wall time: 65.8 µs


0.4874131944444444

In [150]:
%%time
# Test on g50 set

clf_pred_g50 = clf.fit(x_train_unawareness, y_train).predict(x_test_g50)

test_df = x_test_g50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(clf_pred_g50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_g50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_g50

CPU times: user 2.42 s, sys: 178 ms, total: 2.6 s
Wall time: 2.59 s


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([[782, 818],
       [ 98, 102]])

In [151]:
%%time
accuracy_clf_g50 = (confusion_matrix_g50[0][0] + confusion_matrix_g50[1][1]) / (confusion_matrix_g50[0][0] + confusion_matrix_g50[0][1] + confusion_matrix_g50[1][0] + confusion_matrix_g50[1][1])
accuracy_clf_g50 # 0.8718606782768102

CPU times: user 128 µs, sys: 41 µs, total: 169 µs
Wall time: 101 µs


0.4911111111111111