Credit Scoring Fairness Criteria

Load the dataset

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.cm as cm

Load the dataset

In [2]:
import os
BANK_PATH = os.path.join(os.getcwd(), 'ml bank dataset/bankfullclean.csv') # Assign this to the location of the dataset
print(os.getcwd())
print(BANK_PATH)

# 5254 number of rows have 'biY' == 1
# 39787 number of rows have 'biY' == 0


/Users/xinyu/Desktop/senior spring/Independent Study/ML fairness
/Users/xinyu/Desktop/senior spring/Independent Study/ML fairness/ml bank dataset/bankfullclean.csv


In [3]:
bank = pd.read_csv(BANK_PATH)
df = pd.DataFrame(bank)
df.head()
dummy = df[['catAge', 'job', 'marital','education','balance','day', 'month', 'duration', 'campaign', 'pdays', 'previous', 'Fmonth', 'biDefault', 'biHousing', 'biLoan']]
# dummy.columns.values
dummy = pd.get_dummies(data=dummy)
# dummy.head()
dummy.columns.values
# df['marital'].unique()

# df['biY'].replace({0: False, 1: True}, inplace=True)
# print(df['biY'])


array(['balance', 'day', 'duration', 'campaign', 'pdays', 'previous',
       'biDefault', 'biHousing', 'biLoan', 'catAge_30-40', 'catAge_40-50',
       'catAge_<=30', 'catAge_>=50', 'job_admin.', 'job_blue-collar',
       'job_entrepreneur', 'job_housemaid', 'job_management',
       'job_retired', 'job_self-employed', 'job_services', 'job_student',
       'job_technician', 'job_unemployed', 'marital_divorced',
       'marital_married', 'marital_single', 'education_primary',
       'education_secondary', 'education_tertiary', 'month_apr',
       'month_aug', 'month_dec', 'month_feb', 'month_jan', 'month_jul',
       'month_jun', 'month_mar', 'month_may', 'month_nov', 'month_oct',
       'month_sep', 'Fmonth_apr', 'Fmonth_aug', 'Fmonth_dec',
       'Fmonth_feb', 'Fmonth_jan', 'Fmonth_jul', 'Fmonth_jun',
       'Fmonth_mar', 'Fmonth_may', 'Fmonth_nov', 'Fmonth_oct'],
      dtype=object)

Machine Learning Classification Model

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import LeaveOneOut

In [5]:
def get_naive_dataset(dataset):
    dataset = dataset.sample(frac=1).reset_index(drop=True)
    X = dummy
    y = dataset['biY']

    # x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
    loo = LeaveOneOut()
    loo.get_n_splits(X)

    for train_index, test_index in loo.split(X):
        X_train, X_test = X[train_index], X[test_index]
        y_train, y_test = y[train_index], y[test_index]

    return (x_train, y_train), (x_test, y_test)

In [6]:
(x_train, y_train), (x_test, y_test) = get_naive_dataset(df)

In [7]:
x_train.columns.values

array(['balance', 'day', 'duration', 'campaign', 'pdays', 'previous',
       'biDefault', 'biHousing', 'biLoan', 'catAge_30-40', 'catAge_40-50',
       'catAge_<=30', 'catAge_>=50', 'job_admin.', 'job_blue-collar',
       'job_entrepreneur', 'job_housemaid', 'job_management',
       'job_retired', 'job_self-employed', 'job_services', 'job_student',
       'job_technician', 'job_unemployed', 'marital_divorced',
       'marital_married', 'marital_single', 'education_primary',
       'education_secondary', 'education_tertiary', 'month_apr',
       'month_aug', 'month_dec', 'month_feb', 'month_jan', 'month_jul',
       'month_jun', 'month_mar', 'month_may', 'month_nov', 'month_oct',
       'month_sep', 'Fmonth_apr', 'Fmonth_aug', 'Fmonth_dec',
       'Fmonth_feb', 'Fmonth_jan', 'Fmonth_jul', 'Fmonth_jun',
       'Fmonth_mar', 'Fmonth_may', 'Fmonth_nov', 'Fmonth_oct'],
      dtype=object)

In [8]:
y_train.values

array([0, 0, 0, ..., 0, 0, 0])

In [9]:
x_test.columns.values

array(['balance', 'day', 'duration', 'campaign', 'pdays', 'previous',
       'biDefault', 'biHousing', 'biLoan', 'catAge_30-40', 'catAge_40-50',
       'catAge_<=30', 'catAge_>=50', 'job_admin.', 'job_blue-collar',
       'job_entrepreneur', 'job_housemaid', 'job_management',
       'job_retired', 'job_self-employed', 'job_services', 'job_student',
       'job_technician', 'job_unemployed', 'marital_divorced',
       'marital_married', 'marital_single', 'education_primary',
       'education_secondary', 'education_tertiary', 'month_apr',
       'month_aug', 'month_dec', 'month_feb', 'month_jan', 'month_jul',
       'month_jun', 'month_mar', 'month_may', 'month_nov', 'month_oct',
       'month_sep', 'Fmonth_apr', 'Fmonth_aug', 'Fmonth_dec',
       'Fmonth_feb', 'Fmonth_jan', 'Fmonth_jul', 'Fmonth_jun',
       'Fmonth_mar', 'Fmonth_may', 'Fmonth_nov', 'Fmonth_oct'],
      dtype=object)

In [10]:
y_test.values

array([0, 0, 0, ..., 0, 0, 0])

Naive Bayes Model

In [11]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb_pred = gnb.fit(x_train, y_train).predict(x_test)

Result

In [12]:
test_df = x_test.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(gnb_pred, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])
test_df.columns.values

array(['balance', 'day', 'duration', 'campaign', 'pdays', 'previous',
       'biDefault', 'biHousing', 'biLoan', 'catAge_30-40', 'catAge_40-50',
       'catAge_<=30', 'catAge_>=50', 'job_admin.', 'job_blue-collar',
       'job_entrepreneur', 'job_housemaid', 'job_management',
       'job_retired', 'job_self-employed', 'job_services', 'job_student',
       'job_technician', 'job_unemployed', 'marital_divorced',
       'marital_married', 'marital_single', 'education_primary',
       'education_secondary', 'education_tertiary', 'month_apr',
       'month_aug', 'month_dec', 'month_feb', 'month_jan', 'month_jul',
       'month_jun', 'month_mar', 'month_may', 'month_nov', 'month_oct',
       'month_sep', 'Fmonth_apr', 'Fmonth_aug', 'Fmonth_dec',
       'Fmonth_feb', 'Fmonth_jan', 'Fmonth_jul', 'Fmonth_jun',
       'Fmonth_mar', 'Fmonth_may', 'Fmonth_nov', 'Fmonth_oct', 'biY',
       'pred', 'accurate'], dtype=object)

In [13]:
from sklearn.metrics import confusion_matrix

In [14]:

confusion_matrix = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix

array([[7765,  218],
       [ 994,   32]])

In [15]:
# Accuracy
# "Accuracy: ", test_df.accurate.mean()
accuracy_naive_bayes = (confusion_matrix[0][0] + confusion_matrix[1][1]) / (confusion_matrix[0][0] + confusion_matrix[0][1] + confusion_matrix[1][0] + confusion_matrix[1][1])
accuracy_naive_bayes



0.8654678654678655

In [16]:
# Split dataset based on marital status
test_df.columns.values
test_l30 = x_test[x_test['catAge_<=30'] == 1]
test_30to40 = x_test[x_test['catAge_30-40'] == 1]
test_40to50 = x_test[x_test['catAge_40-50'] == 1]
test_g50 = x_test[x_test['catAge_>=50'] == 1]

In [17]:
# Test on l30 subset
gnb_pred_l30 = gnb.fit(x_train, y_train).predict(test_l30)

test_df = test_l30.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(gnb_pred_l30, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_l30 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_l30


array([[1221,   18],
       [ 184,    1]])

In [18]:
accuracy_naive_bayes_l30 = (confusion_matrix_l30[0][0] + confusion_matrix_l30[1][1]) / (confusion_matrix_l30[0][0] + confusion_matrix_l30[0][1] + confusion_matrix_l30[1][0] + confusion_matrix_l30[1][1])
accuracy_naive_bayes_l30

0.8581460674157303

In [19]:
# Test on 30to40 subset
gnb_pred_30to40 = gnb.fit(x_train, y_train).predict(test_30to40)

test_df = test_30to40.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(gnb_pred_30to40, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_30to40 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_30to40

array([[3064,   62],
       [ 373,   10]])

In [20]:
accuracy_naive_bayes_30to40 = (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[1][1]) / (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[0][1] + confusion_matrix_30to40[1][0] + confusion_matrix_30to40[1][1])
accuracy_naive_bayes_30to40

0.8760330578512396

In [21]:
# Test on 40to50 subset
gnb_pred_40to50 = gnb.fit(x_train, y_train).predict(test_40to50)

test_df = test_40to50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(gnb_pred_40to50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_40to50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_40to50

array([[1926,   69],
       [ 252,   10]])

In [22]:
accuracy_naive_bayes_40to50 = (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[1][1]) / (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[0][1] + confusion_matrix_40to50[1][0] + confusion_matrix_40to50[1][1])
accuracy_naive_bayes_40to50 # 0.8718606782768102

0.8577758085954807

In [23]:
# Test on g50 subset
gnb_pred_g50 = gnb.fit(x_train, y_train).predict(test_g50)

test_df = test_g50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(gnb_pred_g50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_g50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_g50

array([[1554,   69],
       [ 185,   11]])

In [24]:
accuracy_naive_bayes_g50 = (confusion_matrix_g50[0][0] + confusion_matrix_g50[1][1]) / (confusion_matrix_g50[0][0] + confusion_matrix_g50[0][1] + confusion_matrix_g50[1][0] + confusion_matrix_g50[1][1])
accuracy_naive_bayes_g50 # 0.8718606782768102

0.8603628367234745

In [25]:
#Demographic Parity
# positive rate = TP + TN
PR_Naive_Bayes_l30 = confusion_matrix_l30[0,0] +confusion_matrix_l30[1,1]

PR_Naive_Bayes_l30 


1222

In [26]:
PR_Naive_Bayes_30to40 = confusion_matrix_30to40[0,0] +confusion_matrix_30to40[1,1]
PR_Naive_Bayes_30to40

3074

In [27]:
PR_Naive_Bayes_40to50 = confusion_matrix_40to50[0,0] +confusion_matrix_40to50[1,1]
PR_Naive_Bayes_40to50 

1936

In [28]:
PR_Naive_Bayes_g50 = confusion_matrix_g50[0,0] +confusion_matrix_g50[1,1]
PR_Naive_Bayes_g50 

1565

In [29]:
# Equalized Opportunity
#TPR = TP/TP+FN

TPR_Naive_Bayes_l30 = confusion_matrix_l30[0,0] / (confusion_matrix_l30[0,0] + confusion_matrix_l30[1,0])

TPR_Naive_Bayes_l30


0.8690391459074733

In [30]:
TPR_Naive_Bayes_30to40 = confusion_matrix_30to40[0,0] / (confusion_matrix_30to40[0,0] + confusion_matrix_30to40[1,0])

TPR_Naive_Bayes_30to40

0.8914751236543498

In [31]:
TPR_Naive_Bayes_40to50 = confusion_matrix_40to50[0,0] / (confusion_matrix_40to50[0,0] + confusion_matrix_40to50[1,0])

TPR_Naive_Bayes_40to50 

0.8842975206611571

In [32]:
TPR_Naive_Bayes_g50 = confusion_matrix_g50[0,0] / (confusion_matrix_g50[0,0] + confusion_matrix_g50[1,0])

TPR_Naive_Bayes_g50 # 0.8925619834710744

0.8936170212765957

In [33]:
# Equalized Odds
#TPR = TP/TP+FN
#FNR = FN/FN+TP


FNR_Naive_Bayes_l30 = confusion_matrix_l30[1,0] / (confusion_matrix_l30[1,0] + confusion_matrix_l30[0,0])

FNR_Naive_Bayes_l30



0.1309608540925267

In [34]:
FNR_Naive_Bayes_30to40 = confusion_matrix_30to40[1,0] / (confusion_matrix_30to40[1,0] + confusion_matrix_30to40[0,0])

FNR_Naive_Bayes_30to40

0.10852487634565028

In [35]:
FNR_Naive_Bayes_40to50 = confusion_matrix_40to50[1,0] / (confusion_matrix_40to50[1,0] + confusion_matrix_40to50[0,0])

FNR_Naive_Bayes_40to50

0.11570247933884298

In [36]:
FNR_Naive_Bayes_g50 = confusion_matrix_g50[1,0] / (confusion_matrix_g50[1,0] + confusion_matrix_g50[0,0])

FNR_Naive_Bayes_g50

0.10638297872340426

In [37]:
# Fairness Through Unwareness
x_train_unawareness = x_train.copy()
x_train_unawareness
x_train_unawareness.drop('catAge_<=30', inplace=True, axis=1)
x_train_unawareness.drop('catAge_30-40', inplace=True, axis=1)
x_train_unawareness.drop('catAge_40-50', inplace=True, axis=1)
x_train_unawareness.drop('catAge_>=50', inplace=True, axis=1)

# x_train_unawareness.columns.values
# x_train.columns.values






In [38]:
#Fairness through unawareness

x_test_unawareness = x_test.copy()
x_test_unawareness
x_test_l30 = x_test_unawareness[x_test_unawareness['catAge_<=30'] == 1]
x_test_30to40 = x_test_unawareness[x_test_unawareness['catAge_30-40'] == 1]
x_test_40to50 = x_test_unawareness[x_test_unawareness['catAge_40-50'] == 1]
x_test_g50 = x_test_unawareness[x_test_unawareness['catAge_>=50'] == 1]


x_test_l30.drop('catAge_<=30', inplace=True, axis=1)
x_test_l30.drop('catAge_30-40', inplace=True, axis=1)
x_test_l30.drop('catAge_40-50', inplace=True, axis=1)
x_test_l30.drop('catAge_>=50', inplace=True, axis=1)

x_test_30to40.drop('catAge_<=30', inplace=True, axis=1)
x_test_30to40.drop('catAge_30-40', inplace=True, axis=1)
x_test_30to40.drop('catAge_40-50', inplace=True, axis=1)
x_test_30to40.drop('catAge_>=50', inplace=True, axis=1)

x_test_40to50.drop('catAge_<=30', inplace=True, axis=1)
x_test_40to50.drop('catAge_30-40', inplace=True, axis=1)
x_test_40to50.drop('catAge_40-50', inplace=True, axis=1)
x_test_40to50.drop('catAge_>=50', inplace=True, axis=1)

x_test_g50.drop('catAge_<=30', inplace=True, axis=1)
x_test_g50.drop('catAge_30-40', inplace=True, axis=1)
x_test_g50.drop('catAge_40-50', inplace=True, axis=1)
x_test_g50.drop('catAge_>=50', inplace=True, axis=1)




# x_test_unawareness.columns.values
# x_test.columns.values
# test_married

In [39]:
# Test on l30 set
gnb_pred_l30 = gnb.fit(x_train_unawareness, y_train).predict(x_test_l30)

test_df = x_test_l30.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(gnb_pred_l30, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_l30 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_l30



array([[1220,   19],
       [ 184,    1]])

In [40]:
accuracy_naive_bayes_l30 = (confusion_matrix_l30[0][0] + confusion_matrix_l30[1][1]) / (confusion_matrix_l30[0][0] + confusion_matrix_l30[0][1] + confusion_matrix_l30[1][0] + confusion_matrix_l30[1][1])
accuracy_naive_bayes_l30 

0.8574438202247191

In [41]:
# Test on 30to40 set
gnb_pred_30to40 = gnb.fit(x_train_unawareness, y_train).predict(x_test_30to40)

test_df = x_test_30to40.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(gnb_pred_30to40, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_30to40 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_30to40



array([[3069,   57],
       [ 373,   10]])

In [42]:
accuracy_naive_bayes_30to40 = (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[1][1]) / (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[0][1] + confusion_matrix_30to40[1][0] + confusion_matrix_30to40[1][1])
accuracy_naive_bayes_30to40 

0.8774579652322599

In [43]:
# Test on 40to50 set
gnb_pred_40to50 = gnb.fit(x_train_unawareness, y_train).predict(x_test_40to50)

test_df = x_test_40to50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(gnb_pred_40to50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_40to50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_40to50

array([[1929,   66],
       [ 253,    9]])

In [44]:
accuracy_naive_bayes_40to50 = (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[1][1]) / (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[0][1] + confusion_matrix_40to50[1][0] + confusion_matrix_40to50[1][1])
accuracy_naive_bayes_40to50 # 0.8718606782768102

0.8586619406291538

In [45]:
# Test on g50 set
gnb_pred_g50 = gnb.fit(x_train_unawareness, y_train).predict(x_test_g50)

test_df = x_test_g50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(gnb_pred_g50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_g50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_g50

array([[1543,   80],
       [ 182,   14]])

In [46]:
accuracy_naive_bayes_g50 = (confusion_matrix_g50[0][0] + confusion_matrix_g50[1][1]) / (confusion_matrix_g50[0][0] + confusion_matrix_g50[0][1] + confusion_matrix_g50[1][0] + confusion_matrix_g50[1][1])
accuracy_naive_bayes_g50 # 0.8718606782768102

0.8559648158328752

Random Forest Model

In [47]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(max_depth=5, random_state=0, class_weight='balanced')
rf_pred = rf.fit(x_train, y_train).predict(x_test)

In [48]:
test_df = x_test.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(rf_pred, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])
test_df.columns.values

array(['balance', 'day', 'duration', 'campaign', 'pdays', 'previous',
       'biDefault', 'biHousing', 'biLoan', 'catAge_30-40', 'catAge_40-50',
       'catAge_<=30', 'catAge_>=50', 'job_admin.', 'job_blue-collar',
       'job_entrepreneur', 'job_housemaid', 'job_management',
       'job_retired', 'job_self-employed', 'job_services', 'job_student',
       'job_technician', 'job_unemployed', 'marital_divorced',
       'marital_married', 'marital_single', 'education_primary',
       'education_secondary', 'education_tertiary', 'month_apr',
       'month_aug', 'month_dec', 'month_feb', 'month_jan', 'month_jul',
       'month_jun', 'month_mar', 'month_may', 'month_nov', 'month_oct',
       'month_sep', 'Fmonth_apr', 'Fmonth_aug', 'Fmonth_dec',
       'Fmonth_feb', 'Fmonth_jan', 'Fmonth_jul', 'Fmonth_jun',
       'Fmonth_mar', 'Fmonth_may', 'Fmonth_nov', 'Fmonth_oct', 'biY',
       'pred', 'accurate'], dtype=object)

In [49]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix

array([[4219, 3764],
       [ 545,  481]])

In [50]:
# Accuracy
# "Accuracy: ", test_df.accurate.mean()
accuracy_rf = (confusion_matrix[0][0] + confusion_matrix[1][1]) / (confusion_matrix[0][0] + confusion_matrix[0][1] + confusion_matrix[1][0] + confusion_matrix[1][1])
accuracy_rf


0.5217005217005217

In [51]:
# Split dataset based on marital status
test_df.columns.values
test_l30 = x_test[x_test['catAge_<=30'] == 1]
test_30to40 = x_test[x_test['catAge_30-40'] == 1]
test_40to50 = x_test[x_test['catAge_40-50'] == 1]
test_g50 = x_test[x_test['catAge_>=50'] == 1]

In [52]:
# Test on single subset
rf_pred_l30 = rf.fit(x_train, y_train).predict(test_l30)

test_df = test_l30.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(rf_pred_l30, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_l30 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_l30

array([[824, 415],
       [121,  64]])

In [53]:
accuracy_rf_l30 = (confusion_matrix_l30[0][0] + confusion_matrix_l30[1][1]) / (confusion_matrix_l30[0][0] + confusion_matrix_l30[0][1] + confusion_matrix_l30[1][0] + confusion_matrix_l30[1][1])
accuracy_rf_l30

0.6235955056179775

In [54]:
# Test on 30to40 subset
rf_pred_30to40 = rf.fit(x_train, y_train).predict(test_30to40)

test_df = test_30to40.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(rf_pred_30to40, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_30to40 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_30to40

array([[1558, 1568],
       [ 182,  201]])

In [55]:
accuracy_rf_30to40 = (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[1][1]) / (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[0][1] + confusion_matrix_30to40[1][0] + confusion_matrix_30to40[1][1])
accuracy_rf_30to40

0.5012824166429182

In [56]:
# Test on 40to50 subset
rf_pred_40to50 = rf.fit(x_train, y_train).predict(test_40to50)
 
test_df = test_40to50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(rf_pred_40to50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])
 
from sklearn.metrics import confusion_matrix
 
confusion_matrix_40to50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_40to50


array([[ 937, 1058],
       [ 129,  133]])

In [57]:
accuracy_rf_40to50 = (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[1][1]) / (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[0][1] + confusion_matrix_40to50[1][0] + confusion_matrix_40to50[1][1])
accuracy_rf_40to50 

0.4740806380150642

In [58]:
# Test on g50 subset
rf_pred_g50 = rf.fit(x_train, y_train).predict(test_g50)
 
test_df = test_g50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(rf_pred_g50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])
 
from sklearn.metrics import confusion_matrix
 
confusion_matrix_g50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_g50

array([[900, 723],
       [113,  83]])

In [59]:
accuracy_rf_g50 = (confusion_matrix_g50[0][0] + confusion_matrix_g50[1][1]) / (confusion_matrix_g50[0][0] + confusion_matrix_g50[0][1] + confusion_matrix_g50[1][0] + confusion_matrix_g50[1][1])
accuracy_rf_g50 

0.5404068169323805

In [60]:
#Demographic Parity
# positive rate = TP + TN
PR_rf_l30 = confusion_matrix_l30[0,0] +confusion_matrix_l30[1,1]
PR_rf_l30 # 4756

888

In [61]:
PR_rf_30to40 = confusion_matrix_30to40[0,0] +confusion_matrix_30to40[1,1]
PR_rf_30to40 # 2136

1759

In [62]:
PR_rf_40to50 = confusion_matrix_40to50[0,0] +confusion_matrix_40to50[1,1]
PR_rf_40to50 # 2136

1070

In [63]:
PR_rf_g50 = confusion_matrix_g50[0,0] +confusion_matrix_g50[1,1]
PR_rf_g50 # 2136

983

In [64]:
# Equalized Opportunity
#TPR = TP/TP+FN

TPR_rf_l30 = confusion_matrix_l30[0,0] / (confusion_matrix_l30[0,0] + confusion_matrix_l30[1,0])

TPR_rf_l30

0.8719576719576719

In [65]:
TPR_rf_30to40 = confusion_matrix_30to40[0,0] / (confusion_matrix_30to40[0,0] + confusion_matrix_30to40[1,0])

TPR_rf_30to40  

0.8954022988505748

In [66]:
TPR_rf_40to50  = confusion_matrix_40to50[0,0] / (confusion_matrix_40to50[0,0] + confusion_matrix_40to50[1,0])

TPR_rf_40to50 

0.8789868667917449

In [67]:
TPR_rf_g50  = confusion_matrix_g50[0,0] / (confusion_matrix_g50[0,0] + confusion_matrix_g50[1,0])

TPR_rf_g50 

0.8884501480750246

In [68]:
# Equalized Odds
#TPR = TP/TP+FN
#FNR = FN/FN+TP


FNR_rf_l30 = confusion_matrix_l30[1,0] / (confusion_matrix_l30[1,0] + confusion_matrix_l30[0,0])

FNR_rf_l30 # 0.11652109273369263


0.12804232804232804

In [69]:
FNR_rf_30to40 = confusion_matrix_30to40[1,0] / (confusion_matrix_30to40[1,0] + confusion_matrix_30to40[0,0])

FNR_rf_30to40

0.10459770114942529

In [70]:
FNR_rf_40to50 = confusion_matrix_40to50[1,0] / (confusion_matrix_40to50[1,0] + confusion_matrix_40to50[0,0])

FNR_rf_40to50

0.12101313320825516

In [71]:
FNR_rf_g50 = confusion_matrix_g50[1,0] / (confusion_matrix_g50[1,0] + confusion_matrix_g50[0,0])

FNR_rf_g50

0.11154985192497532

In [72]:
# Fairness Through Unwareness
x_train_unawareness = x_train.copy()
x_train_unawareness
x_train_unawareness.drop('catAge_<=30', inplace=True, axis=1)
x_train_unawareness.drop('catAge_30-40', inplace=True, axis=1)
x_train_unawareness.drop('catAge_40-50', inplace=True, axis=1)
x_train_unawareness.drop('catAge_>=50', inplace=True, axis=1)

# x_train_unawareness.columns.values
# x_train.columns.values

In [73]:
#Fairness through unawareness

x_test_unawareness = x_test.copy()
x_test_unawareness
x_test_l30 = x_test_unawareness[x_test_unawareness['catAge_<=30'] == 1]
x_test_30to40 = x_test_unawareness[x_test_unawareness['catAge_30-40'] == 1]
x_test_40to50 = x_test_unawareness[x_test_unawareness['catAge_40-50'] == 1]
x_test_g50 = x_test_unawareness[x_test_unawareness['catAge_>=50'] == 1]


x_test_l30.drop('catAge_<=30', inplace=True, axis=1)
x_test_l30.drop('catAge_30-40', inplace=True, axis=1)
x_test_l30.drop('catAge_40-50', inplace=True, axis=1)
x_test_l30.drop('catAge_>=50', inplace=True, axis=1)

x_test_30to40.drop('catAge_<=30', inplace=True, axis=1)
x_test_30to40.drop('catAge_30-40', inplace=True, axis=1)
x_test_30to40.drop('catAge_40-50', inplace=True, axis=1)
x_test_30to40.drop('catAge_>=50', inplace=True, axis=1)

x_test_40to50.drop('catAge_<=30', inplace=True, axis=1)
x_test_40to50.drop('catAge_30-40', inplace=True, axis=1)
x_test_40to50.drop('catAge_40-50', inplace=True, axis=1)
x_test_40to50.drop('catAge_>=50', inplace=True, axis=1)

x_test_g50.drop('catAge_<=30', inplace=True, axis=1)
x_test_g50.drop('catAge_30-40', inplace=True, axis=1)
x_test_g50.drop('catAge_40-50', inplace=True, axis=1)
x_test_g50.drop('catAge_>=50', inplace=True, axis=1)



# x_test_unawareness.columns.values
# x_test.columns.values

In [74]:
# Test on l30 set
rf_pred_l30 = rf.fit(x_train_unawareness, y_train).predict(x_test_l30)

test_df = x_test_l30.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(rf_pred_l30, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_l30 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_l30


array([[780, 459],
       [119,  66]])

In [75]:
accuracy_rf_l30 = (confusion_matrix_l30[0][0] + confusion_matrix_l30[1][1]) / (confusion_matrix_l30[0][0] + confusion_matrix_l30[0][1] + confusion_matrix_l30[1][0] + confusion_matrix_l30[1][1])
accuracy_rf_l30

0.5941011235955056

In [76]:
# Test on 30to40 set
rf_pred_30to40 = rf.fit(x_train_unawareness, y_train).predict(x_test_30to40)

test_df = x_test_30to40.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(rf_pred_30to40, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_30to40 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_30to40


array([[1638, 1488],
       [ 207,  176]])

In [77]:
accuracy_rf_30to40 = (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[1][1]) / (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[0][1] + confusion_matrix_30to40[1][0] + confusion_matrix_30to40[1][1])
accuracy_rf_30to40 

0.5169563978341408

In [78]:
# Test on 40to50 set
rf_pred_40to50 = rf.fit(x_train_unawareness, y_train).predict(x_test_40to50)

test_df = x_test_40to50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(rf_pred_40to50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_40to50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_40to50

array([[ 968, 1027],
       [ 133,  129]])

In [79]:
accuracy_rf_40to50 = (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[1][1]) / (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[0][1] + confusion_matrix_40to50[1][0] + confusion_matrix_40to50[1][1])
accuracy_rf_40to50 # 0.8718606782768102

0.48604342046965

In [80]:
# Test on g50 set
rf_pred_g50 = rf.fit(x_train_unawareness, y_train).predict(x_test_g50)

test_df = x_test_g50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(rf_pred_g50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_g50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_g50

array([[782, 841],
       [109,  87]])

In [81]:
accuracy_rf_g50 = (confusion_matrix_g50[0][0] + confusion_matrix_g50[1][1]) / (confusion_matrix_g50[0][0] + confusion_matrix_g50[0][1] + confusion_matrix_g50[1][0] + confusion_matrix_g50[1][1])
accuracy_rf_g50 # 0.8718606782768102

0.4777350192413414

Support Vector Machine

In [82]:
from sklearn import svm as svm_model
svm = svm_model.SVC(class_weight='balanced') # add class_weight='balanced' is to avoid classifying all data as 0
svm_pred = svm.fit(x_train, y_train).predict(x_test)

In [83]:
test_df = x_test.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(svm_pred, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])
test_df.columns.values

array(['balance', 'day', 'duration', 'campaign', 'pdays', 'previous',
       'biDefault', 'biHousing', 'biLoan', 'catAge_30-40', 'catAge_40-50',
       'catAge_<=30', 'catAge_>=50', 'job_admin.', 'job_blue-collar',
       'job_entrepreneur', 'job_housemaid', 'job_management',
       'job_retired', 'job_self-employed', 'job_services', 'job_student',
       'job_technician', 'job_unemployed', 'marital_divorced',
       'marital_married', 'marital_single', 'education_primary',
       'education_secondary', 'education_tertiary', 'month_apr',
       'month_aug', 'month_dec', 'month_feb', 'month_jan', 'month_jul',
       'month_jun', 'month_mar', 'month_may', 'month_nov', 'month_oct',
       'month_sep', 'Fmonth_apr', 'Fmonth_aug', 'Fmonth_dec',
       'Fmonth_feb', 'Fmonth_jan', 'Fmonth_jul', 'Fmonth_jun',
       'Fmonth_mar', 'Fmonth_may', 'Fmonth_nov', 'Fmonth_oct', 'biY',
       'pred', 'accurate'], dtype=object)

In [84]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix

array([[3430, 4553],
       [ 446,  580]])

In [85]:
# Accuracy
# "Accuracy: ", test_df.accurate.mean()
accuracy_svm = (confusion_matrix[0][0] + confusion_matrix[1][1]) / (confusion_matrix[0][0] + confusion_matrix[0][1] + confusion_matrix[1][0] + confusion_matrix[1][1])
accuracy_svm


0.4451104451104451

In [86]:
# Split dataset based on marital status
test_df.columns.values
test_l30 = x_test[x_test['catAge_<=30'] == 1]
test_30to40 = x_test[x_test['catAge_30-40'] == 1]
test_40to50 = x_test[x_test['catAge_40-50'] == 1]
test_g50 = x_test[x_test['catAge_>=50'] == 1]

In [87]:
# Test on l30 subset
svm_pred_l30 = svm.fit(x_train, y_train).predict(test_l30)

test_df = test_l30.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(svm_pred_l30, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_l30 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_l30

array([[493, 746],
       [ 67, 118]])

In [88]:
accuracy_svm_l30 = (confusion_matrix_l30[0][0] + confusion_matrix_l30[1][1]) / (confusion_matrix_l30[0][0] + confusion_matrix_l30[0][1] + confusion_matrix_l30[1][0] + confusion_matrix_l30[1][1])
accuracy_svm_l30

0.42907303370786515

In [89]:
# Test on married subset
svm_pred_30to40 = svm.fit(x_train, y_train).predict(test_30to40)

test_df = test_30to40.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(svm_pred_30to40, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_30to40 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_30to40

array([[1295, 1831],
       [ 163,  220]])

In [90]:
accuracy_svm_30to40 = (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[1][1]) / (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[0][1] + confusion_matrix_30to40[1][0] + confusion_matrix_30to40[1][1])
accuracy_svm_30to40 # 0.8718606782768102

0.4317469364491308

In [91]:
# Test on 40to50 subset
svm_pred_40to50 = svm.fit(x_train, y_train).predict(test_40to50)

test_df = test_40to50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(svm_pred_40to50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_40to50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_40to50

array([[ 890, 1105],
       [ 115,  147]])

In [92]:
accuracy_svm_40to50 = (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[1][1]) / (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[0][1] + confusion_matrix_40to50[1][0] + confusion_matrix_40to50[1][1])
accuracy_svm_40to50 

0.4594594594594595

In [93]:
# Test on g50 subset
svm_pred_g50 = svm.fit(x_train, y_train).predict(test_g50)

test_df = test_g50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(svm_pred_g50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_g50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_g50

array([[752, 871],
       [101,  95]])

In [94]:
accuracy_svm_g50 = (confusion_matrix_g50[0][0] + confusion_matrix_g50[1][1]) / (confusion_matrix_g50[0][0] + confusion_matrix_g50[0][1] + confusion_matrix_g50[1][0] + confusion_matrix_g50[1][1])
accuracy_svm_g50 # 0.8718606782768102

0.46564046179219354

In [95]:
#Demographic Parity
# positive rate = TP + TN
PR_svm_l30 = confusion_matrix_l30[0,0] +confusion_matrix_l30[1,1]

PR_svm_l30

611

In [96]:
PR_svm_30to40 = confusion_matrix_30to40[0,0] +confusion_matrix_30to40[1,1]
PR_svm_30to40

1515

In [97]:
PR_svm_40to50 = confusion_matrix_40to50[0,0] +confusion_matrix_40to50[1,1]
PR_svm_40to50

1037

In [98]:
PR_svm_g50 = confusion_matrix_g50[0,0] +confusion_matrix_g50[1,1]
PR_svm_g50

847

In [99]:
# Equalized Opportunity
#TPR = TP/TP+FN

TPR_svm_l30 = confusion_matrix_l30[0,0] / (confusion_matrix_l30[0,0] + confusion_matrix_l30[1,0])

TPR_svm_l30

0.8803571428571428

In [100]:
TPR_svm_30to40 = confusion_matrix_30to40[0,0] / (confusion_matrix_30to40[0,0] + confusion_matrix_30to40[1,0])

TPR_svm_30to40 

0.8882030178326474

In [101]:
TPR_svm_40to50 = confusion_matrix_40to50[0,0] / (confusion_matrix_40to50[0,0] + confusion_matrix_40to50[1,0])

TPR_svm_40to50 

0.8855721393034826

In [102]:
TPR_svm_g50 = confusion_matrix_g50[0,0] / (confusion_matrix_g50[0,0] + confusion_matrix_g50[1,0])

TPR_svm_g50 

0.8815943728018757

In [103]:
# Equalized Odds
#TPR = TP/TP+FN
#FNR = FN/FN+TP


FNR_svm_l30 = confusion_matrix_l30[1,0] / (confusion_matrix_l30[1,0] + confusion_matrix_l30[0,0])

FNR_svm_l30

0.11964285714285715

In [104]:
FNR_svm_30to40 = confusion_matrix_30to40[1,0] / (confusion_matrix_30to40[1,0] + confusion_matrix_30to40[0,0])

FNR_svm_30to40 

0.11179698216735254

In [105]:
FNR_svm_40to50 = confusion_matrix_40to50[1,0] / (confusion_matrix_40to50[1,0] + confusion_matrix_40to50[0,0])

FNR_svm_40to50 

0.11442786069651742

In [106]:
FNR_svm_g50 = confusion_matrix_g50[1,0] / (confusion_matrix_g50[1,0] + confusion_matrix_g50[0,0])

FNR_svm_g50 

0.11840562719812427

In [107]:
# Fairness Through Unwareness
x_train_unawareness = x_train.copy()
x_train_unawareness
x_train_unawareness.drop('catAge_<=30', inplace=True, axis=1)
x_train_unawareness.drop('catAge_30-40', inplace=True, axis=1)
x_train_unawareness.drop('catAge_40-50', inplace=True, axis=1)
x_train_unawareness.drop('catAge_>=50', inplace=True, axis=1)


# x_train_unawareness.columns.values
# x_train.columns.values

In [108]:
#Fairness through unawareness


x_test_unawareness = x_test.copy()
x_test_unawareness
x_test_l30 = x_test_unawareness[x_test_unawareness['catAge_<=30'] == 1]
x_test_30to40 = x_test_unawareness[x_test_unawareness['catAge_30-40'] == 1]
x_test_40to50 = x_test_unawareness[x_test_unawareness['catAge_40-50'] == 1]
x_test_g50 = x_test_unawareness[x_test_unawareness['catAge_>=50'] == 1]


x_test_l30.drop('catAge_<=30', inplace=True, axis=1)
x_test_l30.drop('catAge_30-40', inplace=True, axis=1)
x_test_l30.drop('catAge_40-50', inplace=True, axis=1)
x_test_l30.drop('catAge_>=50', inplace=True, axis=1)

x_test_30to40.drop('catAge_<=30', inplace=True, axis=1)
x_test_30to40.drop('catAge_30-40', inplace=True, axis=1)
x_test_30to40.drop('catAge_40-50', inplace=True, axis=1)
x_test_30to40.drop('catAge_>=50', inplace=True, axis=1)

x_test_40to50.drop('catAge_<=30', inplace=True, axis=1)
x_test_40to50.drop('catAge_30-40', inplace=True, axis=1)
x_test_40to50.drop('catAge_40-50', inplace=True, axis=1)
x_test_40to50.drop('catAge_>=50', inplace=True, axis=1)

x_test_g50.drop('catAge_<=30', inplace=True, axis=1)
x_test_g50.drop('catAge_30-40', inplace=True, axis=1)
x_test_g50.drop('catAge_40-50', inplace=True, axis=1)
x_test_g50.drop('catAge_>=50', inplace=True, axis=1)



In [109]:
# Test on l30 set
svm_pred_l30 = svm.fit(x_train_unawareness, y_train).predict(x_test_l30)

test_df = x_test_l30.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(svm_pred_l30, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_l30 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_l30


array([[491, 748],
       [ 67, 118]])

In [110]:
accuracy_svm_l30 = (confusion_matrix_l30[0][0] + confusion_matrix_l30[1][1]) / (confusion_matrix_l30[0][0] + confusion_matrix_l30[0][1] + confusion_matrix_l30[1][0] + confusion_matrix_l30[1][1])
accuracy_svm_l30

0.4276685393258427

In [111]:
# Test on 30to40 set
svm_pred_30to40 = svm.fit(x_train_unawareness, y_train).predict(x_test_30to40)

test_df = x_test_30to40.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(svm_pred_30to40, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_30to40 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_30to40

array([[1289, 1837],
       [ 163,  220]])

In [112]:
accuracy_svm_30to40 = (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[1][1]) / (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[0][1] + confusion_matrix_30to40[1][0] + confusion_matrix_30to40[1][1])
accuracy_svm_30to40 # 0.8718606782768102

0.43003704759190653

In [113]:
# Test on 40to50 subset
svm_pred_40to50 = svm.fit(x_train_unawareness, y_train).predict(x_test_40to50)

test_df = x_test_40to50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(svm_pred_40to50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_40to50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_40to50

array([[ 889, 1106],
       [ 115,  147]])

In [114]:
accuracy_svm_40to50 = (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[1][1]) / (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[0][1] + confusion_matrix_40to50[1][0] + confusion_matrix_40to50[1][1])
accuracy_svm_40to50 

0.45901639344262296

In [115]:
# Test on g50 subset
svm_pred_g50 = svm.fit(x_train_unawareness, y_train).predict(x_test_g50)

test_df = x_test_g50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(svm_pred_g50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_g50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_g50

array([[752, 871],
       [101,  95]])

In [116]:
accuracy_svm_g50 = (confusion_matrix_g50[0][0] + confusion_matrix_g50[1][1]) / (confusion_matrix_g50[0][0] + confusion_matrix_g50[0][1] + confusion_matrix_g50[1][0] + confusion_matrix_g50[1][1])
accuracy_svm_g50 

0.46564046179219354

Logistic Regression Model

In [117]:
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(random_state=0, class_weight='balanced')
clf_pred = clf.fit(x_train, y_train).predict(x_test)

In [118]:
test_df = x_test.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(clf_pred, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])
test_df.columns.values

array(['balance', 'day', 'duration', 'campaign', 'pdays', 'previous',
       'biDefault', 'biHousing', 'biLoan', 'catAge_30-40', 'catAge_40-50',
       'catAge_<=30', 'catAge_>=50', 'job_admin.', 'job_blue-collar',
       'job_entrepreneur', 'job_housemaid', 'job_management',
       'job_retired', 'job_self-employed', 'job_services', 'job_student',
       'job_technician', 'job_unemployed', 'marital_divorced',
       'marital_married', 'marital_single', 'education_primary',
       'education_secondary', 'education_tertiary', 'month_apr',
       'month_aug', 'month_dec', 'month_feb', 'month_jan', 'month_jul',
       'month_jun', 'month_mar', 'month_may', 'month_nov', 'month_oct',
       'month_sep', 'Fmonth_apr', 'Fmonth_aug', 'Fmonth_dec',
       'Fmonth_feb', 'Fmonth_jan', 'Fmonth_jul', 'Fmonth_jun',
       'Fmonth_mar', 'Fmonth_may', 'Fmonth_nov', 'Fmonth_oct', 'biY',
       'pred', 'accurate'], dtype=object)

In [119]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix

array([[4149, 3834],
       [ 544,  482]])

In [120]:
# Accuracy
# "Accuracy: ", test_df.accurate.mean()
accuracy_clf = (confusion_matrix[0][0] + confusion_matrix[1][1]) / (confusion_matrix[0][0] + confusion_matrix[0][1] + confusion_matrix[1][0] + confusion_matrix[1][1])
accuracy_clf

0.514041514041514

In [121]:
# Split dataset based on marital status
test_df.columns.values
test_l30 = x_test[x_test['catAge_<=30'] == 1]
test_30to40 = x_test[x_test['catAge_30-40'] == 1]
test_40to50 = x_test[x_test['catAge_40-50'] == 1]
test_g50 = x_test[x_test['catAge_>=50'] == 1]

In [122]:
# Test on l30 subset
clf_pred_l30 = clf.fit(x_train, y_train).predict(test_l30)

test_df = test_l30.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(clf_pred_l30, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_l30 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_l30

array([[853, 386],
       [133,  52]])

In [123]:
accuracy_clf_l30 = (confusion_matrix_l30[0][0] + confusion_matrix_l30[1][1]) / (confusion_matrix_l30[0][0] + confusion_matrix_l30[0][1] + confusion_matrix_l30[1][0] + confusion_matrix_l30[1][1])
accuracy_clf_l30

0.6355337078651685

In [124]:
# Test on 30to40 subset
clf_pred_30to40 = clf.fit(x_train, y_train).predict(test_30to40)

test_df = test_30to40.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(clf_pred_30to40, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_30to40 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_30to40

array([[1603, 1523],
       [ 195,  188]])

In [125]:
accuracy_clf_30to40 = (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[1][1]) / (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[0][1] + confusion_matrix_30to40[1][0] + confusion_matrix_30to40[1][1])
accuracy_clf_30to40

0.5104018238814477

In [126]:
# Test on 40to50 subset
clf_pred_40to50 = clf.fit(x_train, y_train).predict(test_40to50)
 
test_df = test_40to50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(clf_pred_40to50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])
 
from sklearn.metrics import confusion_matrix
 
confusion_matrix_40to50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_40to50

array([[ 827, 1168],
       [ 111,  151]])

In [127]:
accuracy_clf_40to50 = (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[1][1]) / (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[0][1] + confusion_matrix_40to50[1][0] + confusion_matrix_40to50[1][1])
accuracy_clf_40to50 

0.43331856446610545

In [128]:
# Test on g50 subset
clf_pred_g50 = clf.fit(x_train, y_train).predict(test_g50)
 
test_df = test_g50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(clf_pred_g50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])
 
from sklearn.metrics import confusion_matrix
 
confusion_matrix_g50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_g50

array([[866, 757],
       [105,  91]])

In [129]:
accuracy_clf_g50 = (confusion_matrix_g50[0][0] + confusion_matrix_g50[1][1]) / (confusion_matrix_g50[0][0] + confusion_matrix_g50[0][1] + confusion_matrix_g50[1][0] + confusion_matrix_g50[1][1])
accuracy_clf_g50 

0.5261132490379329

In [130]:
#Demographic Parity
# positive rate = TP + TN
PR_clf_l30 = confusion_matrix_l30[0,0] +confusion_matrix_l30[1,1]
PR_clf_l30 # 4756

905

In [131]:
PR_clf_30to40 = confusion_matrix_30to40[0,0] +confusion_matrix_30to40[1,1]
PR_clf_30to40 # 2136

1791

In [132]:
PR_clf_40to50 = confusion_matrix_40to50[0,0] +confusion_matrix_40to50[1,1]
PR_clf_40to50 # 2136

978

In [133]:
PR_clf_g50 = confusion_matrix_g50[0,0] +confusion_matrix_g50[1,1]
PR_clf_g50 # 2136

957

In [134]:
# Equalized Opportunity
#TPR = TP/TP+FN

TPR_clf_l30 = confusion_matrix_l30[0,0] / (confusion_matrix_l30[0,0] + confusion_matrix_l30[1,0])

TPR_clf_l30

0.8651115618661258

In [135]:
TPR_clf_30to40 = confusion_matrix_30to40[0,0] / (confusion_matrix_30to40[0,0] + confusion_matrix_30to40[1,0])

TPR_clf_30to40  

0.8915461624026696

In [136]:
TPR_clf_40to50  = confusion_matrix_40to50[0,0] / (confusion_matrix_40to50[0,0] + confusion_matrix_40to50[1,0])

TPR_clf_40to50 

0.8816631130063965

In [137]:
TPR_clf_g50  = confusion_matrix_g50[0,0] / (confusion_matrix_g50[0,0] + confusion_matrix_g50[1,0])

TPR_clf_g50 

0.8918640576725025

In [138]:
# Equalized Odds
#TPR = TP/TP+FN
#FNR = FN/FN+TP


FNR_clf_l30 = confusion_matrix_l30[1,0] / (confusion_matrix_l30[1,0] + confusion_matrix_l30[0,0])

FNR_clf_l30 # 0.11652109273369263

0.13488843813387424

In [139]:
FNR_clf_30to40 = confusion_matrix_30to40[1,0] / (confusion_matrix_30to40[1,0] + confusion_matrix_30to40[0,0])

FNR_clf_30to40

0.10845383759733036

In [140]:
FNR_clf_40to50 = confusion_matrix_40to50[1,0] / (confusion_matrix_40to50[1,0] + confusion_matrix_40to50[0,0])

FNR_clf_40to50

0.11833688699360341

In [141]:
FNR_clf_g50 = confusion_matrix_g50[1,0] / (confusion_matrix_g50[1,0] + confusion_matrix_g50[0,0])

FNR_clf_g50

0.10813594232749743

In [142]:
# Fairness Through Unwareness
x_train_unawareness = x_train.copy()
x_train_unawareness
x_train_unawareness.drop('catAge_<=30', inplace=True, axis=1)
x_train_unawareness.drop('catAge_30-40', inplace=True, axis=1)
x_train_unawareness.drop('catAge_40-50', inplace=True, axis=1)
x_train_unawareness.drop('catAge_>=50', inplace=True, axis=1)

# x_train_unawareness.columns.values
# x_train.columns.values

In [143]:
#Fairness through unawareness

x_test_unawareness = x_test.copy()
x_test_unawareness
x_test_l30 = x_test_unawareness[x_test_unawareness['catAge_<=30'] == 1]
x_test_30to40 = x_test_unawareness[x_test_unawareness['catAge_30-40'] == 1]
x_test_40to50 = x_test_unawareness[x_test_unawareness['catAge_40-50'] == 1]
x_test_g50 = x_test_unawareness[x_test_unawareness['catAge_>=50'] == 1]


x_test_l30.drop('catAge_<=30', inplace=True, axis=1)
x_test_l30.drop('catAge_30-40', inplace=True, axis=1)
x_test_l30.drop('catAge_40-50', inplace=True, axis=1)
x_test_l30.drop('catAge_>=50', inplace=True, axis=1)

x_test_30to40.drop('catAge_<=30', inplace=True, axis=1)
x_test_30to40.drop('catAge_30-40', inplace=True, axis=1)
x_test_30to40.drop('catAge_40-50', inplace=True, axis=1)
x_test_30to40.drop('catAge_>=50', inplace=True, axis=1)

x_test_40to50.drop('catAge_<=30', inplace=True, axis=1)
x_test_40to50.drop('catAge_30-40', inplace=True, axis=1)
x_test_40to50.drop('catAge_40-50', inplace=True, axis=1)
x_test_40to50.drop('catAge_>=50', inplace=True, axis=1)

x_test_g50.drop('catAge_<=30', inplace=True, axis=1)
x_test_g50.drop('catAge_30-40', inplace=True, axis=1)
x_test_g50.drop('catAge_40-50', inplace=True, axis=1)
x_test_g50.drop('catAge_>=50', inplace=True, axis=1)



# x_test_unawareness.columns.values
# x_test.columns.values

In [144]:
# Test on l30 set
clf_pred_l30 = clf.fit(x_train_unawareness, y_train).predict(x_test_l30)

test_df = x_test_l30.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(clf_pred_l30, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_l30 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_l30

array([[834, 405],
       [129,  56]])

In [145]:
accuracy_clf_l30 = (confusion_matrix_l30[0][0] + confusion_matrix_l30[1][1]) / (confusion_matrix_l30[0][0] + confusion_matrix_l30[0][1] + confusion_matrix_l30[1][0] + confusion_matrix_l30[1][1])
accuracy_clf_l30

0.625

In [146]:
# Test on 30to40 set
clf_pred_30to40 = clf.fit(x_train_unawareness, y_train).predict(x_test_30to40)

test_df = x_test_30to40.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(clf_pred_30to40, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_30to40 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_30to40


array([[1587, 1539],
       [ 194,  189]])

In [147]:
accuracy_clf_30to40 = (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[1][1]) / (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[0][1] + confusion_matrix_30to40[1][0] + confusion_matrix_30to40[1][1])
accuracy_clf_30to40 

0.506127101738387

In [148]:
# Test on 40to50 set
clf_pred_40to50 = clf.fit(x_train_unawareness, y_train).predict(x_test_40to50)

test_df = x_test_40to50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(clf_pred_40to50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_40to50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_40to50

array([[ 931, 1064],
       [ 127,  135]])

In [149]:
accuracy_clf_40to50 = (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[1][1]) / (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[0][1] + confusion_matrix_40to50[1][0] + confusion_matrix_40to50[1][1])
accuracy_clf_40to50 # 0.8718606782768102

0.4723083739477182

In [150]:
# Test on g50 set
clf_pred_g50 = clf.fit(x_train_unawareness, y_train).predict(x_test_g50)

test_df = x_test_g50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(clf_pred_g50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_g50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_g50

array([[670, 953],
       [ 86, 110]])

In [151]:
accuracy_clf_g50 = (confusion_matrix_g50[0][0] + confusion_matrix_g50[1][1]) / (confusion_matrix_g50[0][0] + confusion_matrix_g50[0][1] + confusion_matrix_g50[1][0] + confusion_matrix_g50[1][1])
accuracy_clf_g50 # 0.8718606782768102

0.42880703683342497

Linear Regression model

In [152]:
from sklearn import linear_model
linear_regression_model = linear_model.LinearRegression()
linear_regression_model.fit(x_train, y_train)
prediction = linear_regression_model.predict(x_test)

Result

In [153]:
test_df = x_test.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(prediction, index=test_df.index)

test_df['accurate'] = (test_df['pred'] == test_df['biY'])
test_df['pred']

35649    0.128255
41827    0.118935
44974    0.131668
5991     0.115258
6104     0.111872
           ...   
25454    0.133661
26942    0.125148
37275    0.123939
18785    0.121039
14470    0.124035
Name: pred, Length: 9009, dtype: float64