Credit Scoring Fairness Criteria

Load the dataset

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.cm as cm

Load the dataset

In [2]:
import os
BANK_PATH = os.path.join(os.getcwd(), 'ml bank dataset/bankfullclean.csv') # Assign this to the location of the dataset
print(os.getcwd())
print(BANK_PATH)

# 5254 number of rows have 'biY' == 1
# 39787 number of rows have 'biY' == 0


/Users/xinyu/Desktop/senior spring/Independent Study/ML fairness
/Users/xinyu/Desktop/senior spring/Independent Study/ML fairness/ml bank dataset/bankfullclean.csv


In [3]:
bank = pd.read_csv(BANK_PATH)
df = pd.DataFrame(bank)
df.head()
dummy = df[['catAge', 'job', 'marital','education','balance','day', 'month', 'duration', 'campaign', 'pdays', 'previous', 'Fmonth', 'biDefault', 'biHousing', 'biLoan']]
# dummy.columns.values
dummy = pd.get_dummies(data=dummy)
# dummy.head()
dummy.columns.values
# df['marital'].unique()

# df['biY'].replace({0: False, 1: True}, inplace=True)
# print(df['biY'])


array(['balance', 'day', 'duration', 'campaign', 'pdays', 'previous',
       'biDefault', 'biHousing', 'biLoan', 'catAge_30-40', 'catAge_40-50',
       'catAge_<=30', 'catAge_>=50', 'job_admin.', 'job_blue-collar',
       'job_entrepreneur', 'job_housemaid', 'job_management',
       'job_retired', 'job_self-employed', 'job_services', 'job_student',
       'job_technician', 'job_unemployed', 'marital_divorced',
       'marital_married', 'marital_single', 'education_primary',
       'education_secondary', 'education_tertiary', 'month_apr',
       'month_aug', 'month_dec', 'month_feb', 'month_jan', 'month_jul',
       'month_jun', 'month_mar', 'month_may', 'month_nov', 'month_oct',
       'month_sep', 'Fmonth_apr', 'Fmonth_aug', 'Fmonth_dec',
       'Fmonth_feb', 'Fmonth_jan', 'Fmonth_jul', 'Fmonth_jun',
       'Fmonth_mar', 'Fmonth_may', 'Fmonth_nov', 'Fmonth_oct'],
      dtype=object)

Machine Learning Classification Model

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
def get_naive_dataset(dataset):
    dataset = dataset.sample(frac=1).reset_index(drop=True)
    X = dummy
    y = dataset['biY']
    x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
    
    return (x_train, y_train), (x_test, y_test)

In [6]:
(x_train, y_train), (x_test, y_test) = get_naive_dataset(df)

In [7]:
x_train.columns.values

array(['balance', 'day', 'duration', 'campaign', 'pdays', 'previous',
       'biDefault', 'biHousing', 'biLoan', 'catAge_30-40', 'catAge_40-50',
       'catAge_<=30', 'catAge_>=50', 'job_admin.', 'job_blue-collar',
       'job_entrepreneur', 'job_housemaid', 'job_management',
       'job_retired', 'job_self-employed', 'job_services', 'job_student',
       'job_technician', 'job_unemployed', 'marital_divorced',
       'marital_married', 'marital_single', 'education_primary',
       'education_secondary', 'education_tertiary', 'month_apr',
       'month_aug', 'month_dec', 'month_feb', 'month_jan', 'month_jul',
       'month_jun', 'month_mar', 'month_may', 'month_nov', 'month_oct',
       'month_sep', 'Fmonth_apr', 'Fmonth_aug', 'Fmonth_dec',
       'Fmonth_feb', 'Fmonth_jan', 'Fmonth_jul', 'Fmonth_jun',
       'Fmonth_mar', 'Fmonth_may', 'Fmonth_nov', 'Fmonth_oct'],
      dtype=object)

In [8]:
y_train.values

array([1, 1, 0, ..., 0, 0, 0])

In [9]:
x_test.columns.values

array(['balance', 'day', 'duration', 'campaign', 'pdays', 'previous',
       'biDefault', 'biHousing', 'biLoan', 'catAge_30-40', 'catAge_40-50',
       'catAge_<=30', 'catAge_>=50', 'job_admin.', 'job_blue-collar',
       'job_entrepreneur', 'job_housemaid', 'job_management',
       'job_retired', 'job_self-employed', 'job_services', 'job_student',
       'job_technician', 'job_unemployed', 'marital_divorced',
       'marital_married', 'marital_single', 'education_primary',
       'education_secondary', 'education_tertiary', 'month_apr',
       'month_aug', 'month_dec', 'month_feb', 'month_jan', 'month_jul',
       'month_jun', 'month_mar', 'month_may', 'month_nov', 'month_oct',
       'month_sep', 'Fmonth_apr', 'Fmonth_aug', 'Fmonth_dec',
       'Fmonth_feb', 'Fmonth_jan', 'Fmonth_jul', 'Fmonth_jun',
       'Fmonth_mar', 'Fmonth_may', 'Fmonth_nov', 'Fmonth_oct'],
      dtype=object)

In [10]:
y_test.values

array([1, 1, 0, ..., 0, 0, 0])

Naive Bayes Model

In [11]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb_pred = gnb.fit(x_train, y_train).predict(x_test)


Result

In [12]:
test_df = x_test.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(gnb_pred, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])
test_df.columns.values

array(['balance', 'day', 'duration', 'campaign', 'pdays', 'previous',
       'biDefault', 'biHousing', 'biLoan', 'catAge_30-40', 'catAge_40-50',
       'catAge_<=30', 'catAge_>=50', 'job_admin.', 'job_blue-collar',
       'job_entrepreneur', 'job_housemaid', 'job_management',
       'job_retired', 'job_self-employed', 'job_services', 'job_student',
       'job_technician', 'job_unemployed', 'marital_divorced',
       'marital_married', 'marital_single', 'education_primary',
       'education_secondary', 'education_tertiary', 'month_apr',
       'month_aug', 'month_dec', 'month_feb', 'month_jan', 'month_jul',
       'month_jun', 'month_mar', 'month_may', 'month_nov', 'month_oct',
       'month_sep', 'Fmonth_apr', 'Fmonth_aug', 'Fmonth_dec',
       'Fmonth_feb', 'Fmonth_jan', 'Fmonth_jul', 'Fmonth_jun',
       'Fmonth_mar', 'Fmonth_may', 'Fmonth_nov', 'Fmonth_oct', 'biY',
       'pred', 'accurate'], dtype=object)

In [13]:
from sklearn.metrics import confusion_matrix

In [14]:

confusion_matrix = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix

array([[7920,   48],
       [1033,    8]])

In [15]:
# Accuracy
# "Accuracy: ", test_df.accurate.mean()
accuracy_naive_bayes = (confusion_matrix[0][0] + confusion_matrix[1][1]) / (confusion_matrix[0][0] + confusion_matrix[0][1] + confusion_matrix[1][0] + confusion_matrix[1][1])
accuracy_naive_bayes



0.88000888000888

In [16]:
# Split dataset based on marital status
test_df.columns.values
test_married = x_test[x_test['marital_married'] == 1]
test_single = x_test[x_test['marital_single'] == 1]
test_divorced = x_test[x_test['marital_divorced'] == 1]

In [17]:
# Test on single subset
gnb_pred_single = gnb.fit(x_train, y_train).predict(test_single)

test_df = test_single.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(gnb_pred_single, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_single = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_single


array([[2238,   22],
       [ 307,    7]])

In [18]:
accuracy_naive_bayes_single = (confusion_matrix_single[0][0] + confusion_matrix_single[1][1]) / (confusion_matrix_single[0][0] + confusion_matrix_single[0][1] + confusion_matrix_single[1][0] + confusion_matrix_single[1][1])
accuracy_naive_bayes_single

0.8721833721833722

In [19]:
# Test on married subset
gnb_pred_married = gnb.fit(x_train, y_train).predict(test_married)

test_df = test_married.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(gnb_pred_married, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_married = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_married

array([[4784,   24],
       [ 604,    1]])

In [20]:
accuracy_naive_bayes_married = (confusion_matrix_married[0][0] + confusion_matrix_married[1][1]) / (confusion_matrix_married[0][0] + confusion_matrix_married[0][1] + confusion_matrix_married[1][0] + confusion_matrix_married[1][1])
accuracy_naive_bayes_married 

0.8839830038795492

In [21]:
# Test on divorced subset
gnb_pred_divorced = gnb.fit(x_train, y_train).predict(test_divorced)

test_df = test_divorced.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(gnb_pred_divorced, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_divorced = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_divorced

array([[898,   2],
       [122,   0]])

In [22]:
accuracy_naive_bayes_divorced = (confusion_matrix_divorced[0][0] + confusion_matrix_divorced[1][1]) / (confusion_matrix_divorced[0][0] + confusion_matrix_divorced[0][1] + confusion_matrix_divorced[1][0] + confusion_matrix_divorced[1][1])
accuracy_naive_bayes_divorced # 0.8718606782768102

0.8786692759295499

In [23]:
#Demographic Parity
# positive rate = TP + TN
PR_Naive_Bayes_married = confusion_matrix_married[0,0] +confusion_matrix_married[1,1]

PR_Naive_Bayes_married 


4785

In [24]:
PR_Naive_Bayes_single = confusion_matrix_single[0,0] +confusion_matrix_single[1,1]
PR_Naive_Bayes_single 

2245

In [25]:
PR_Naive_Bayes_divorced = confusion_matrix_divorced[0,0] +confusion_matrix_divorced[1,1]
PR_Naive_Bayes_divorced 

898

In [26]:
# Equalized Opportunity
#TPR = TP/TP+FN

TPR_Naive_Bayes_married = confusion_matrix_married[0,0] / (confusion_matrix_married[0,0] + confusion_matrix_married[1,0])

TPR_Naive_Bayes_married 


0.8878990348923533

In [27]:
TPR_Naive_Bayes_single = confusion_matrix_single[0,0] / (confusion_matrix_single[0,0] + confusion_matrix_single[1,0])

TPR_Naive_Bayes_single 

0.8793713163064834

In [28]:
TPR_Naive_Bayes_divorced = confusion_matrix_divorced[0,0] / (confusion_matrix_divorced[0,0] + confusion_matrix_divorced[1,0])

TPR_Naive_Bayes_divorced # 0.8925619834710744

0.8803921568627451

In [29]:
# Equalized Odds
#TPR = TP/TP+FN
#FNR = FN/FN+TP


FNR_Naive_Bayes_married = confusion_matrix_married[1,0] / (confusion_matrix_married[1,0] + confusion_matrix_married[0,0])

FNR_Naive_Bayes_married 



0.11210096510764662

In [30]:
FNR_Naive_Bayes_single = confusion_matrix_single[1,0] / (confusion_matrix_single[1,0] + confusion_matrix_single[0,0])

FNR_Naive_Bayes_single 

0.1206286836935167

In [31]:
FNR_Naive_Bayes_divorced = confusion_matrix_divorced[1,0] / (confusion_matrix_divorced[1,0] + confusion_matrix_divorced[0,0])

FNR_Naive_Bayes_divorced 

0.11960784313725491

In [32]:
# Fairness Through Unwareness
x_train_unawareness = x_train.copy()
x_train_unawareness
x_train_unawareness.drop('marital_married', inplace=True, axis=1)
x_train_unawareness.drop('marital_single', inplace=True, axis=1)
x_train_unawareness.drop('marital_divorced', inplace=True, axis=1)

# x_train_unawareness.columns.values
# x_train.columns.values






In [33]:
#Fairness through unawareness

x_test_unawareness = x_test.copy()
x_test_unawareness
x_test_married = x_test_unawareness[x_test_unawareness['marital_married'] == 1]
x_test_single = x_test_unawareness[x_test_unawareness['marital_single'] == 1]
x_test_divorced = x_test_unawareness[x_test_unawareness['marital_divorced'] == 1]


x_test_married.drop('marital_married', inplace=True, axis=1)
x_test_married.drop('marital_single', inplace=True, axis=1)
x_test_married.drop('marital_divorced', inplace=True, axis=1)

x_test_single.drop('marital_married', inplace=True, axis=1)
x_test_single.drop('marital_single', inplace=True, axis=1)
x_test_single.drop('marital_divorced', inplace=True, axis=1)

x_test_divorced.drop('marital_married', inplace=True, axis=1)
x_test_divorced.drop('marital_single', inplace=True, axis=1)
x_test_divorced.drop('marital_divorced', inplace=True, axis=1)




# x_test_unawareness.columns.values
# x_test.columns.values
# test_married

In [34]:
# Test on single set
gnb_pred_single = gnb.fit(x_train_unawareness, y_train).predict(x_test_single)

test_df = x_test_single.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(gnb_pred_single, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_single = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_single



array([[2240,   20],
       [ 307,    7]])

In [35]:
accuracy_naive_bayes_single = (confusion_matrix_single[0][0] + confusion_matrix_single[1][1]) / (confusion_matrix_single[0][0] + confusion_matrix_single[0][1] + confusion_matrix_single[1][0] + confusion_matrix_single[1][1])
accuracy_naive_bayes_single 

0.872960372960373

In [36]:
# Test on married set
gnb_pred_married = gnb.fit(x_train_unawareness, y_train).predict(x_test_married)

test_df = x_test_married.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(gnb_pred_married, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_married = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_married



array([[4784,   24],
       [ 604,    1]])

In [37]:
accuracy_naive_bayes_married = (confusion_matrix_married[0][0] + confusion_matrix_married[1][1]) / (confusion_matrix_married[0][0] + confusion_matrix_married[0][1] + confusion_matrix_married[1][0] + confusion_matrix_married[1][1])
accuracy_naive_bayes_married 

0.8839830038795492

In [38]:
# Test on divorced set
gnb_pred_divorced = gnb.fit(x_train_unawareness, y_train).predict(x_test_divorced)

test_df = x_test_divorced.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(gnb_pred_divorced, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_divorced = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_divorced

array([[895,   5],
       [121,   1]])

In [39]:
accuracy_naive_bayes_divorced = (confusion_matrix_divorced[0][0] + confusion_matrix_divorced[1][1]) / (confusion_matrix_divorced[0][0] + confusion_matrix_divorced[0][1] + confusion_matrix_divorced[1][0] + confusion_matrix_divorced[1][1])
accuracy_naive_bayes_divorced # 0.8718606782768102

0.8767123287671232

Random Forest Model

In [40]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(max_depth=5, random_state=0, class_weight='balanced')
rf_pred = rf.fit(x_train, y_train).predict(x_test)

In [41]:
test_df = x_test.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(rf_pred, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])
test_df.columns.values

array(['balance', 'day', 'duration', 'campaign', 'pdays', 'previous',
       'biDefault', 'biHousing', 'biLoan', 'catAge_30-40', 'catAge_40-50',
       'catAge_<=30', 'catAge_>=50', 'job_admin.', 'job_blue-collar',
       'job_entrepreneur', 'job_housemaid', 'job_management',
       'job_retired', 'job_self-employed', 'job_services', 'job_student',
       'job_technician', 'job_unemployed', 'marital_divorced',
       'marital_married', 'marital_single', 'education_primary',
       'education_secondary', 'education_tertiary', 'month_apr',
       'month_aug', 'month_dec', 'month_feb', 'month_jan', 'month_jul',
       'month_jun', 'month_mar', 'month_may', 'month_nov', 'month_oct',
       'month_sep', 'Fmonth_apr', 'Fmonth_aug', 'Fmonth_dec',
       'Fmonth_feb', 'Fmonth_jan', 'Fmonth_jul', 'Fmonth_jun',
       'Fmonth_mar', 'Fmonth_may', 'Fmonth_nov', 'Fmonth_oct', 'biY',
       'pred', 'accurate'], dtype=object)

In [42]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix

array([[4957, 3011],
       [ 648,  393]])

In [43]:
# Accuracy
# "Accuracy: ", test_df.accurate.mean()
accuracy_rf = (confusion_matrix[0][0] + confusion_matrix[1][1]) / (confusion_matrix[0][0] + confusion_matrix[0][1] + confusion_matrix[1][0] + confusion_matrix[1][1])
accuracy_rf


0.5938505938505938

In [44]:
# Split dataset based on marital status
test_df.columns.values
test_married = x_test[x_test['marital_married'] == 1]
test_single = x_test[x_test['marital_single'] == 1]
test_divorced = x_test[x_test['marital_divorced'] == 1]

In [45]:
# Test on single subset
rf_pred_single = rf.fit(x_train, y_train).predict(test_single)

test_df = test_single.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(rf_pred_single, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_single = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_single

array([[1295,  965],
       [ 184,  130]])

In [46]:
accuracy_rf_single = (confusion_matrix_single[0][0] + confusion_matrix_single[1][1]) / (confusion_matrix_single[0][0] + confusion_matrix_single[0][1] + confusion_matrix_single[1][0] + confusion_matrix_single[1][1])
accuracy_rf_single

0.5536130536130536

In [47]:
# Test on married subset
rf_pred_married = rf.fit(x_train, y_train).predict(test_married)

test_df = test_married.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(rf_pred_married, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_married = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_married

array([[3063, 1745],
       [ 369,  236]])

In [48]:
accuracy_rf_married = (confusion_matrix_married[0][0] + confusion_matrix_married[1][1]) / (confusion_matrix_married[0][0] + confusion_matrix_married[0][1] + confusion_matrix_married[1][0] + confusion_matrix_married[1][1])
accuracy_rf_married 

0.6094587105117311

In [49]:
# Test on divorced subset
rf_pred_divorced = rf.fit(x_train, y_train).predict(test_divorced)
 
test_df = test_divorced.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(rf_pred_divorced, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])
 
from sklearn.metrics import confusion_matrix
 
confusion_matrix_divorced = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_divorced


array([[599, 301],
       [ 95,  27]])

In [50]:
accuracy_rf_divorced = (confusion_matrix_divorced[0][0] + confusion_matrix_divorced[1][1]) / (confusion_matrix_divorced[0][0] + confusion_matrix_divorced[0][1] + confusion_matrix_divorced[1][0] + confusion_matrix_divorced[1][1])
accuracy_rf_divorced 

0.6125244618395304

In [51]:
#Demographic Parity
# positive rate = TP + TN
PR_rf_married = confusion_matrix_married[0,0] +confusion_matrix_married[1,1]
PR_rf_married # 4756

3299

In [52]:
PR_rf_single = confusion_matrix_single[0,0] +confusion_matrix_single[1,1]
PR_rf_single # 2136

1425

In [53]:
PR_rf_divorced = confusion_matrix_divorced[0,0] +confusion_matrix_divorced[1,1]
PR_rf_divorced # 2136

626

In [54]:
# Equalized Opportunity
#TPR = TP/TP+FN

TPR_rf_married = confusion_matrix_married[0,0] / (confusion_matrix_married[0,0] + confusion_matrix_married[1,0])

TPR_rf_married 

0.8924825174825175

In [55]:
TPR_rf_single = confusion_matrix_single[0,0] / (confusion_matrix_single[0,0] + confusion_matrix_single[1,0])

TPR_rf_single 

0.8755916159567275

In [56]:
TPR_rf_divorced = confusion_matrix_divorced[0,0] / (confusion_matrix_divorced[0,0] + confusion_matrix_divorced[1,0])

TPR_rf_divorced 

0.8631123919308358

In [57]:
# Equalized Odds
#TPR = TP/TP+FN
#FNR = FN/FN+TP


FNR_rf_married = confusion_matrix_married[1,0] / (confusion_matrix_married[1,0] + confusion_matrix_married[0,0])

FNR_rf_married # 0.11652109273369263


0.10751748251748251

In [58]:
FNR_rf_single = confusion_matrix_single[1,0] / (confusion_matrix_single[1,0] + confusion_matrix_single[0,0])

FNR_rf_single 

0.12440838404327248

In [59]:
FNR_rf_divorced = confusion_matrix_divorced[1,0] / (confusion_matrix_divorced[1,0] + confusion_matrix_divorced[0,0])

FNR_rf_divorced 

0.13688760806916425

In [60]:
# Fairness Through Unwareness
x_train_unawareness = x_train.copy()
x_train_unawareness
x_train_unawareness.drop('marital_married', inplace=True, axis=1)
x_train_unawareness.drop('marital_single', inplace=True, axis=1)
x_train_unawareness.drop('marital_divorced', inplace=True, axis=1)

# x_train_unawareness.columns.values
# x_train.columns.values

In [61]:
#Fairness through unawareness

x_test_unawareness = x_test.copy()
x_test_unawareness
x_test_married = x_test_unawareness[x_test_unawareness['marital_married'] == 1]
x_test_single = x_test_unawareness[x_test_unawareness['marital_single'] == 1]
x_test_divorced = x_test_unawareness[x_test_unawareness['marital_divorced'] == 1]


x_test_married.drop('marital_married', inplace=True, axis=1)
x_test_married.drop('marital_single', inplace=True, axis=1)
x_test_married.drop('marital_divorced', inplace=True, axis=1)

x_test_single.drop('marital_married', inplace=True, axis=1)
x_test_single.drop('marital_single', inplace=True, axis=1)
x_test_single.drop('marital_divorced', inplace=True, axis=1)

x_test_divorced.drop('marital_married', inplace=True, axis=1)
x_test_divorced.drop('marital_single', inplace=True, axis=1)
x_test_divorced.drop('marital_divorced', inplace=True, axis=1)


# x_test_unawareness.columns.values
# x_test.columns.values

In [62]:
# Test on single set
rf_pred_single = rf.fit(x_train_unawareness, y_train).predict(x_test_single)

test_df = x_test_single.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(rf_pred_single, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_single = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_single


array([[1307,  953],
       [ 187,  127]])

In [63]:
accuracy_rf_single = (confusion_matrix_single[0][0] + confusion_matrix_single[1][1]) / (confusion_matrix_single[0][0] + confusion_matrix_single[0][1] + confusion_matrix_single[1][0] + confusion_matrix_single[1][1])
accuracy_rf_single 

0.5571095571095571

In [64]:
# Test on married set
rf_pred_married = rf.fit(x_train_unawareness, y_train).predict(x_test_married)

test_df = x_test_married.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(rf_pred_married, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_married = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_married


array([[3065, 1743],
       [ 388,  217]])

In [65]:
accuracy_rf_married = (confusion_matrix_married[0][0] + confusion_matrix_married[1][1]) / (confusion_matrix_married[0][0] + confusion_matrix_married[0][1] + confusion_matrix_married[1][0] + confusion_matrix_married[1][1])
accuracy_rf_married 

0.6063181230371328

In [66]:
# Test on divorced set
rf_pred_divorced = rf.fit(x_train_unawareness, y_train).predict(x_test_divorced)

test_df = x_test_divorced.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(rf_pred_divorced, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_divorced = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_divorced

array([[583, 317],
       [ 87,  35]])

In [67]:
accuracy_rf_divorced = (confusion_matrix_divorced[0][0] + confusion_matrix_divorced[1][1]) / (confusion_matrix_divorced[0][0] + confusion_matrix_divorced[0][1] + confusion_matrix_divorced[1][0] + confusion_matrix_divorced[1][1])
accuracy_rf_divorced # 0.8718606782768102

0.6046966731898239

Support Vector Machine

In [68]:
from sklearn import svm as svm_model
svm = svm_model.SVC(class_weight='balanced') # add class_weight='balanced' is to avoid classifying all data as 0
svm_pred = svm.fit(x_train, y_train).predict(x_test)

In [69]:
test_df = x_test.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(svm_pred, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])
test_df.columns.values

array(['balance', 'day', 'duration', 'campaign', 'pdays', 'previous',
       'biDefault', 'biHousing', 'biLoan', 'catAge_30-40', 'catAge_40-50',
       'catAge_<=30', 'catAge_>=50', 'job_admin.', 'job_blue-collar',
       'job_entrepreneur', 'job_housemaid', 'job_management',
       'job_retired', 'job_self-employed', 'job_services', 'job_student',
       'job_technician', 'job_unemployed', 'marital_divorced',
       'marital_married', 'marital_single', 'education_primary',
       'education_secondary', 'education_tertiary', 'month_apr',
       'month_aug', 'month_dec', 'month_feb', 'month_jan', 'month_jul',
       'month_jun', 'month_mar', 'month_may', 'month_nov', 'month_oct',
       'month_sep', 'Fmonth_apr', 'Fmonth_aug', 'Fmonth_dec',
       'Fmonth_feb', 'Fmonth_jan', 'Fmonth_jul', 'Fmonth_jun',
       'Fmonth_mar', 'Fmonth_may', 'Fmonth_nov', 'Fmonth_oct', 'biY',
       'pred', 'accurate'], dtype=object)

In [70]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix

array([[5243, 2725],
       [ 674,  367]])

In [71]:
# Accuracy
# "Accuracy: ", test_df.accurate.mean()
accuracy_svm = (confusion_matrix[0][0] + confusion_matrix[1][1]) / (confusion_matrix[0][0] + confusion_matrix[0][1] + confusion_matrix[1][0] + confusion_matrix[1][1])
accuracy_svm


0.6227106227106227

In [72]:
# Split dataset based on marital status
test_df.columns.values
test_married = x_test[x_test['marital_married'] == 1]
test_single = x_test[x_test['marital_single'] == 1]
test_divorced = x_test[x_test['marital_divorced'] == 1]

In [73]:
# Test on single subset
svm_pred_single = svm.fit(x_train, y_train).predict(test_single)

test_df = test_single.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(svm_pred_single, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_single = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_single

array([[1508,  752],
       [ 202,  112]])

In [74]:
accuracy_svm_single = (confusion_matrix_single[0][0] + confusion_matrix_single[1][1]) / (confusion_matrix_single[0][0] + confusion_matrix_single[0][1] + confusion_matrix_single[1][0] + confusion_matrix_single[1][1])
accuracy_svm_single

0.6293706293706294

In [75]:
# Test on married subset
svm_pred_married = svm.fit(x_train, y_train).predict(test_married)

test_df = test_married.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(svm_pred_married, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_married = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_married

array([[3114, 1694],
       [ 394,  211]])

In [76]:
accuracy_svm_married = (confusion_matrix_married[0][0] + confusion_matrix_married[1][1]) / (confusion_matrix_married[0][0] + confusion_matrix_married[0][1] + confusion_matrix_married[1][0] + confusion_matrix_married[1][1])
accuracy_svm_married # 0.8718606782768102

0.6142619619434694

In [77]:
# Test on divorced subset
svm_pred_divorced = svm.fit(x_train, y_train).predict(test_divorced)

test_df = test_divorced.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(svm_pred_divorced, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_divorced = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_divorced

array([[621, 279],
       [ 78,  44]])

In [78]:
accuracy_svm_divorced = (confusion_matrix_divorced[0][0] + confusion_matrix_divorced[1][1]) / (confusion_matrix_divorced[0][0] + confusion_matrix_divorced[0][1] + confusion_matrix_divorced[1][0] + confusion_matrix_divorced[1][1])
accuracy_svm_divorced # 0.8718606782768102

0.6506849315068494

In [79]:
#Demographic Parity
# positive rate = TP + TN
PR_svm_married = confusion_matrix_married[0,0] +confusion_matrix_married[1,1]

PR_svm_married

3325

In [80]:
PR_svm_single = confusion_matrix_single[0,0] +confusion_matrix_single[1,1]
PR_svm_single

1620

In [81]:
PR_svm_divorced = confusion_matrix_divorced[0,0] +confusion_matrix_divorced[1,1]
PR_svm_divorced 

665

In [82]:
# Equalized Opportunity
#TPR = TP/TP+FN

TPR_svm_married = confusion_matrix_married[0,0] / (confusion_matrix_married[0,0] + confusion_matrix_married[1,0])

TPR_svm_married 

0.8876852907639681

In [83]:
TPR_svm_single = confusion_matrix_single[0,0] / (confusion_matrix_single[0,0] + confusion_matrix_single[1,0])

TPR_svm_single 

0.8818713450292398

In [84]:
TPR_svm_divorced = confusion_matrix_divorced[0,0] / (confusion_matrix_divorced[0,0] + confusion_matrix_divorced[1,0])

TPR_svm_divorced 

0.8884120171673819

In [85]:
# Equalized Odds
#TPR = TP/TP+FN
#FNR = FN/FN+TP


FNR_svm_married = confusion_matrix_married[1,0] / (confusion_matrix_married[1,0] + confusion_matrix_married[0,0])

FNR_svm_married

0.11231470923603193

In [86]:
FNR_svm_single = confusion_matrix_single[1,0] / (confusion_matrix_single[1,0] + confusion_matrix_single[0,0])

FNR_svm_single 

0.11812865497076024

In [87]:
FNR_svm_divorced = confusion_matrix_divorced[1,0] / (confusion_matrix_divorced[1,0] + confusion_matrix_divorced[0,0])

FNR_svm_divorced 

0.11158798283261803

In [88]:
# Fairness Through Unwareness
x_train_unawareness = x_train.copy()
x_train_unawareness
x_train_unawareness.drop('marital_married', inplace=True, axis=1)
x_train_unawareness.drop('marital_single', inplace=True, axis=1)
x_train_unawareness.drop('marital_divorced', inplace=True, axis=1)

# x_train_unawareness.columns.values
# x_train.columns.values

In [89]:
#Fairness through unawareness

x_test_unawareness = x_test.copy()
x_test_unawareness
x_test_married = x_test_unawareness[x_test_unawareness['marital_married'] == 1]
x_test_single = x_test_unawareness[x_test_unawareness['marital_single'] == 1]
x_test_divorced = x_test_unawareness[x_test_unawareness['marital_divorced'] == 1]


x_test_married.drop('marital_married', inplace=True, axis=1)
x_test_married.drop('marital_single', inplace=True, axis=1)
x_test_married.drop('marital_divorced', inplace=True, axis=1)

x_test_single.drop('marital_married', inplace=True, axis=1)
x_test_single.drop('marital_single', inplace=True, axis=1)
x_test_single.drop('marital_divorced', inplace=True, axis=1)

x_test_divorced.drop('marital_married', inplace=True, axis=1)
x_test_divorced.drop('marital_single', inplace=True, axis=1)
x_test_divorced.drop('marital_divorced', inplace=True, axis=1)



In [90]:
# Test on single set
svm_pred_single = svm.fit(x_train_unawareness, y_train).predict(x_test_single)

test_df = x_test_single.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(svm_pred_single, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_single = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_single


array([[1508,  752],
       [ 202,  112]])

In [91]:
accuracy_svm_single = (confusion_matrix_single[0][0] + confusion_matrix_single[1][1]) / (confusion_matrix_single[0][0] + confusion_matrix_single[0][1] + confusion_matrix_single[1][0] + confusion_matrix_single[1][1])
accuracy_svm_single

0.6293706293706294

In [92]:
# Test on married set
svm_pred_married = svm.fit(x_train_unawareness, y_train).predict(x_test_married)

test_df = x_test_married.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(svm_pred_married, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_married = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_married

array([[3114, 1694],
       [ 394,  211]])

In [93]:
accuracy_svm_married = (confusion_matrix_married[0][0] + confusion_matrix_married[1][1]) / (confusion_matrix_married[0][0] + confusion_matrix_married[0][1] + confusion_matrix_married[1][0] + confusion_matrix_married[1][1])
accuracy_svm_married # 0.8718606782768102

0.6142619619434694

In [94]:
# Test on divorced subset
svm_pred_divorced = svm.fit(x_train_unawareness, y_train).predict(x_test_divorced)

test_df = x_test_divorced.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(svm_pred_divorced, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_divorced = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_divorced

array([[621, 279],
       [ 78,  44]])

In [95]:
accuracy_svm_divorced = (confusion_matrix_divorced[0][0] + confusion_matrix_divorced[1][1]) / (confusion_matrix_divorced[0][0] + confusion_matrix_divorced[0][1] + confusion_matrix_divorced[1][0] + confusion_matrix_divorced[1][1])
accuracy_svm_divorced 

0.6506849315068494

Logistic Regression Model

In [96]:
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(random_state=0, class_weight='balanced')
clf_pred = clf.fit(x_train, y_train).predict(x_test)

In [97]:
test_df = x_test.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(clf_pred, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])
test_df.columns.values

array(['balance', 'day', 'duration', 'campaign', 'pdays', 'previous',
       'biDefault', 'biHousing', 'biLoan', 'catAge_30-40', 'catAge_40-50',
       'catAge_<=30', 'catAge_>=50', 'job_admin.', 'job_blue-collar',
       'job_entrepreneur', 'job_housemaid', 'job_management',
       'job_retired', 'job_self-employed', 'job_services', 'job_student',
       'job_technician', 'job_unemployed', 'marital_divorced',
       'marital_married', 'marital_single', 'education_primary',
       'education_secondary', 'education_tertiary', 'month_apr',
       'month_aug', 'month_dec', 'month_feb', 'month_jan', 'month_jul',
       'month_jun', 'month_mar', 'month_may', 'month_nov', 'month_oct',
       'month_sep', 'Fmonth_apr', 'Fmonth_aug', 'Fmonth_dec',
       'Fmonth_feb', 'Fmonth_jan', 'Fmonth_jul', 'Fmonth_jun',
       'Fmonth_mar', 'Fmonth_may', 'Fmonth_nov', 'Fmonth_oct', 'biY',
       'pred', 'accurate'], dtype=object)

In [98]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix

array([[4363, 3605],
       [ 578,  463]])

In [99]:
# Accuracy
# "Accuracy: ", test_df.accurate.mean()
accuracy_clf = (confusion_matrix[0][0] + confusion_matrix[1][1]) / (confusion_matrix[0][0] + confusion_matrix[0][1] + confusion_matrix[1][0] + confusion_matrix[1][1])
accuracy_clf


0.5356865356865357

In [100]:
# Split dataset based on marital status
test_df.columns.values
test_married = x_test[x_test['marital_married'] == 1]
test_single = x_test[x_test['marital_single'] == 1]
test_divorced = x_test[x_test['marital_divorced'] == 1]

In [101]:
# Test on single subset
clf_pred_single = clf.fit(x_train, y_train).predict(test_single)

test_df = test_single.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(clf_pred_single, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_single = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_single

array([[1085, 1175],
       [ 153,  161]])

In [102]:
accuracy_clf_single = (confusion_matrix_single[0][0] + confusion_matrix_single[1][1]) / (confusion_matrix_single[0][0] + confusion_matrix_single[0][1] + confusion_matrix_single[1][0] + confusion_matrix_single[1][1])
accuracy_clf_single

0.4840714840714841

In [103]:
# Test on married subset
clf_pred_married = clf.fit(x_train, y_train).predict(test_married)

test_df = test_married.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(clf_pred_married, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_married = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_married

array([[2740, 2068],
       [ 344,  261]])

In [104]:
accuracy_clf_married = (confusion_matrix_married[0][0] + confusion_matrix_married[1][1]) / (confusion_matrix_married[0][0] + confusion_matrix_married[0][1] + confusion_matrix_married[1][0] + confusion_matrix_married[1][1])
accuracy_clf_married 

0.5544060594864216

In [105]:
# Test on divorced subset
clf_pred_divorced = clf.fit(x_train, y_train).predict(test_divorced)
 
test_df = test_divorced.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(clf_pred_divorced, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])
 
from sklearn.metrics import confusion_matrix
 
confusion_matrix_divorced = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_divorced


array([[538, 362],
       [ 81,  41]])

In [106]:
accuracy_clf_divorced = (confusion_matrix_divorced[0][0] + confusion_matrix_divorced[1][1]) / (confusion_matrix_divorced[0][0] + confusion_matrix_divorced[0][1] + confusion_matrix_divorced[1][0] + confusion_matrix_divorced[1][1])
accuracy_clf_divorced 

0.5665362035225049

In [107]:
#Demographic Parity
# positive rate = TP + TN
PR_clf_married = confusion_matrix_married[0,0] +confusion_matrix_married[1,1]
PR_clf_married # 4756

3001

In [108]:
PR_clf_single = confusion_matrix_single[0,0] +confusion_matrix_single[1,1]
PR_clf_single # 2136

1246

In [109]:
PR_clf_divorced = confusion_matrix_divorced[0,0] +confusion_matrix_divorced[1,1]
PR_clf_divorced # 2136

579

In [110]:
# Equalized Opportunity
#TPR = TP/TP+FN

TPR_clf_married = confusion_matrix_married[0,0] / (confusion_matrix_married[0,0] + confusion_matrix_married[1,0])

TPR_clf_married 

0.8884565499351491

In [111]:
TPR_clf_single = confusion_matrix_single[0,0] / (confusion_matrix_single[0,0] + confusion_matrix_single[1,0])

TPR_clf_single 

0.8764135702746365

In [112]:
TPR_clf_divorced = confusion_matrix_divorced[0,0] / (confusion_matrix_divorced[0,0] + confusion_matrix_divorced[1,0])

TPR_clf_divorced 

0.8691437802907916

In [113]:
# Equalized Odds
#TPR = TP/TP+FN
#FNR = FN/FN+TP


FNR_clf_married = confusion_matrix_married[1,0] / (confusion_matrix_married[1,0] + confusion_matrix_married[0,0])

FNR_clf_married # 0.11652109273369263

0.11154345006485085

In [114]:
FNR_clf_single = confusion_matrix_single[1,0] / (confusion_matrix_single[1,0] + confusion_matrix_single[0,0])

FNR_clf_single 

0.12358642972536349

In [115]:
FNR_clf_divorced = confusion_matrix_divorced[1,0] / (confusion_matrix_divorced[1,0] + confusion_matrix_divorced[0,0])

FNR_clf_divorced 

0.1308562197092084

In [116]:
# Fairness Through Unwareness
x_train_unawareness = x_train.copy()
x_train_unawareness
x_train_unawareness.drop('marital_married', inplace=True, axis=1)
x_train_unawareness.drop('marital_single', inplace=True, axis=1)
x_train_unawareness.drop('marital_divorced', inplace=True, axis=1)

# x_train_unawareness.columns.values
# x_train.columns.values

In [117]:
#Fairness through unawareness

x_test_unawareness = x_test.copy()
x_test_unawareness
x_test_married = x_test_unawareness[x_test_unawareness['marital_married'] == 1]
x_test_single = x_test_unawareness[x_test_unawareness['marital_single'] == 1]
x_test_divorced = x_test_unawareness[x_test_unawareness['marital_divorced'] == 1]


x_test_married.drop('marital_married', inplace=True, axis=1)
x_test_married.drop('marital_single', inplace=True, axis=1)
x_test_married.drop('marital_divorced', inplace=True, axis=1)

x_test_single.drop('marital_married', inplace=True, axis=1)
x_test_single.drop('marital_single', inplace=True, axis=1)
x_test_single.drop('marital_divorced', inplace=True, axis=1)

x_test_divorced.drop('marital_married', inplace=True, axis=1)
x_test_divorced.drop('marital_single', inplace=True, axis=1)
x_test_divorced.drop('marital_divorced', inplace=True, axis=1)


# x_test_unawareness.columns.values
# x_test.columns.values

In [118]:
# Test on single set
clf_pred_single = clf.fit(x_train_unawareness, y_train).predict(x_test_single)

test_df = x_test_single.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(clf_pred_single, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_single = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_single

array([[1166, 1094],
       [ 161,  153]])

In [119]:
accuracy_clf_single = (confusion_matrix_single[0][0] + confusion_matrix_single[1][1]) / (confusion_matrix_single[0][0] + confusion_matrix_single[0][1] + confusion_matrix_single[1][0] + confusion_matrix_single[1][1])
accuracy_clf_single 

0.5124320124320124

In [120]:
# Test on married set
clf_pred_married = rf.fit(x_train_unawareness, y_train).predict(x_test_married)

test_df = x_test_married.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(clf_pred_married, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_married = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_married


array([[3065, 1743],
       [ 388,  217]])

In [121]:
accuracy_clf_married = (confusion_matrix_married[0][0] + confusion_matrix_married[1][1]) / (confusion_matrix_married[0][0] + confusion_matrix_married[0][1] + confusion_matrix_married[1][0] + confusion_matrix_married[1][1])
accuracy_clf_married 

0.6063181230371328

In [122]:
# Test on divorced set
clf_pred_divorced = clf.fit(x_train_unawareness, y_train).predict(x_test_divorced)

test_df = x_test_divorced.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(clf_pred_divorced, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_divorced = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_divorced

array([[461, 439],
       [ 71,  51]])

In [123]:
accuracy_clf_divorced = (confusion_matrix_divorced[0][0] + confusion_matrix_divorced[1][1]) / (confusion_matrix_divorced[0][0] + confusion_matrix_divorced[0][1] + confusion_matrix_divorced[1][0] + confusion_matrix_divorced[1][1])
accuracy_clf_divorced # 0.8718606782768102

0.5009784735812133

Linear Regression model

In [124]:
from sklearn import linear_model
linear_regression_model = linear_model.LinearRegression()
linear_regression_model.fit(x_train, y_train)
prediction = linear_regression_model.predict(x_test)

Result

In [125]:
test_df = x_test.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(prediction, index=test_df.index)

test_df['accurate'] = (test_df['pred'] == test_df['biY'])
test_df['pred']

11879    0.111887
5653     0.111763
11198    0.126075
3957     0.111495
3762     0.112426
           ...   
42560    0.113807
44451    0.127561
9787     0.114586
10850    0.122021
16015    0.119516
Name: pred, Length: 9009, dtype: float64