Credit Scoring Fairness Criteria

Load the dataset

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.cm as cm

Load the dataset

In [2]:
import os
BANK_PATH = os.path.join(os.getcwd(), 'ML fairness/ml bank dataset/bankfullclean.csv') # Assign this to the location of the dataset
print(os.getcwd())
print(BANK_PATH)

# 5254 number of rows have 'biY' == 1
# 39787 number of rows have 'biY' == 0


/Users/xinyu/Desktop/Research/Machine-Learning-Fairness--main
/Users/xinyu/Desktop/Research/Machine-Learning-Fairness--main/ML fairness/ml bank dataset/bankfullclean.csv


In [3]:
bank = pd.read_csv(BANK_PATH)
df = pd.DataFrame(bank)
df.head()
dummy = df[['catAge', 'job', 'marital','education','balance','day', 'month', 'duration', 'campaign', 'pdays', 'previous', 'Fmonth', 'biDefault', 'biHousing', 'biLoan']]
# dummy.columns.values
dummy = pd.get_dummies(data=dummy)
# dummy.head()
dummy.columns.values
# df['marital'].unique()

# df['biY'].replace({0: False, 1: True}, inplace=True)
# print(df['biY'])


array(['balance', 'day', 'duration', 'campaign', 'pdays', 'previous',
       'biDefault', 'biHousing', 'biLoan', 'catAge_30-40', 'catAge_40-50',
       'catAge_<=30', 'catAge_>=50', 'job_admin.', 'job_blue-collar',
       'job_entrepreneur', 'job_housemaid', 'job_management',
       'job_retired', 'job_self-employed', 'job_services', 'job_student',
       'job_technician', 'job_unemployed', 'marital_divorced',
       'marital_married', 'marital_single', 'education_primary',
       'education_secondary', 'education_tertiary', 'month_apr',
       'month_aug', 'month_dec', 'month_feb', 'month_jan', 'month_jul',
       'month_jun', 'month_mar', 'month_may', 'month_nov', 'month_oct',
       'month_sep', 'Fmonth_apr', 'Fmonth_aug', 'Fmonth_dec',
       'Fmonth_feb', 'Fmonth_jan', 'Fmonth_jul', 'Fmonth_jun',
       'Fmonth_mar', 'Fmonth_may', 'Fmonth_nov', 'Fmonth_oct'],
      dtype=object)

Machine Learning Classification Model

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import LeaveOneOut

In [5]:
def get_naive_dataset(dataset):
    dataset = dataset.sample(frac=1).reset_index(drop=True)
    X = dummy
    y = dataset['biY']
    x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
    
    return (x_train, y_train), (x_test, y_test)

In [6]:
(x_train, y_train), (x_test, y_test) = get_naive_dataset(df)

In [7]:
x_train.columns.values

array(['balance', 'day', 'duration', 'campaign', 'pdays', 'previous',
       'biDefault', 'biHousing', 'biLoan', 'catAge_30-40', 'catAge_40-50',
       'catAge_<=30', 'catAge_>=50', 'job_admin.', 'job_blue-collar',
       'job_entrepreneur', 'job_housemaid', 'job_management',
       'job_retired', 'job_self-employed', 'job_services', 'job_student',
       'job_technician', 'job_unemployed', 'marital_divorced',
       'marital_married', 'marital_single', 'education_primary',
       'education_secondary', 'education_tertiary', 'month_apr',
       'month_aug', 'month_dec', 'month_feb', 'month_jan', 'month_jul',
       'month_jun', 'month_mar', 'month_may', 'month_nov', 'month_oct',
       'month_sep', 'Fmonth_apr', 'Fmonth_aug', 'Fmonth_dec',
       'Fmonth_feb', 'Fmonth_jan', 'Fmonth_jul', 'Fmonth_jun',
       'Fmonth_mar', 'Fmonth_may', 'Fmonth_nov', 'Fmonth_oct'],
      dtype=object)

In [8]:
y_train.values

array([0, 0, 0, ..., 0, 0, 0])

In [9]:
x_test.columns.values

array(['balance', 'day', 'duration', 'campaign', 'pdays', 'previous',
       'biDefault', 'biHousing', 'biLoan', 'catAge_30-40', 'catAge_40-50',
       'catAge_<=30', 'catAge_>=50', 'job_admin.', 'job_blue-collar',
       'job_entrepreneur', 'job_housemaid', 'job_management',
       'job_retired', 'job_self-employed', 'job_services', 'job_student',
       'job_technician', 'job_unemployed', 'marital_divorced',
       'marital_married', 'marital_single', 'education_primary',
       'education_secondary', 'education_tertiary', 'month_apr',
       'month_aug', 'month_dec', 'month_feb', 'month_jan', 'month_jul',
       'month_jun', 'month_mar', 'month_may', 'month_nov', 'month_oct',
       'month_sep', 'Fmonth_apr', 'Fmonth_aug', 'Fmonth_dec',
       'Fmonth_feb', 'Fmonth_jan', 'Fmonth_jul', 'Fmonth_jun',
       'Fmonth_mar', 'Fmonth_may', 'Fmonth_nov', 'Fmonth_oct'],
      dtype=object)

In [10]:
y_test.values

array([0, 0, 0, ..., 0, 0, 0])

Naive Bayes Model

In [11]:
%%time
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb_pred = gnb.fit(x_train, y_train).predict(x_test)

CPU times: user 148 ms, sys: 78.1 ms, total: 226 ms
Wall time: 487 ms


Result

In [12]:
test_df = x_test.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(gnb_pred, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])
test_df.columns.values

array(['balance', 'day', 'duration', 'campaign', 'pdays', 'previous',
       'biDefault', 'biHousing', 'biLoan', 'catAge_30-40', 'catAge_40-50',
       'catAge_<=30', 'catAge_>=50', 'job_admin.', 'job_blue-collar',
       'job_entrepreneur', 'job_housemaid', 'job_management',
       'job_retired', 'job_self-employed', 'job_services', 'job_student',
       'job_technician', 'job_unemployed', 'marital_divorced',
       'marital_married', 'marital_single', 'education_primary',
       'education_secondary', 'education_tertiary', 'month_apr',
       'month_aug', 'month_dec', 'month_feb', 'month_jan', 'month_jul',
       'month_jun', 'month_mar', 'month_may', 'month_nov', 'month_oct',
       'month_sep', 'Fmonth_apr', 'Fmonth_aug', 'Fmonth_dec',
       'Fmonth_feb', 'Fmonth_jan', 'Fmonth_jul', 'Fmonth_jun',
       'Fmonth_mar', 'Fmonth_may', 'Fmonth_nov', 'Fmonth_oct', 'biY',
       'pred', 'accurate'], dtype=object)

In [13]:
from sklearn.metrics import confusion_matrix

In [14]:

confusion_matrix = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix

array([[7539,  407],
       [ 993,   70]])

In [15]:
# Accuracy
# "Accuracy: ", test_df.accurate.mean()
accuracy_naive_bayes = (confusion_matrix[0][0] + confusion_matrix[1][1]) / (confusion_matrix[0][0] + confusion_matrix[0][1] + confusion_matrix[1][0] + confusion_matrix[1][1])
accuracy_naive_bayes



0.8445998445998446

In [16]:
# Split dataset based on marital status
test_df.columns.values
test_l30 = x_test[x_test['catAge_<=30'] == 1]
test_30to40 = x_test[x_test['catAge_30-40'] == 1]
test_40to50 = x_test[x_test['catAge_40-50'] == 1]
test_g50 = x_test[x_test['catAge_>=50'] == 1]

In [17]:
# Test on l30 subset
gnb_pred_l30 = gnb.fit(x_train, y_train).predict(test_l30)

test_df = test_l30.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(gnb_pred_l30, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_l30 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_l30


array([[1120,  107],
       [ 148,   19]])

In [18]:
accuracy_naive_bayes_l30 = (confusion_matrix_l30[0][0] + confusion_matrix_l30[1][1]) / (confusion_matrix_l30[0][0] + confusion_matrix_l30[0][1] + confusion_matrix_l30[1][0] + confusion_matrix_l30[1][1])
accuracy_naive_bayes_l30

0.8170731707317073

In [19]:
# Test on 30to40 subset
gnb_pred_30to40 = gnb.fit(x_train, y_train).predict(test_30to40)

test_df = test_30to40.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(gnb_pred_30to40, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_30to40 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_30to40

array([[2973,  142],
       [ 419,   26]])

In [20]:
accuracy_naive_bayes_30to40 = (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[1][1]) / (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[0][1] + confusion_matrix_30to40[1][0] + confusion_matrix_30to40[1][1])
accuracy_naive_bayes_30to40

0.8424157303370786

In [21]:
# Test on 40to50 subset
gnb_pred_40to50 = gnb.fit(x_train, y_train).predict(test_40to50)

test_df = test_40to50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(gnb_pred_40to50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_40to50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_40to50

array([[1918,   84],
       [ 229,   13]])

In [22]:
accuracy_naive_bayes_40to50 = (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[1][1]) / (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[0][1] + confusion_matrix_40to50[1][0] + confusion_matrix_40to50[1][1])
accuracy_naive_bayes_40to50 # 0.8718606782768102

0.8605169340463458

In [23]:
# Test on g50 subset
gnb_pred_g50 = gnb.fit(x_train, y_train).predict(test_g50)

test_df = test_g50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(gnb_pred_g50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_g50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_g50

array([[1528,   74],
       [ 197,   12]])

In [24]:
accuracy_naive_bayes_g50 = (confusion_matrix_g50[0][0] + confusion_matrix_g50[1][1]) / (confusion_matrix_g50[0][0] + confusion_matrix_g50[0][1] + confusion_matrix_g50[1][0] + confusion_matrix_g50[1][1])
accuracy_naive_bayes_g50 # 0.8718606782768102

0.8503589177250138

In [25]:
#Demographic Parity
# positive rate = TP + TN
PR_Naive_Bayes_l30 = confusion_matrix_l30[0,0] +confusion_matrix_l30[1,1]

PR_Naive_Bayes_l30 


1139

In [26]:
PR_Naive_Bayes_30to40 = confusion_matrix_30to40[0,0] +confusion_matrix_30to40[1,1]
PR_Naive_Bayes_30to40

2999

In [27]:
PR_Naive_Bayes_40to50 = confusion_matrix_40to50[0,0] +confusion_matrix_40to50[1,1]
PR_Naive_Bayes_40to50 

1931

In [28]:
PR_Naive_Bayes_g50 = confusion_matrix_g50[0,0] +confusion_matrix_g50[1,1]
PR_Naive_Bayes_g50 

1540

In [29]:
# Equalized Opportunity
#TPR = TP/TP+FN

TPR_Naive_Bayes_l30 = confusion_matrix_l30[0,0] / (confusion_matrix_l30[0,0] + confusion_matrix_l30[1,0])

TPR_Naive_Bayes_l30


0.8832807570977917

In [30]:
TPR_Naive_Bayes_30to40 = confusion_matrix_30to40[0,0] / (confusion_matrix_30to40[0,0] + confusion_matrix_30to40[1,0])

TPR_Naive_Bayes_30to40

0.8764740566037735

In [31]:
TPR_Naive_Bayes_40to50 = confusion_matrix_40to50[0,0] / (confusion_matrix_40to50[0,0] + confusion_matrix_40to50[1,0])

TPR_Naive_Bayes_40to50 

0.8933395435491384

In [32]:
TPR_Naive_Bayes_g50 = confusion_matrix_g50[0,0] / (confusion_matrix_g50[0,0] + confusion_matrix_g50[1,0])

TPR_Naive_Bayes_g50 # 0.8925619834710744

0.8857971014492754

In [33]:
# Equalized Odds
#TPR = TP/TP+FN
#FNR = FN/FN+TP


FNR_Naive_Bayes_l30 = confusion_matrix_l30[1,0] / (confusion_matrix_l30[1,0] + confusion_matrix_l30[0,0])

FNR_Naive_Bayes_l30



0.1167192429022082

In [34]:
FNR_Naive_Bayes_30to40 = confusion_matrix_30to40[1,0] / (confusion_matrix_30to40[1,0] + confusion_matrix_30to40[0,0])

FNR_Naive_Bayes_30to40

0.12352594339622641

In [35]:
FNR_Naive_Bayes_40to50 = confusion_matrix_40to50[1,0] / (confusion_matrix_40to50[1,0] + confusion_matrix_40to50[0,0])

FNR_Naive_Bayes_40to50

0.10666045645086167

In [36]:
FNR_Naive_Bayes_g50 = confusion_matrix_g50[1,0] / (confusion_matrix_g50[1,0] + confusion_matrix_g50[0,0])

FNR_Naive_Bayes_g50

0.11420289855072464

In [37]:
# Fairness Through Unwareness
x_train_unawareness = x_train.copy()
x_train_unawareness
x_train_unawareness.drop('catAge_<=30', inplace=True, axis=1)
x_train_unawareness.drop('catAge_30-40', inplace=True, axis=1)
x_train_unawareness.drop('catAge_40-50', inplace=True, axis=1)
x_train_unawareness.drop('catAge_>=50', inplace=True, axis=1)

# x_train_unawareness.columns.values
# x_train.columns.values






In [38]:
#Fairness through unawareness

x_test_unawareness = x_test.copy()
x_test_unawareness
x_test_l30 = x_test_unawareness[x_test_unawareness['catAge_<=30'] == 1]
x_test_30to40 = x_test_unawareness[x_test_unawareness['catAge_30-40'] == 1]
x_test_40to50 = x_test_unawareness[x_test_unawareness['catAge_40-50'] == 1]
x_test_g50 = x_test_unawareness[x_test_unawareness['catAge_>=50'] == 1]


x_test_l30.drop('catAge_<=30', inplace=True, axis=1)
x_test_l30.drop('catAge_30-40', inplace=True, axis=1)
x_test_l30.drop('catAge_40-50', inplace=True, axis=1)
x_test_l30.drop('catAge_>=50', inplace=True, axis=1)

x_test_30to40.drop('catAge_<=30', inplace=True, axis=1)
x_test_30to40.drop('catAge_30-40', inplace=True, axis=1)
x_test_30to40.drop('catAge_40-50', inplace=True, axis=1)
x_test_30to40.drop('catAge_>=50', inplace=True, axis=1)

x_test_40to50.drop('catAge_<=30', inplace=True, axis=1)
x_test_40to50.drop('catAge_30-40', inplace=True, axis=1)
x_test_40to50.drop('catAge_40-50', inplace=True, axis=1)
x_test_40to50.drop('catAge_>=50', inplace=True, axis=1)

x_test_g50.drop('catAge_<=30', inplace=True, axis=1)
x_test_g50.drop('catAge_30-40', inplace=True, axis=1)
x_test_g50.drop('catAge_40-50', inplace=True, axis=1)
x_test_g50.drop('catAge_>=50', inplace=True, axis=1)




# x_test_unawareness.columns.values
# x_test.columns.values
# test_married

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/core/frame.py:4163: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


In [39]:
# Test on l30 set
gnb_pred_l30 = gnb.fit(x_train_unawareness, y_train).predict(x_test_l30)

test_df = x_test_l30.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(gnb_pred_l30, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_l30 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_l30



array([[1120,  107],
       [ 148,   19]])

In [40]:
accuracy_naive_bayes_l30 = (confusion_matrix_l30[0][0] + confusion_matrix_l30[1][1]) / (confusion_matrix_l30[0][0] + confusion_matrix_l30[0][1] + confusion_matrix_l30[1][0] + confusion_matrix_l30[1][1])
accuracy_naive_bayes_l30 

0.8170731707317073

In [41]:
# Test on 30to40 set
gnb_pred_30to40 = gnb.fit(x_train_unawareness, y_train).predict(x_test_30to40)

test_df = x_test_30to40.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(gnb_pred_30to40, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_30to40 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_30to40



array([[2973,  142],
       [ 419,   26]])

In [42]:
accuracy_naive_bayes_30to40 = (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[1][1]) / (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[0][1] + confusion_matrix_30to40[1][0] + confusion_matrix_30to40[1][1])
accuracy_naive_bayes_30to40 

0.8424157303370786

In [43]:
# Test on 40to50 set
gnb_pred_40to50 = gnb.fit(x_train_unawareness, y_train).predict(x_test_40to50)

test_df = x_test_40to50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(gnb_pred_40to50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_40to50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_40to50

array([[1918,   84],
       [ 229,   13]])

In [44]:
accuracy_naive_bayes_40to50 = (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[1][1]) / (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[0][1] + confusion_matrix_40to50[1][0] + confusion_matrix_40to50[1][1])
accuracy_naive_bayes_40to50 # 0.8718606782768102

0.8605169340463458

In [45]:
# Test on g50 set
gnb_pred_g50 = gnb.fit(x_train_unawareness, y_train).predict(x_test_g50)

test_df = x_test_g50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(gnb_pred_g50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_g50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_g50

array([[1528,   74],
       [ 197,   12]])

In [46]:
accuracy_naive_bayes_g50 = (confusion_matrix_g50[0][0] + confusion_matrix_g50[1][1]) / (confusion_matrix_g50[0][0] + confusion_matrix_g50[0][1] + confusion_matrix_g50[1][0] + confusion_matrix_g50[1][1])
accuracy_naive_bayes_g50 # 0.8718606782768102

0.8503589177250138

Random Forest Model

In [47]:
%%time
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(max_depth=5, random_state=0, class_weight='balanced')
rf_pred = rf.fit(x_train, y_train).predict(x_test)

CPU times: user 5.07 s, sys: 228 ms, total: 5.29 s
Wall time: 9.52 s


In [48]:
test_df = x_test.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(rf_pred, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])
test_df.columns.values

array(['balance', 'day', 'duration', 'campaign', 'pdays', 'previous',
       'biDefault', 'biHousing', 'biLoan', 'catAge_30-40', 'catAge_40-50',
       'catAge_<=30', 'catAge_>=50', 'job_admin.', 'job_blue-collar',
       'job_entrepreneur', 'job_housemaid', 'job_management',
       'job_retired', 'job_self-employed', 'job_services', 'job_student',
       'job_technician', 'job_unemployed', 'marital_divorced',
       'marital_married', 'marital_single', 'education_primary',
       'education_secondary', 'education_tertiary', 'month_apr',
       'month_aug', 'month_dec', 'month_feb', 'month_jan', 'month_jul',
       'month_jun', 'month_mar', 'month_may', 'month_nov', 'month_oct',
       'month_sep', 'Fmonth_apr', 'Fmonth_aug', 'Fmonth_dec',
       'Fmonth_feb', 'Fmonth_jan', 'Fmonth_jul', 'Fmonth_jun',
       'Fmonth_mar', 'Fmonth_may', 'Fmonth_nov', 'Fmonth_oct', 'biY',
       'pred', 'accurate'], dtype=object)

In [49]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix

array([[5205, 2741],
       [ 707,  356]])

In [50]:
# Accuracy
# "Accuracy: ", test_df.accurate.mean()
accuracy_rf = (confusion_matrix[0][0] + confusion_matrix[1][1]) / (confusion_matrix[0][0] + confusion_matrix[0][1] + confusion_matrix[1][0] + confusion_matrix[1][1])
accuracy_rf


0.6172716172716173

In [51]:
# Split dataset based on marital status
test_df.columns.values
test_l30 = x_test[x_test['catAge_<=30'] == 1]
test_30to40 = x_test[x_test['catAge_30-40'] == 1]
test_40to50 = x_test[x_test['catAge_40-50'] == 1]
test_g50 = x_test[x_test['catAge_>=50'] == 1]

In [52]:
# Test on single subset
rf_pred_l30 = rf.fit(x_train, y_train).predict(test_l30)

test_df = test_l30.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(rf_pred_l30, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_l30 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_l30

array([[698, 529],
       [ 97,  70]])

In [53]:
accuracy_rf_l30 = (confusion_matrix_l30[0][0] + confusion_matrix_l30[1][1]) / (confusion_matrix_l30[0][0] + confusion_matrix_l30[0][1] + confusion_matrix_l30[1][0] + confusion_matrix_l30[1][1])
accuracy_rf_l30

0.5509325681492109

In [54]:
# Test on 30to40 subset
rf_pred_30to40 = rf.fit(x_train, y_train).predict(test_30to40)

test_df = test_30to40.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(rf_pred_30to40, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_30to40 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_30to40

array([[2491,  624],
       [ 354,   91]])

In [55]:
accuracy_rf_30to40 = (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[1][1]) / (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[0][1] + confusion_matrix_30to40[1][0] + confusion_matrix_30to40[1][1])
accuracy_rf_30to40

0.7252808988764045

In [56]:
# Test on 40to50 subset
rf_pred_40to50 = rf.fit(x_train, y_train).predict(test_40to50)
 
test_df = test_40to50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(rf_pred_40to50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])
 
from sklearn.metrics import confusion_matrix
 
confusion_matrix_40to50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_40to50


array([[1152,  850],
       [ 136,  106]])

In [57]:
accuracy_rf_40to50 = (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[1][1]) / (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[0][1] + confusion_matrix_40to50[1][0] + confusion_matrix_40to50[1][1])
accuracy_rf_40to50 

0.5606060606060606

In [58]:
# Test on g50 subset
rf_pred_g50 = rf.fit(x_train, y_train).predict(test_g50)
 
test_df = test_g50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(rf_pred_g50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])
 
from sklearn.metrics import confusion_matrix
 
confusion_matrix_g50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_g50

array([[864, 738],
       [120,  89]])

In [59]:
accuracy_rf_g50 = (confusion_matrix_g50[0][0] + confusion_matrix_g50[1][1]) / (confusion_matrix_g50[0][0] + confusion_matrix_g50[0][1] + confusion_matrix_g50[1][0] + confusion_matrix_g50[1][1])
accuracy_rf_g50 

0.526228602981778

In [60]:
#Demographic Parity
# positive rate = TP + TN
PR_rf_l30 = confusion_matrix_l30[0,0] +confusion_matrix_l30[1,1]
PR_rf_l30 # 4756

768

In [61]:
PR_rf_30to40 = confusion_matrix_30to40[0,0] +confusion_matrix_30to40[1,1]
PR_rf_30to40 # 2136

2582

In [62]:
PR_rf_40to50 = confusion_matrix_40to50[0,0] +confusion_matrix_40to50[1,1]
PR_rf_40to50 # 2136

1258

In [63]:
PR_rf_g50 = confusion_matrix_g50[0,0] +confusion_matrix_g50[1,1]
PR_rf_g50 # 2136

953

In [64]:
# Equalized Opportunity
#TPR = TP/TP+FN

TPR_rf_l30 = confusion_matrix_l30[0,0] / (confusion_matrix_l30[0,0] + confusion_matrix_l30[1,0])

TPR_rf_l30

0.8779874213836478

In [65]:
TPR_rf_30to40 = confusion_matrix_30to40[0,0] / (confusion_matrix_30to40[0,0] + confusion_matrix_30to40[1,0])

TPR_rf_30to40  

0.8755711775043937

In [66]:
TPR_rf_40to50  = confusion_matrix_40to50[0,0] / (confusion_matrix_40to50[0,0] + confusion_matrix_40to50[1,0])

TPR_rf_40to50 

0.8944099378881988

In [67]:
TPR_rf_g50  = confusion_matrix_g50[0,0] / (confusion_matrix_g50[0,0] + confusion_matrix_g50[1,0])

TPR_rf_g50 

0.8780487804878049

In [68]:
# Equalized Odds
#TPR = TP/TP+FN
#FNR = FN/FN+TP


FNR_rf_l30 = confusion_matrix_l30[1,0] / (confusion_matrix_l30[1,0] + confusion_matrix_l30[0,0])

FNR_rf_l30 # 0.11652109273369263


0.1220125786163522

In [69]:
FNR_rf_30to40 = confusion_matrix_30to40[1,0] / (confusion_matrix_30to40[1,0] + confusion_matrix_30to40[0,0])

FNR_rf_30to40

0.12442882249560633

In [70]:
FNR_rf_40to50 = confusion_matrix_40to50[1,0] / (confusion_matrix_40to50[1,0] + confusion_matrix_40to50[0,0])

FNR_rf_40to50

0.10559006211180125

In [71]:
FNR_rf_g50 = confusion_matrix_g50[1,0] / (confusion_matrix_g50[1,0] + confusion_matrix_g50[0,0])

FNR_rf_g50

0.12195121951219512

In [72]:
# Fairness Through Unwareness
x_train_unawareness = x_train.copy()
x_train_unawareness
x_train_unawareness.drop('catAge_<=30', inplace=True, axis=1)
x_train_unawareness.drop('catAge_30-40', inplace=True, axis=1)
x_train_unawareness.drop('catAge_40-50', inplace=True, axis=1)
x_train_unawareness.drop('catAge_>=50', inplace=True, axis=1)

# x_train_unawareness.columns.values
# x_train.columns.values

In [73]:
#Fairness through unawareness

x_test_unawareness = x_test.copy()
x_test_unawareness
x_test_l30 = x_test_unawareness[x_test_unawareness['catAge_<=30'] == 1]
x_test_30to40 = x_test_unawareness[x_test_unawareness['catAge_30-40'] == 1]
x_test_40to50 = x_test_unawareness[x_test_unawareness['catAge_40-50'] == 1]
x_test_g50 = x_test_unawareness[x_test_unawareness['catAge_>=50'] == 1]


x_test_l30.drop('catAge_<=30', inplace=True, axis=1)
x_test_l30.drop('catAge_30-40', inplace=True, axis=1)
x_test_l30.drop('catAge_40-50', inplace=True, axis=1)
x_test_l30.drop('catAge_>=50', inplace=True, axis=1)

x_test_30to40.drop('catAge_<=30', inplace=True, axis=1)
x_test_30to40.drop('catAge_30-40', inplace=True, axis=1)
x_test_30to40.drop('catAge_40-50', inplace=True, axis=1)
x_test_30to40.drop('catAge_>=50', inplace=True, axis=1)

x_test_40to50.drop('catAge_<=30', inplace=True, axis=1)
x_test_40to50.drop('catAge_30-40', inplace=True, axis=1)
x_test_40to50.drop('catAge_40-50', inplace=True, axis=1)
x_test_40to50.drop('catAge_>=50', inplace=True, axis=1)

x_test_g50.drop('catAge_<=30', inplace=True, axis=1)
x_test_g50.drop('catAge_30-40', inplace=True, axis=1)
x_test_g50.drop('catAge_40-50', inplace=True, axis=1)
x_test_g50.drop('catAge_>=50', inplace=True, axis=1)



# x_test_unawareness.columns.values
# x_test.columns.values

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/core/frame.py:4163: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


In [74]:
# Test on l30 set
rf_pred_l30 = rf.fit(x_train_unawareness, y_train).predict(x_test_l30)

test_df = x_test_l30.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(rf_pred_l30, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_l30 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_l30


array([[816, 411],
       [103,  64]])

In [75]:
accuracy_rf_l30 = (confusion_matrix_l30[0][0] + confusion_matrix_l30[1][1]) / (confusion_matrix_l30[0][0] + confusion_matrix_l30[0][1] + confusion_matrix_l30[1][0] + confusion_matrix_l30[1][1])
accuracy_rf_l30

0.6312769010043041

In [76]:
# Test on 30to40 set
rf_pred_30to40 = rf.fit(x_train_unawareness, y_train).predict(x_test_30to40)

test_df = x_test_30to40.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(rf_pred_30to40, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_30to40 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_30to40


array([[2067, 1048],
       [ 300,  145]])

In [77]:
accuracy_rf_30to40 = (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[1][1]) / (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[0][1] + confusion_matrix_30to40[1][0] + confusion_matrix_30to40[1][1])
accuracy_rf_30to40 

0.6213483146067416

In [78]:
# Test on 40to50 set
rf_pred_40to50 = rf.fit(x_train_unawareness, y_train).predict(x_test_40to50)

test_df = x_test_40to50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(rf_pred_40to50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_40to50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_40to50

array([[1210,  792],
       [ 139,  103]])

In [79]:
accuracy_rf_40to50 = (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[1][1]) / (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[0][1] + confusion_matrix_40to50[1][0] + confusion_matrix_40to50[1][1])
accuracy_rf_40to50 # 0.8718606782768102

0.5851158645276292

In [80]:
# Test on g50 set
rf_pred_g50 = rf.fit(x_train_unawareness, y_train).predict(x_test_g50)

test_df = x_test_g50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(rf_pred_g50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_g50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_g50

array([[916, 686],
       [131,  78]])

In [81]:
accuracy_rf_g50 = (confusion_matrix_g50[0][0] + confusion_matrix_g50[1][1]) / (confusion_matrix_g50[0][0] + confusion_matrix_g50[0][1] + confusion_matrix_g50[1][0] + confusion_matrix_g50[1][1])
accuracy_rf_g50 # 0.8718606782768102

0.548868028713418

Support Vector Machine

In [82]:
%%time
from sklearn import svm as svm_model
svm = svm_model.SVC(class_weight='balanced') # add class_weight='balanced' is to avoid classifying all data as 0
svm_pred = svm.fit(x_train, y_train).predict(x_test)

CPU times: user 6min 38s, sys: 4.99 s, total: 6min 43s
Wall time: 7min 30s


In [83]:
test_df = x_test.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(svm_pred, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])
test_df.columns.values

array(['balance', 'day', 'duration', 'campaign', 'pdays', 'previous',
       'biDefault', 'biHousing', 'biLoan', 'catAge_30-40', 'catAge_40-50',
       'catAge_<=30', 'catAge_>=50', 'job_admin.', 'job_blue-collar',
       'job_entrepreneur', 'job_housemaid', 'job_management',
       'job_retired', 'job_self-employed', 'job_services', 'job_student',
       'job_technician', 'job_unemployed', 'marital_divorced',
       'marital_married', 'marital_single', 'education_primary',
       'education_secondary', 'education_tertiary', 'month_apr',
       'month_aug', 'month_dec', 'month_feb', 'month_jan', 'month_jul',
       'month_jun', 'month_mar', 'month_may', 'month_nov', 'month_oct',
       'month_sep', 'Fmonth_apr', 'Fmonth_aug', 'Fmonth_dec',
       'Fmonth_feb', 'Fmonth_jan', 'Fmonth_jul', 'Fmonth_jun',
       'Fmonth_mar', 'Fmonth_may', 'Fmonth_nov', 'Fmonth_oct', 'biY',
       'pred', 'accurate'], dtype=object)

In [84]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix

array([[2302, 5644],
       [ 290,  773]])

In [85]:
# Accuracy
# "Accuracy: ", test_df.accurate.mean()
accuracy_svm = (confusion_matrix[0][0] + confusion_matrix[1][1]) / (confusion_matrix[0][0] + confusion_matrix[0][1] + confusion_matrix[1][0] + confusion_matrix[1][1])
accuracy_svm


0.3413253413253413

In [86]:
# Split dataset based on marital status
test_df.columns.values
test_l30 = x_test[x_test['catAge_<=30'] == 1]
test_30to40 = x_test[x_test['catAge_30-40'] == 1]
test_40to50 = x_test[x_test['catAge_40-50'] == 1]
test_g50 = x_test[x_test['catAge_>=50'] == 1]

In [87]:
# Test on l30 subset
svm_pred_l30 = svm.fit(x_train, y_train).predict(test_l30)

test_df = test_l30.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(svm_pred_l30, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_l30 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_l30

array([[281, 946],
       [ 39, 128]])

In [88]:
accuracy_svm_l30 = (confusion_matrix_l30[0][0] + confusion_matrix_l30[1][1]) / (confusion_matrix_l30[0][0] + confusion_matrix_l30[0][1] + confusion_matrix_l30[1][0] + confusion_matrix_l30[1][1])
accuracy_svm_l30

0.2934002869440459

In [89]:
# Test on married subset
svm_pred_30to40 = svm.fit(x_train, y_train).predict(test_30to40)

test_df = test_30to40.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(svm_pred_30to40, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_30to40 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_30to40

array([[ 860, 2255],
       [ 104,  341]])

In [90]:
accuracy_svm_30to40 = (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[1][1]) / (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[0][1] + confusion_matrix_30to40[1][0] + confusion_matrix_30to40[1][1])
accuracy_svm_30to40 # 0.8718606782768102

0.3373595505617977

In [91]:
# Test on 40to50 subset
svm_pred_40to50 = svm.fit(x_train, y_train).predict(test_40to50)

test_df = test_40to50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(svm_pred_40to50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_40to50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_40to50

array([[ 589, 1413],
       [  74,  168]])

In [92]:
accuracy_svm_40to50 = (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[1][1]) / (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[0][1] + confusion_matrix_40to50[1][0] + confusion_matrix_40to50[1][1])
accuracy_svm_40to50 

0.3373440285204991

In [93]:
# Test on g50 subset
svm_pred_g50 = svm.fit(x_train, y_train).predict(test_g50)

test_df = test_g50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(svm_pred_g50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_g50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_g50

array([[ 572, 1030],
       [  73,  136]])

In [94]:
accuracy_svm_g50 = (confusion_matrix_g50[0][0] + confusion_matrix_g50[1][1]) / (confusion_matrix_g50[0][0] + confusion_matrix_g50[0][1] + confusion_matrix_g50[1][0] + confusion_matrix_g50[1][1])
accuracy_svm_g50 # 0.8718606782768102

0.390944229707344

In [95]:
#Demographic Parity
# positive rate = TP + TN
PR_svm_l30 = confusion_matrix_l30[0,0] +confusion_matrix_l30[1,1]

PR_svm_l30

409

In [96]:
PR_svm_30to40 = confusion_matrix_30to40[0,0] +confusion_matrix_30to40[1,1]
PR_svm_30to40

1201

In [97]:
PR_svm_40to50 = confusion_matrix_40to50[0,0] +confusion_matrix_40to50[1,1]
PR_svm_40to50

757

In [98]:
PR_svm_g50 = confusion_matrix_g50[0,0] +confusion_matrix_g50[1,1]
PR_svm_g50

708

In [99]:
# Equalized Opportunity
#TPR = TP/TP+FN

TPR_svm_l30 = confusion_matrix_l30[0,0] / (confusion_matrix_l30[0,0] + confusion_matrix_l30[1,0])

TPR_svm_l30

0.878125

In [100]:
TPR_svm_30to40 = confusion_matrix_30to40[0,0] / (confusion_matrix_30to40[0,0] + confusion_matrix_30to40[1,0])

TPR_svm_30to40 

0.8921161825726142

In [101]:
TPR_svm_40to50 = confusion_matrix_40to50[0,0] / (confusion_matrix_40to50[0,0] + confusion_matrix_40to50[1,0])

TPR_svm_40to50 

0.8883861236802413

In [102]:
TPR_svm_g50 = confusion_matrix_g50[0,0] / (confusion_matrix_g50[0,0] + confusion_matrix_g50[1,0])

TPR_svm_g50 

0.8868217054263566

In [103]:
# Equalized Odds
#TPR = TP/TP+FN
#FNR = FN/FN+TP


FNR_svm_l30 = confusion_matrix_l30[1,0] / (confusion_matrix_l30[1,0] + confusion_matrix_l30[0,0])

FNR_svm_l30

0.121875

In [104]:
FNR_svm_30to40 = confusion_matrix_30to40[1,0] / (confusion_matrix_30to40[1,0] + confusion_matrix_30to40[0,0])

FNR_svm_30to40 

0.1078838174273859

In [105]:
FNR_svm_40to50 = confusion_matrix_40to50[1,0] / (confusion_matrix_40to50[1,0] + confusion_matrix_40to50[0,0])

FNR_svm_40to50 

0.11161387631975868

In [106]:
FNR_svm_g50 = confusion_matrix_g50[1,0] / (confusion_matrix_g50[1,0] + confusion_matrix_g50[0,0])

FNR_svm_g50 

0.11317829457364341

In [107]:
# Fairness Through Unwareness
x_train_unawareness = x_train.copy()
x_train_unawareness
x_train_unawareness.drop('catAge_<=30', inplace=True, axis=1)
x_train_unawareness.drop('catAge_30-40', inplace=True, axis=1)
x_train_unawareness.drop('catAge_40-50', inplace=True, axis=1)
x_train_unawareness.drop('catAge_>=50', inplace=True, axis=1)


# x_train_unawareness.columns.values
# x_train.columns.values

In [108]:
#Fairness through unawareness


x_test_unawareness = x_test.copy()
x_test_unawareness
x_test_l30 = x_test_unawareness[x_test_unawareness['catAge_<=30'] == 1]
x_test_30to40 = x_test_unawareness[x_test_unawareness['catAge_30-40'] == 1]
x_test_40to50 = x_test_unawareness[x_test_unawareness['catAge_40-50'] == 1]
x_test_g50 = x_test_unawareness[x_test_unawareness['catAge_>=50'] == 1]


x_test_l30.drop('catAge_<=30', inplace=True, axis=1)
x_test_l30.drop('catAge_30-40', inplace=True, axis=1)
x_test_l30.drop('catAge_40-50', inplace=True, axis=1)
x_test_l30.drop('catAge_>=50', inplace=True, axis=1)

x_test_30to40.drop('catAge_<=30', inplace=True, axis=1)
x_test_30to40.drop('catAge_30-40', inplace=True, axis=1)
x_test_30to40.drop('catAge_40-50', inplace=True, axis=1)
x_test_30to40.drop('catAge_>=50', inplace=True, axis=1)

x_test_40to50.drop('catAge_<=30', inplace=True, axis=1)
x_test_40to50.drop('catAge_30-40', inplace=True, axis=1)
x_test_40to50.drop('catAge_40-50', inplace=True, axis=1)
x_test_40to50.drop('catAge_>=50', inplace=True, axis=1)

x_test_g50.drop('catAge_<=30', inplace=True, axis=1)
x_test_g50.drop('catAge_30-40', inplace=True, axis=1)
x_test_g50.drop('catAge_40-50', inplace=True, axis=1)
x_test_g50.drop('catAge_>=50', inplace=True, axis=1)



/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/core/frame.py:4163: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


In [109]:
# Test on l30 set
svm_pred_l30 = svm.fit(x_train_unawareness, y_train).predict(x_test_l30)

test_df = x_test_l30.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(svm_pred_l30, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_l30 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_l30


array([[281, 946],
       [ 39, 128]])

In [110]:
accuracy_svm_l30 = (confusion_matrix_l30[0][0] + confusion_matrix_l30[1][1]) / (confusion_matrix_l30[0][0] + confusion_matrix_l30[0][1] + confusion_matrix_l30[1][0] + confusion_matrix_l30[1][1])
accuracy_svm_l30

0.2934002869440459

In [111]:
# Test on 30to40 set
svm_pred_30to40 = svm.fit(x_train_unawareness, y_train).predict(x_test_30to40)

test_df = x_test_30to40.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(svm_pred_30to40, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_30to40 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_30to40

array([[ 859, 2256],
       [ 104,  341]])

In [112]:
accuracy_svm_30to40 = (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[1][1]) / (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[0][1] + confusion_matrix_30to40[1][0] + confusion_matrix_30to40[1][1])
accuracy_svm_30to40 # 0.8718606782768102

0.33707865168539325

In [113]:
# Test on 40to50 subset
svm_pred_40to50 = svm.fit(x_train_unawareness, y_train).predict(x_test_40to50)

test_df = x_test_40to50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(svm_pred_40to50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_40to50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_40to50

array([[ 589, 1413],
       [  74,  168]])

In [114]:
accuracy_svm_40to50 = (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[1][1]) / (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[0][1] + confusion_matrix_40to50[1][0] + confusion_matrix_40to50[1][1])
accuracy_svm_40to50 

0.3373440285204991

In [115]:
# Test on g50 subset
svm_pred_g50 = svm.fit(x_train_unawareness, y_train).predict(x_test_g50)

test_df = x_test_g50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(svm_pred_g50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_g50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_g50

array([[ 572, 1030],
       [  73,  136]])

In [116]:
accuracy_svm_g50 = (confusion_matrix_g50[0][0] + confusion_matrix_g50[1][1]) / (confusion_matrix_g50[0][0] + confusion_matrix_g50[0][1] + confusion_matrix_g50[1][0] + confusion_matrix_g50[1][1])
accuracy_svm_g50 

0.390944229707344

Logistic Regression Model

In [117]:
%%time
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(random_state=0, class_weight='balanced')
clf_pred = clf.fit(x_train, y_train).predict(x_test)

CPU times: user 422 ms, sys: 92.1 ms, total: 514 ms
Wall time: 376 ms


In [118]:
test_df = x_test.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(clf_pred, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])
test_df.columns.values

array(['balance', 'day', 'duration', 'campaign', 'pdays', 'previous',
       'biDefault', 'biHousing', 'biLoan', 'catAge_30-40', 'catAge_40-50',
       'catAge_<=30', 'catAge_>=50', 'job_admin.', 'job_blue-collar',
       'job_entrepreneur', 'job_housemaid', 'job_management',
       'job_retired', 'job_self-employed', 'job_services', 'job_student',
       'job_technician', 'job_unemployed', 'marital_divorced',
       'marital_married', 'marital_single', 'education_primary',
       'education_secondary', 'education_tertiary', 'month_apr',
       'month_aug', 'month_dec', 'month_feb', 'month_jan', 'month_jul',
       'month_jun', 'month_mar', 'month_may', 'month_nov', 'month_oct',
       'month_sep', 'Fmonth_apr', 'Fmonth_aug', 'Fmonth_dec',
       'Fmonth_feb', 'Fmonth_jan', 'Fmonth_jul', 'Fmonth_jun',
       'Fmonth_mar', 'Fmonth_may', 'Fmonth_nov', 'Fmonth_oct', 'biY',
       'pred', 'accurate'], dtype=object)

In [119]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix

array([[4090, 3856],
       [ 535,  528]])

In [120]:
# Accuracy
# "Accuracy: ", test_df.accurate.mean()
accuracy_clf = (confusion_matrix[0][0] + confusion_matrix[1][1]) / (confusion_matrix[0][0] + confusion_matrix[0][1] + confusion_matrix[1][0] + confusion_matrix[1][1])
accuracy_clf

0.5125985125985126

In [121]:
# Split dataset based on marital status
test_df.columns.values
test_l30 = x_test[x_test['catAge_<=30'] == 1]
test_30to40 = x_test[x_test['catAge_30-40'] == 1]
test_40to50 = x_test[x_test['catAge_40-50'] == 1]
test_g50 = x_test[x_test['catAge_>=50'] == 1]

In [122]:
# Test on l30 subset
clf_pred_l30 = clf.fit(x_train, y_train).predict(test_l30)

test_df = test_l30.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(clf_pred_l30, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_l30 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_l30

array([[541, 686],
       [ 71,  96]])

In [123]:
accuracy_clf_l30 = (confusion_matrix_l30[0][0] + confusion_matrix_l30[1][1]) / (confusion_matrix_l30[0][0] + confusion_matrix_l30[0][1] + confusion_matrix_l30[1][0] + confusion_matrix_l30[1][1])
accuracy_clf_l30

0.4569583931133429

In [124]:
# Test on 30to40 subset
clf_pred_30to40 = clf.fit(x_train, y_train).predict(test_30to40)

test_df = test_30to40.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(clf_pred_30to40, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_30to40 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_30to40

array([[1588, 1527],
       [ 233,  212]])

In [125]:
accuracy_clf_30to40 = (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[1][1]) / (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[0][1] + confusion_matrix_30to40[1][0] + confusion_matrix_30to40[1][1])
accuracy_clf_30to40

0.5056179775280899

In [126]:
# Test on 40to50 subset
clf_pred_40to50 = clf.fit(x_train, y_train).predict(test_40to50)
 
test_df = test_40to50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(clf_pred_40to50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])
 
from sklearn.metrics import confusion_matrix
 
confusion_matrix_40to50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_40to50

array([[1056,  946],
       [ 119,  123]])

In [127]:
accuracy_clf_40to50 = (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[1][1]) / (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[0][1] + confusion_matrix_40to50[1][0] + confusion_matrix_40to50[1][1])
accuracy_clf_40to50 

0.5254010695187166

In [128]:
# Test on g50 subset
clf_pred_g50 = clf.fit(x_train, y_train).predict(test_g50)
 
test_df = test_g50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(clf_pred_g50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])
 
from sklearn.metrics import confusion_matrix
 
confusion_matrix_g50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_g50

array([[905, 697],
       [112,  97]])

In [129]:
accuracy_clf_g50 = (confusion_matrix_g50[0][0] + confusion_matrix_g50[1][1]) / (confusion_matrix_g50[0][0] + confusion_matrix_g50[0][1] + confusion_matrix_g50[1][0] + confusion_matrix_g50[1][1])
accuracy_clf_g50 

0.5532854776366648

In [130]:
#Demographic Parity
# positive rate = TP + TN
PR_clf_l30 = confusion_matrix_l30[0,0] +confusion_matrix_l30[1,1]
PR_clf_l30 # 4756

637

In [131]:
PR_clf_30to40 = confusion_matrix_30to40[0,0] +confusion_matrix_30to40[1,1]
PR_clf_30to40 # 2136

1800

In [132]:
PR_clf_40to50 = confusion_matrix_40to50[0,0] +confusion_matrix_40to50[1,1]
PR_clf_40to50 # 2136

1179

In [133]:
PR_clf_g50 = confusion_matrix_g50[0,0] +confusion_matrix_g50[1,1]
PR_clf_g50 # 2136

1002

In [134]:
# Equalized Opportunity
#TPR = TP/TP+FN

TPR_clf_l30 = confusion_matrix_l30[0,0] / (confusion_matrix_l30[0,0] + confusion_matrix_l30[1,0])

TPR_clf_l30

0.8839869281045751

In [135]:
TPR_clf_30to40 = confusion_matrix_30to40[0,0] / (confusion_matrix_30to40[0,0] + confusion_matrix_30to40[1,0])

TPR_clf_30to40  

0.8720483250961011

In [136]:
TPR_clf_40to50  = confusion_matrix_40to50[0,0] / (confusion_matrix_40to50[0,0] + confusion_matrix_40to50[1,0])

TPR_clf_40to50 

0.8987234042553192

In [137]:
TPR_clf_g50  = confusion_matrix_g50[0,0] / (confusion_matrix_g50[0,0] + confusion_matrix_g50[1,0])

TPR_clf_g50 

0.8898721730580138

In [138]:
# Equalized Odds
#TPR = TP/TP+FN
#FNR = FN/FN+TP


FNR_clf_l30 = confusion_matrix_l30[1,0] / (confusion_matrix_l30[1,0] + confusion_matrix_l30[0,0])

FNR_clf_l30 # 0.11652109273369263

0.11601307189542484

In [139]:
FNR_clf_30to40 = confusion_matrix_30to40[1,0] / (confusion_matrix_30to40[1,0] + confusion_matrix_30to40[0,0])

FNR_clf_30to40

0.12795167490389894

In [140]:
FNR_clf_40to50 = confusion_matrix_40to50[1,0] / (confusion_matrix_40to50[1,0] + confusion_matrix_40to50[0,0])

FNR_clf_40to50

0.10127659574468086

In [141]:
FNR_clf_g50 = confusion_matrix_g50[1,0] / (confusion_matrix_g50[1,0] + confusion_matrix_g50[0,0])

FNR_clf_g50

0.11012782694198624

In [142]:
# Fairness Through Unwareness
x_train_unawareness = x_train.copy()
x_train_unawareness
x_train_unawareness.drop('catAge_<=30', inplace=True, axis=1)
x_train_unawareness.drop('catAge_30-40', inplace=True, axis=1)
x_train_unawareness.drop('catAge_40-50', inplace=True, axis=1)
x_train_unawareness.drop('catAge_>=50', inplace=True, axis=1)

# x_train_unawareness.columns.values
# x_train.columns.values

In [143]:
#Fairness through unawareness

x_test_unawareness = x_test.copy()
x_test_unawareness
x_test_l30 = x_test_unawareness[x_test_unawareness['catAge_<=30'] == 1]
x_test_30to40 = x_test_unawareness[x_test_unawareness['catAge_30-40'] == 1]
x_test_40to50 = x_test_unawareness[x_test_unawareness['catAge_40-50'] == 1]
x_test_g50 = x_test_unawareness[x_test_unawareness['catAge_>=50'] == 1]


x_test_l30.drop('catAge_<=30', inplace=True, axis=1)
x_test_l30.drop('catAge_30-40', inplace=True, axis=1)
x_test_l30.drop('catAge_40-50', inplace=True, axis=1)
x_test_l30.drop('catAge_>=50', inplace=True, axis=1)

x_test_30to40.drop('catAge_<=30', inplace=True, axis=1)
x_test_30to40.drop('catAge_30-40', inplace=True, axis=1)
x_test_30to40.drop('catAge_40-50', inplace=True, axis=1)
x_test_30to40.drop('catAge_>=50', inplace=True, axis=1)

x_test_40to50.drop('catAge_<=30', inplace=True, axis=1)
x_test_40to50.drop('catAge_30-40', inplace=True, axis=1)
x_test_40to50.drop('catAge_40-50', inplace=True, axis=1)
x_test_40to50.drop('catAge_>=50', inplace=True, axis=1)

x_test_g50.drop('catAge_<=30', inplace=True, axis=1)
x_test_g50.drop('catAge_30-40', inplace=True, axis=1)
x_test_g50.drop('catAge_40-50', inplace=True, axis=1)
x_test_g50.drop('catAge_>=50', inplace=True, axis=1)



# x_test_unawareness.columns.values
# x_test.columns.values

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/core/frame.py:4163: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


In [144]:
# Test on l30 set
clf_pred_l30 = clf.fit(x_train_unawareness, y_train).predict(x_test_l30)

test_df = x_test_l30.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(clf_pred_l30, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_l30 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_l30

array([[541, 686],
       [ 72,  95]])

In [145]:
accuracy_clf_l30 = (confusion_matrix_l30[0][0] + confusion_matrix_l30[1][1]) / (confusion_matrix_l30[0][0] + confusion_matrix_l30[0][1] + confusion_matrix_l30[1][0] + confusion_matrix_l30[1][1])
accuracy_clf_l30

0.4562410329985653

In [146]:
# Test on 30to40 set
clf_pred_30to40 = clf.fit(x_train_unawareness, y_train).predict(x_test_30to40)

test_df = x_test_30to40.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(clf_pred_30to40, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_30to40 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_30to40


array([[1588, 1527],
       [ 233,  212]])

In [147]:
accuracy_clf_30to40 = (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[1][1]) / (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[0][1] + confusion_matrix_30to40[1][0] + confusion_matrix_30to40[1][1])
accuracy_clf_30to40 

0.5056179775280899

In [148]:
# Test on 40to50 set
clf_pred_40to50 = clf.fit(x_train_unawareness, y_train).predict(x_test_40to50)

test_df = x_test_40to50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(clf_pred_40to50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_40to50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_40to50

array([[1056,  946],
       [ 119,  123]])

In [149]:
accuracy_clf_40to50 = (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[1][1]) / (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[0][1] + confusion_matrix_40to50[1][0] + confusion_matrix_40to50[1][1])
accuracy_clf_40to50 # 0.8718606782768102

0.5254010695187166

In [150]:
# Test on g50 set
clf_pred_g50 = clf.fit(x_train_unawareness, y_train).predict(x_test_g50)

test_df = x_test_g50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(clf_pred_g50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_g50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_g50

array([[905, 697],
       [112,  97]])

In [151]:
accuracy_clf_g50 = (confusion_matrix_g50[0][0] + confusion_matrix_g50[1][1]) / (confusion_matrix_g50[0][0] + confusion_matrix_g50[0][1] + confusion_matrix_g50[1][0] + confusion_matrix_g50[1][1])
accuracy_clf_g50 # 0.8718606782768102

0.5532854776366648

Linear Regression model

In [152]:
from sklearn import linear_model
linear_regression_model = linear_model.LinearRegression()
linear_regression_model.fit(x_train, y_train)
prediction = linear_regression_model.predict(x_test)

Result

In [153]:
test_df = x_test.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(prediction, index=test_df.index)

test_df['accurate'] = (test_df['pred'] == test_df['biY'])
test_df['pred']

38779    0.116257
16635    0.110172
31810    0.116128
4485     0.110103
3992     0.115290
           ...   
21630    0.121771
11104    0.129326
27469    0.117897
433      0.120801
41301    0.134487
Name: pred, Length: 9009, dtype: float64