Credit Scoring Fairness Criteria

Load the dataset

In [1]:
%%time
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.cm as cm

CPU times: user 1.53 s, sys: 254 ms, total: 1.78 s
Wall time: 6.05 s


Load the dataset

In [2]:
%%time
import os
BANK_PATH = os.path.join(os.getcwd(), 'ML fairness/ml bank dataset/bankfullclean.csv') # Assign this to the location of the dataset
# print(os.getcwd())
print(BANK_PATH)

# 5254 number of rows have 'biY' == 1
# 39787 number of rows have 'biY' == 0


/Users/xinyu/Desktop/Research/Machine-Learning-Fairness--main/ML fairness/ml bank dataset/bankfullclean.csv
CPU times: user 1.45 ms, sys: 1.52 ms, total: 2.97 ms
Wall time: 2.35 ms


In [3]:
%%time
bank = pd.read_csv(BANK_PATH)
df = pd.DataFrame(bank)
df.head()
dummy = df[['catAge', 'job', 'marital','education','balance','day', 'month', 'duration', 'campaign', 'pdays', 'previous', 'Fmonth', 'biDefault', 'biHousing', 'biLoan']]
# dummy.columns.values
dummy = pd.get_dummies(data=dummy) 
# dummy.head()
dummy.columns.values
# df['marital'].unique()

# df['biY'].replace({0: False, 1: True}, inplace=True)
# print(df['biY'])


CPU times: user 449 ms, sys: 122 ms, total: 571 ms
Wall time: 1.63 s


array(['balance', 'day', 'duration', 'campaign', 'pdays', 'previous',
       'biDefault', 'biHousing', 'biLoan', 'catAge_30-40', 'catAge_40-50',
       'catAge_<=30', 'catAge_>=50', 'job_admin.', 'job_blue-collar',
       'job_entrepreneur', 'job_housemaid', 'job_management',
       'job_retired', 'job_self-employed', 'job_services', 'job_student',
       'job_technician', 'job_unemployed', 'marital_divorced',
       'marital_married', 'marital_single', 'education_primary',
       'education_secondary', 'education_tertiary', 'month_apr',
       'month_aug', 'month_dec', 'month_feb', 'month_jan', 'month_jul',
       'month_jun', 'month_mar', 'month_may', 'month_nov', 'month_oct',
       'month_sep', 'Fmonth_apr', 'Fmonth_aug', 'Fmonth_dec',
       'Fmonth_feb', 'Fmonth_jan', 'Fmonth_jul', 'Fmonth_jun',
       'Fmonth_mar', 'Fmonth_may', 'Fmonth_nov', 'Fmonth_oct'],
      dtype=object)

Machine Learning Classification Model

In [4]:
%%time
from sklearn.model_selection import train_test_split

CPU times: user 1.41 s, sys: 273 ms, total: 1.68 s
Wall time: 4.6 s


In [5]:
%%time
def get_naive_dataset(dataset):
    dataset = dataset.sample(frac=1).reset_index(drop=True)
    X = dummy
    y = dataset['biY']
    x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
    
    return (x_train, y_train), (x_test, y_test)

CPU times: user 7 µs, sys: 0 ns, total: 7 µs
Wall time: 12.6 µs


In [6]:
%%time
(x_train, y_train), (x_test, y_test) = get_naive_dataset(df)

CPU times: user 77.4 ms, sys: 28 ms, total: 105 ms
Wall time: 138 ms


In [7]:
%%time
x_train.columns.values

CPU times: user 36 µs, sys: 1 µs, total: 37 µs
Wall time: 44.8 µs


array(['balance', 'day', 'duration', 'campaign', 'pdays', 'previous',
       'biDefault', 'biHousing', 'biLoan', 'catAge_30-40', 'catAge_40-50',
       'catAge_<=30', 'catAge_>=50', 'job_admin.', 'job_blue-collar',
       'job_entrepreneur', 'job_housemaid', 'job_management',
       'job_retired', 'job_self-employed', 'job_services', 'job_student',
       'job_technician', 'job_unemployed', 'marital_divorced',
       'marital_married', 'marital_single', 'education_primary',
       'education_secondary', 'education_tertiary', 'month_apr',
       'month_aug', 'month_dec', 'month_feb', 'month_jan', 'month_jul',
       'month_jun', 'month_mar', 'month_may', 'month_nov', 'month_oct',
       'month_sep', 'Fmonth_apr', 'Fmonth_aug', 'Fmonth_dec',
       'Fmonth_feb', 'Fmonth_jan', 'Fmonth_jul', 'Fmonth_jun',
       'Fmonth_mar', 'Fmonth_may', 'Fmonth_nov', 'Fmonth_oct'],
      dtype=object)

In [8]:
%%time
y_train.values

CPU times: user 21 µs, sys: 1e+03 ns, total: 22 µs
Wall time: 27.9 µs


array([1, 1, 0, ..., 0, 0, 0])

In [9]:
%%time
x_test.columns.values

CPU times: user 36 µs, sys: 2 µs, total: 38 µs
Wall time: 47.9 µs


array(['balance', 'day', 'duration', 'campaign', 'pdays', 'previous',
       'biDefault', 'biHousing', 'biLoan', 'catAge_30-40', 'catAge_40-50',
       'catAge_<=30', 'catAge_>=50', 'job_admin.', 'job_blue-collar',
       'job_entrepreneur', 'job_housemaid', 'job_management',
       'job_retired', 'job_self-employed', 'job_services', 'job_student',
       'job_technician', 'job_unemployed', 'marital_divorced',
       'marital_married', 'marital_single', 'education_primary',
       'education_secondary', 'education_tertiary', 'month_apr',
       'month_aug', 'month_dec', 'month_feb', 'month_jan', 'month_jul',
       'month_jun', 'month_mar', 'month_may', 'month_nov', 'month_oct',
       'month_sep', 'Fmonth_apr', 'Fmonth_aug', 'Fmonth_dec',
       'Fmonth_feb', 'Fmonth_jan', 'Fmonth_jul', 'Fmonth_jun',
       'Fmonth_mar', 'Fmonth_may', 'Fmonth_nov', 'Fmonth_oct'],
      dtype=object)

In [10]:
%%time
y_test.values

CPU times: user 35 µs, sys: 10 µs, total: 45 µs
Wall time: 225 µs


array([1, 0, 0, ..., 0, 0, 0])

Naive Bayes Model

In [11]:
%%time
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb_pred = gnb.fit(x_train, y_train).predict(x_test)


CPU times: user 155 ms, sys: 69.7 ms, total: 225 ms
Wall time: 550 ms


Result

In [12]:
%%time
test_df = x_test.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(gnb_pred, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])
test_df.columns.values

CPU times: user 9.46 ms, sys: 3.35 ms, total: 12.8 ms
Wall time: 12.2 ms


array(['balance', 'day', 'duration', 'campaign', 'pdays', 'previous',
       'biDefault', 'biHousing', 'biLoan', 'catAge_30-40', 'catAge_40-50',
       'catAge_<=30', 'catAge_>=50', 'job_admin.', 'job_blue-collar',
       'job_entrepreneur', 'job_housemaid', 'job_management',
       'job_retired', 'job_self-employed', 'job_services', 'job_student',
       'job_technician', 'job_unemployed', 'marital_divorced',
       'marital_married', 'marital_single', 'education_primary',
       'education_secondary', 'education_tertiary', 'month_apr',
       'month_aug', 'month_dec', 'month_feb', 'month_jan', 'month_jul',
       'month_jun', 'month_mar', 'month_may', 'month_nov', 'month_oct',
       'month_sep', 'Fmonth_apr', 'Fmonth_aug', 'Fmonth_dec',
       'Fmonth_feb', 'Fmonth_jan', 'Fmonth_jul', 'Fmonth_jun',
       'Fmonth_mar', 'Fmonth_may', 'Fmonth_nov', 'Fmonth_oct', 'biY',
       'pred', 'accurate'], dtype=object)

In [13]:
%%time
from sklearn.metrics import confusion_matrix

CPU times: user 28 µs, sys: 1 µs, total: 29 µs
Wall time: 40.1 µs


In [14]:
%%time
confusion_matrix = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix

CPU times: user 32.9 ms, sys: 4.43 ms, total: 37.4 ms
Wall time: 37.2 ms


array([[7765,  242],
       [ 972,   30]])

In [15]:
%%time
# Accuracy
# "Accuracy: ", test_df.accurate.mean()

accuracy_naive_bayes = (confusion_matrix[0][0] + confusion_matrix[1][1]) / (confusion_matrix[0][0] + confusion_matrix[0][1] + confusion_matrix[1][0] + confusion_matrix[1][1])
accuracy_naive_bayes



CPU times: user 78 µs, sys: 1e+03 ns, total: 79 µs
Wall time: 88.7 µs


0.8652458652458652

In [16]:
%%time
# Split dataset based on marital status

test_df.columns.values
test_married = x_test[x_test['marital_married'] == 1]
test_single = x_test[x_test['marital_single'] == 1]
test_divorced = x_test[x_test['marital_divorced'] == 1]

CPU times: user 11 ms, sys: 3.7 ms, total: 14.7 ms
Wall time: 21.6 ms


In [17]:
%%time
# Test on single subset

gnb_pred_single = gnb.fit(x_train, y_train).predict(test_single)

test_df = test_single.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(gnb_pred_single, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_single = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_single


CPU times: user 133 ms, sys: 33.9 ms, total: 166 ms
Wall time: 231 ms


array([[2211,   59],
       [ 283,   13]])

In [18]:
%%time
accuracy_naive_bayes_single = (confusion_matrix_single[0][0] + confusion_matrix_single[1][1]) / (confusion_matrix_single[0][0] + confusion_matrix_single[0][1] + confusion_matrix_single[1][0] + confusion_matrix_single[1][1])
accuracy_naive_bayes_single

CPU times: user 90 µs, sys: 2 µs, total: 92 µs
Wall time: 103 µs


0.8667186282151208

In [19]:
%%time
# Test on married subset

gnb_pred_married = gnb.fit(x_train, y_train).predict(test_married)

test_df = test_married.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(gnb_pred_married, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_married = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_married

CPU times: user 142 ms, sys: 24.3 ms, total: 166 ms
Wall time: 316 ms


array([[4672,  161],
       [ 571,   15]])

In [20]:
%%time
accuracy_naive_bayes_married = (confusion_matrix_married[0][0] + confusion_matrix_married[1][1]) / (confusion_matrix_married[0][0] + confusion_matrix_married[0][1] + confusion_matrix_married[1][0] + confusion_matrix_married[1][1])
accuracy_naive_bayes_married 

CPU times: user 63 µs, sys: 1 µs, total: 64 µs
Wall time: 70.1 µs


0.8649197268868795

In [21]:
%%time
# Test on divorced subset

gnb_pred_divorced = gnb.fit(x_train, y_train).predict(test_divorced)

test_df = test_divorced.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(gnb_pred_divorced, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_divorced = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_divorced

CPU times: user 131 ms, sys: 29.3 ms, total: 160 ms
Wall time: 211 ms


array([[882,  22],
       [118,   2]])

In [22]:
%%time
accuracy_naive_bayes_divorced = (confusion_matrix_divorced[0][0] + confusion_matrix_divorced[1][1]) / (confusion_matrix_divorced[0][0] + confusion_matrix_divorced[0][1] + confusion_matrix_divorced[1][0] + confusion_matrix_divorced[1][1])
accuracy_naive_bayes_divorced # 0.8718606782768102

CPU times: user 105 µs, sys: 2 µs, total: 107 µs
Wall time: 120 µs


0.86328125

In [23]:
%%time
#Demographic Parity
# positive rate = TP + TN

PR_Naive_Bayes_married = confusion_matrix_married[0,0] +confusion_matrix_married[1,1]

PR_Naive_Bayes_married 


CPU times: user 79 µs, sys: 2 µs, total: 81 µs
Wall time: 90.1 µs


4687

In [24]:
%%time
PR_Naive_Bayes_single = confusion_matrix_single[0,0] +confusion_matrix_single[1,1]
PR_Naive_Bayes_single 

CPU times: user 65 µs, sys: 1 µs, total: 66 µs
Wall time: 76.1 µs


2224

In [25]:
%%time
PR_Naive_Bayes_divorced = confusion_matrix_divorced[0,0] +confusion_matrix_divorced[1,1]
PR_Naive_Bayes_divorced 

CPU times: user 51 µs, sys: 1 µs, total: 52 µs
Wall time: 59.1 µs


884

In [26]:
%%time
# Equalized Opportunity
#TPR = TP/TP+FN

TPR_Naive_Bayes_married = confusion_matrix_married[0,0] / (confusion_matrix_married[0,0] + confusion_matrix_married[1,0])

TPR_Naive_Bayes_married 


CPU times: user 76 µs, sys: 1e+03 ns, total: 77 µs
Wall time: 89.2 µs


0.8910928857524318

In [27]:
%%time
TPR_Naive_Bayes_single = confusion_matrix_single[0,0] / (confusion_matrix_single[0,0] + confusion_matrix_single[1,0])

TPR_Naive_Bayes_single 

CPU times: user 49 µs, sys: 1e+03 ns, total: 50 µs
Wall time: 55.8 µs


0.8865276663993584

In [28]:
%%time
TPR_Naive_Bayes_divorced = confusion_matrix_divorced[0,0] / (confusion_matrix_divorced[0,0] + confusion_matrix_divorced[1,0])

TPR_Naive_Bayes_divorced # 0.8925619834710744

CPU times: user 123 µs, sys: 126 µs, total: 249 µs
Wall time: 130 µs


0.882

In [29]:
%%time
# Equalized Odds
#TPR = TP/TP+FN
#FNR = FN/FN+TP


FNR_Naive_Bayes_married = confusion_matrix_married[1,0] / (confusion_matrix_married[1,0] + confusion_matrix_married[0,0])

FNR_Naive_Bayes_married 



CPU times: user 147 µs, sys: 22 µs, total: 169 µs
Wall time: 194 µs


0.10890711424756819

In [30]:
%%time
FNR_Naive_Bayes_single = confusion_matrix_single[1,0] / (confusion_matrix_single[1,0] + confusion_matrix_single[0,0])

FNR_Naive_Bayes_single 

CPU times: user 81 µs, sys: 4 µs, total: 85 µs
Wall time: 95.8 µs


0.11347233360064155

In [31]:
%%time
FNR_Naive_Bayes_divorced = confusion_matrix_divorced[1,0] / (confusion_matrix_divorced[1,0] + confusion_matrix_divorced[0,0])

FNR_Naive_Bayes_divorced 

CPU times: user 48 µs, sys: 1e+03 ns, total: 49 µs
Wall time: 55.1 µs


0.118

In [32]:
%%time
# Fairness Through Unwareness

x_train_unawareness = x_train.copy()
x_train_unawareness
x_train_unawareness.drop('marital_married', inplace=True, axis=1)
x_train_unawareness.drop('marital_single', inplace=True, axis=1)
x_train_unawareness.drop('marital_divorced', inplace=True, axis=1)

# x_train_unawareness.columns.values
# x_train.columns.values






CPU times: user 20.5 ms, sys: 10.3 ms, total: 30.8 ms
Wall time: 30 ms


In [33]:
%%time
#Fairness through unawareness

x_test_unawareness = x_test.copy()
x_test_unawareness
x_test_married = x_test_unawareness[x_test_unawareness['marital_married'] == 1]
x_test_single = x_test_unawareness[x_test_unawareness['marital_single'] == 1]
x_test_divorced = x_test_unawareness[x_test_unawareness['marital_divorced'] == 1]


x_test_married.drop('marital_married', inplace=True, axis=1)
x_test_married.drop('marital_single', inplace=True, axis=1)
x_test_married.drop('marital_divorced', inplace=True, axis=1)

x_test_single.drop('marital_married', inplace=True, axis=1)
x_test_single.drop('marital_single', inplace=True, axis=1)
x_test_single.drop('marital_divorced', inplace=True, axis=1)

x_test_divorced.drop('marital_married', inplace=True, axis=1)
x_test_divorced.drop('marital_single', inplace=True, axis=1)
x_test_divorced.drop('marital_divorced', inplace=True, axis=1)




# x_test_unawareness.columns.values
# x_test.columns.values
# test_married

CPU times: user 44.8 ms, sys: 3.98 ms, total: 48.7 ms
Wall time: 65.8 ms


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/core/frame.py:4163: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


In [34]:
%%time
# Test on single set

gnb_pred_single = gnb.fit(x_train_unawareness, y_train).predict(x_test_single)

test_df = x_test_single.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(gnb_pred_single, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_single = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_single



CPU times: user 128 ms, sys: 15.8 ms, total: 144 ms
Wall time: 250 ms


array([[2211,   59],
       [ 283,   13]])

In [35]:
%%time
accuracy_naive_bayes_single = (confusion_matrix_single[0][0] + confusion_matrix_single[1][1]) / (confusion_matrix_single[0][0] + confusion_matrix_single[0][1] + confusion_matrix_single[1][0] + confusion_matrix_single[1][1])
accuracy_naive_bayes_single 

CPU times: user 90 µs, sys: 2 µs, total: 92 µs
Wall time: 102 µs


0.8667186282151208

In [36]:
%%time
# Test on married set

gnb_pred_married = gnb.fit(x_train_unawareness, y_train).predict(x_test_married)

test_df = x_test_married.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(gnb_pred_married, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_married = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_married



CPU times: user 138 ms, sys: 17.3 ms, total: 156 ms
Wall time: 346 ms


array([[4673,  160],
       [ 571,   15]])

In [37]:
%%time
accuracy_naive_bayes_married = (confusion_matrix_married[0][0] + confusion_matrix_married[1][1]) / (confusion_matrix_married[0][0] + confusion_matrix_married[0][1] + confusion_matrix_married[1][0] + confusion_matrix_married[1][1])
accuracy_naive_bayes_married 

CPU times: user 91 µs, sys: 2 µs, total: 93 µs
Wall time: 103 µs


0.8651042627791106

In [38]:
%%time
# Test on divorced set

gnb_pred_divorced = gnb.fit(x_train_unawareness, y_train).predict(x_test_divorced)

test_df = x_test_divorced.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(gnb_pred_divorced, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_divorced = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_divorced

CPU times: user 123 ms, sys: 15.9 ms, total: 139 ms
Wall time: 222 ms


array([[881,  23],
       [117,   3]])

In [39]:
%%time
accuracy_naive_bayes_divorced = (confusion_matrix_divorced[0][0] + confusion_matrix_divorced[1][1]) / (confusion_matrix_divorced[0][0] + confusion_matrix_divorced[0][1] + confusion_matrix_divorced[1][0] + confusion_matrix_divorced[1][1])
accuracy_naive_bayes_divorced # 0.8718606782768102

CPU times: user 81 µs, sys: 2 µs, total: 83 µs
Wall time: 92 µs


0.86328125

Random Forest Model

In [40]:
%%time
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(max_depth=5, random_state=0, class_weight='balanced')
rf_pred = rf.fit(x_train, y_train).predict(x_test)

CPU times: user 4.67 s, sys: 112 ms, total: 4.78 s
Wall time: 6.81 s


In [41]:
%%time
test_df = x_test.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(rf_pred, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])
test_df.columns.values

CPU times: user 8.5 ms, sys: 1.23 ms, total: 9.73 ms
Wall time: 13.1 ms


array(['balance', 'day', 'duration', 'campaign', 'pdays', 'previous',
       'biDefault', 'biHousing', 'biLoan', 'catAge_30-40', 'catAge_40-50',
       'catAge_<=30', 'catAge_>=50', 'job_admin.', 'job_blue-collar',
       'job_entrepreneur', 'job_housemaid', 'job_management',
       'job_retired', 'job_self-employed', 'job_services', 'job_student',
       'job_technician', 'job_unemployed', 'marital_divorced',
       'marital_married', 'marital_single', 'education_primary',
       'education_secondary', 'education_tertiary', 'month_apr',
       'month_aug', 'month_dec', 'month_feb', 'month_jan', 'month_jul',
       'month_jun', 'month_mar', 'month_may', 'month_nov', 'month_oct',
       'month_sep', 'Fmonth_apr', 'Fmonth_aug', 'Fmonth_dec',
       'Fmonth_feb', 'Fmonth_jan', 'Fmonth_jul', 'Fmonth_jun',
       'Fmonth_mar', 'Fmonth_may', 'Fmonth_nov', 'Fmonth_oct', 'biY',
       'pred', 'accurate'], dtype=object)

In [42]:
%%time
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix

CPU times: user 22.5 ms, sys: 2.53 ms, total: 25 ms
Wall time: 45.6 ms


array([[4607, 3400],
       [ 588,  414]])

In [43]:
%%time
# Accuracy
# "Accuracy: ", test_df.accurate.mean()

accuracy_rf = (confusion_matrix[0][0] + confusion_matrix[1][1]) / (confusion_matrix[0][0] + confusion_matrix[0][1] + confusion_matrix[1][0] + confusion_matrix[1][1])
accuracy_rf


CPU times: user 86 µs, sys: 1e+03 ns, total: 87 µs
Wall time: 97 µs


0.5573315573315574

In [44]:
%%time
# Split dataset based on marital status

test_df.columns.values
test_married = x_test[x_test['marital_married'] == 1]
test_single = x_test[x_test['marital_single'] == 1]
test_divorced = x_test[x_test['marital_divorced'] == 1]

CPU times: user 10 ms, sys: 2.78 ms, total: 12.8 ms
Wall time: 12.4 ms


In [45]:
%%time
# Test on single subset

rf_pred_single = rf.fit(x_train, y_train).predict(test_single)

test_df = test_single.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(rf_pred_single, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_single = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_single

CPU times: user 4.56 s, sys: 93.9 ms, total: 4.65 s
Wall time: 9.61 s


array([[1215, 1055],
       [ 164,  132]])

In [46]:
%%time
accuracy_rf_single = (confusion_matrix_single[0][0] + confusion_matrix_single[1][1]) / (confusion_matrix_single[0][0] + confusion_matrix_single[0][1] + confusion_matrix_single[1][0] + confusion_matrix_single[1][1])
accuracy_rf_single

CPU times: user 85 µs, sys: 2 µs, total: 87 µs
Wall time: 99.2 µs


0.5249415432579891

In [47]:
%%time
# Test on married subset

rf_pred_married = rf.fit(x_train, y_train).predict(test_married)

test_df = test_married.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(rf_pred_married, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_married = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_married

CPU times: user 4.43 s, sys: 65.2 ms, total: 4.49 s
Wall time: 6.42 s


array([[2655, 2178],
       [ 328,  258]])

In [48]:
%%time
accuracy_rf_married = (confusion_matrix_married[0][0] + confusion_matrix_married[1][1]) / (confusion_matrix_married[0][0] + confusion_matrix_married[0][1] + confusion_matrix_married[1][0] + confusion_matrix_married[1][1])

accuracy_rf_married 

CPU times: user 80 µs, sys: 1e+03 ns, total: 81 µs
Wall time: 90.1 µs


0.5375530540690164

In [49]:
%%time
# Test on divorced subset

rf_pred_divorced = rf.fit(x_train, y_train).predict(test_divorced)
 
test_df = test_divorced.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(rf_pred_divorced, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])
 
from sklearn.metrics import confusion_matrix
 
confusion_matrix_divorced = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_divorced


CPU times: user 4.75 s, sys: 90.7 ms, total: 4.84 s
Wall time: 6.45 s


array([[737, 167],
       [ 96,  24]])

In [50]:
%%time
accuracy_rf_divorced = (confusion_matrix_divorced[0][0] + confusion_matrix_divorced[1][1]) / (confusion_matrix_divorced[0][0] + confusion_matrix_divorced[0][1] + confusion_matrix_divorced[1][0] + confusion_matrix_divorced[1][1])
accuracy_rf_divorced 

CPU times: user 89 µs, sys: 2 µs, total: 91 µs
Wall time: 98.9 µs


0.7431640625

In [51]:
%%time
#Demographic Parity
# positive rate = TP + TN

PR_rf_married = confusion_matrix_married[0,0] +confusion_matrix_married[1,1]
PR_rf_married # 4756

CPU times: user 70 µs, sys: 2 µs, total: 72 µs
Wall time: 80.8 µs


2913

In [52]:
%%time
PR_rf_single = confusion_matrix_single[0,0] +confusion_matrix_single[1,1]
PR_rf_single # 2136

CPU times: user 65 µs, sys: 1 µs, total: 66 µs
Wall time: 75.8 µs


1347

In [53]:
%%time
PR_rf_divorced = confusion_matrix_divorced[0,0] +confusion_matrix_divorced[1,1]
PR_rf_divorced # 2136

CPU times: user 78 µs, sys: 2 µs, total: 80 µs
Wall time: 90.8 µs


761

In [54]:
%%time
# Equalized Opportunity
#TPR = TP/TP+FN

TPR_rf_married = confusion_matrix_married[0,0] / (confusion_matrix_married[0,0] + confusion_matrix_married[1,0])

TPR_rf_married 

CPU times: user 61 µs, sys: 1e+03 ns, total: 62 µs
Wall time: 70.8 µs


0.8900435802883003

In [55]:
%%time
TPR_rf_single = confusion_matrix_single[0,0] / (confusion_matrix_single[0,0] + confusion_matrix_single[1,0])

TPR_rf_single 

CPU times: user 68 µs, sys: 2 µs, total: 70 µs
Wall time: 80.1 µs


0.8810732414793329

In [56]:
%%time
TPR_rf_divorced = confusion_matrix_divorced[0,0] / (confusion_matrix_divorced[0,0] + confusion_matrix_divorced[1,0])

TPR_rf_divorced 

CPU times: user 82 µs, sys: 2 µs, total: 84 µs
Wall time: 97 µs


0.8847539015606243

In [57]:
%%time
# Equalized Odds
#TPR = TP/TP+FN
#FNR = FN/FN+TP


FNR_rf_married = confusion_matrix_married[1,0] / (confusion_matrix_married[1,0] + confusion_matrix_married[0,0])

FNR_rf_married # 0.11652109273369263


CPU times: user 77 µs, sys: 2 µs, total: 79 µs
Wall time: 89.9 µs


0.10995641971169963

In [58]:
%%time
FNR_rf_single = confusion_matrix_single[1,0] / (confusion_matrix_single[1,0] + confusion_matrix_single[0,0])

FNR_rf_single 

CPU times: user 75 µs, sys: 2 µs, total: 77 µs
Wall time: 87.7 µs


0.11892675852066716

In [59]:
%%time
FNR_rf_divorced = confusion_matrix_divorced[1,0] / (confusion_matrix_divorced[1,0] + confusion_matrix_divorced[0,0])

FNR_rf_divorced 

CPU times: user 126 µs, sys: 28 µs, total: 154 µs
Wall time: 885 µs


0.11524609843937575

In [60]:
%%time
# Fairness Through Unwareness

x_train_unawareness = x_train.copy()
x_train_unawareness
x_train_unawareness.drop('marital_married', inplace=True, axis=1)
x_train_unawareness.drop('marital_single', inplace=True, axis=1)
x_train_unawareness.drop('marital_divorced', inplace=True, axis=1)

# x_train_unawareness.columns.values
# x_train.columns.values

CPU times: user 21.9 ms, sys: 8.84 ms, total: 30.8 ms
Wall time: 34.9 ms


In [61]:
%%time
#Fairness through unawareness

x_test_unawareness = x_test.copy()
x_test_unawareness
x_test_married = x_test_unawareness[x_test_unawareness['marital_married'] == 1]
x_test_single = x_test_unawareness[x_test_unawareness['marital_single'] == 1]
x_test_divorced = x_test_unawareness[x_test_unawareness['marital_divorced'] == 1]


x_test_married.drop('marital_married', inplace=True, axis=1)
x_test_married.drop('marital_single', inplace=True, axis=1)
x_test_married.drop('marital_divorced', inplace=True, axis=1)

x_test_single.drop('marital_married', inplace=True, axis=1)
x_test_single.drop('marital_single', inplace=True, axis=1)
x_test_single.drop('marital_divorced', inplace=True, axis=1)

x_test_divorced.drop('marital_married', inplace=True, axis=1)
x_test_divorced.drop('marital_single', inplace=True, axis=1)
x_test_divorced.drop('marital_divorced', inplace=True, axis=1)


# x_test_unawareness.columns.values
# x_test.columns.values

CPU times: user 39.5 ms, sys: 4.48 ms, total: 43.9 ms
Wall time: 52.2 ms


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/core/frame.py:4163: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


In [62]:
%%time
# Test on single set

rf_pred_single = rf.fit(x_train_unawareness, y_train).predict(x_test_single)

test_df = x_test_single.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(rf_pred_single, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_single = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_single


CPU times: user 4.99 s, sys: 94.6 ms, total: 5.08 s
Wall time: 7.11 s


array([[1208, 1062],
       [ 160,  136]])

In [63]:
%%time
accuracy_rf_single = (confusion_matrix_single[0][0] + confusion_matrix_single[1][1]) / (confusion_matrix_single[0][0] + confusion_matrix_single[0][1] + confusion_matrix_single[1][0] + confusion_matrix_single[1][1])
accuracy_rf_single 

CPU times: user 90 µs, sys: 2 µs, total: 92 µs
Wall time: 102 µs


0.5237724084177708

In [64]:
%%time
# Test on married set

rf_pred_married = rf.fit(x_train_unawareness, y_train).predict(x_test_married)

test_df = x_test_married.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(rf_pred_married, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_married = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_married


CPU times: user 4.82 s, sys: 71.4 ms, total: 4.89 s
Wall time: 8.37 s


array([[2687, 2146],
       [ 313,  273]])

In [65]:
%%time
accuracy_rf_married = (confusion_matrix_married[0][0] + confusion_matrix_married[1][1]) / (confusion_matrix_married[0][0] + confusion_matrix_married[0][1] + confusion_matrix_married[1][0] + confusion_matrix_married[1][1])
accuracy_rf_married 

CPU times: user 139 µs, sys: 123 µs, total: 262 µs
Wall time: 152 µs


0.5462262410038753

In [66]:
%%time
# Test on divorced set

rf_pred_divorced = rf.fit(x_train_unawareness, y_train).predict(x_test_divorced)

test_df = x_test_divorced.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(rf_pred_divorced, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_divorced = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_divorced

CPU times: user 4.53 s, sys: 72 ms, total: 4.6 s
Wall time: 6.14 s


array([[527, 377],
       [ 77,  43]])

In [67]:
%%time
accuracy_rf_divorced = (confusion_matrix_divorced[0][0] + confusion_matrix_divorced[1][1]) / (confusion_matrix_divorced[0][0] + confusion_matrix_divorced[0][1] + confusion_matrix_divorced[1][0] + confusion_matrix_divorced[1][1])
accuracy_rf_divorced # 0.8718606782768102

CPU times: user 82 µs, sys: 1 µs, total: 83 µs
Wall time: 91.8 µs


0.556640625

Support Vector Machine

In [68]:
%%time
from sklearn import svm as svm_model
svm = svm_model.SVC(class_weight='balanced') # add class_weight='balanced' is to avoid classifying all data as 0
svm_pred = svm.fit(x_train, y_train).predict(x_test)

CPU times: user 7min 25s, sys: 6.51 s, total: 7min 31s
Wall time: 11min 35s


In [69]:
%%time
test_df = x_test.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(svm_pred, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])
test_df.columns.values

CPU times: user 11.8 ms, sys: 13.4 ms, total: 25.3 ms
Wall time: 33.7 ms


array(['balance', 'day', 'duration', 'campaign', 'pdays', 'previous',
       'biDefault', 'biHousing', 'biLoan', 'catAge_30-40', 'catAge_40-50',
       'catAge_<=30', 'catAge_>=50', 'job_admin.', 'job_blue-collar',
       'job_entrepreneur', 'job_housemaid', 'job_management',
       'job_retired', 'job_self-employed', 'job_services', 'job_student',
       'job_technician', 'job_unemployed', 'marital_divorced',
       'marital_married', 'marital_single', 'education_primary',
       'education_secondary', 'education_tertiary', 'month_apr',
       'month_aug', 'month_dec', 'month_feb', 'month_jan', 'month_jul',
       'month_jun', 'month_mar', 'month_may', 'month_nov', 'month_oct',
       'month_sep', 'Fmonth_apr', 'Fmonth_aug', 'Fmonth_dec',
       'Fmonth_feb', 'Fmonth_jan', 'Fmonth_jul', 'Fmonth_jun',
       'Fmonth_mar', 'Fmonth_may', 'Fmonth_nov', 'Fmonth_oct', 'biY',
       'pred', 'accurate'], dtype=object)

In [70]:
%%time
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix

CPU times: user 32.3 ms, sys: 9.41 ms, total: 41.7 ms
Wall time: 52.6 ms


array([[5977, 2030],
       [ 737,  265]])

In [71]:
%%time
# Accuracy
# "Accuracy: ", test_df.accurate.mean()

accuracy_svm = (confusion_matrix[0][0] + confusion_matrix[1][1]) / (confusion_matrix[0][0] + confusion_matrix[0][1] + confusion_matrix[1][0] + confusion_matrix[1][1])
accuracy_svm


CPU times: user 125 µs, sys: 3 µs, total: 128 µs
Wall time: 143 µs


0.6928626928626929

In [72]:
%%time
# Split dataset based on marital status

test_df.columns.values
test_married = x_test[x_test['marital_married'] == 1]
test_single = x_test[x_test['marital_single'] == 1]
test_divorced = x_test[x_test['marital_divorced'] == 1]

CPU times: user 12.5 ms, sys: 4.82 ms, total: 17.3 ms
Wall time: 18.9 ms


In [73]:
%%time
# Test on single subset

svm_pred_single = svm.fit(x_train, y_train).predict(test_single)

test_df = test_single.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(svm_pred_single, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_single = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_single

CPU times: user 6min 47s, sys: 4.91 s, total: 6min 52s
Wall time: 9min 27s


array([[1741,  529],
       [ 213,   83]])

In [74]:
%%time
accuracy_svm_single = (confusion_matrix_single[0][0] + confusion_matrix_single[1][1]) / (confusion_matrix_single[0][0] + confusion_matrix_single[0][1] + confusion_matrix_single[1][0] + confusion_matrix_single[1][1])
accuracy_svm_single

CPU times: user 110 µs, sys: 2 µs, total: 112 µs
Wall time: 130 µs


0.7108339828526891

In [75]:
%%time
# Test on married subset

svm_pred_married = svm.fit(x_train, y_train).predict(test_married)

test_df = test_married.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(svm_pred_married, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_married = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_married

CPU times: user 6min 21s, sys: 3.51 s, total: 6min 24s
Wall time: 7min 37s


array([[3539, 1294],
       [ 425,  161]])

In [76]:
%%time
accuracy_svm_married = (confusion_matrix_married[0][0] + confusion_matrix_married[1][1]) / (confusion_matrix_married[0][0] + confusion_matrix_married[0][1] + confusion_matrix_married[1][0] + confusion_matrix_married[1][1])
accuracy_svm_married # 0.8718606782768102

CPU times: user 106 µs, sys: 3 µs, total: 109 µs
Wall time: 120 µs


0.682782801254844

In [77]:
%%time
# Test on divorced subset

svm_pred_divorced = svm.fit(x_train, y_train).predict(test_divorced)

test_df = test_divorced.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(svm_pred_divorced, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_divorced = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_divorced

CPU times: user 5min 1s, sys: 2.29 s, total: 5min 4s
Wall time: 5min 14s


array([[697, 207],
       [ 99,  21]])

In [78]:
%%time
accuracy_svm_divorced = (confusion_matrix_divorced[0][0] + confusion_matrix_divorced[1][1]) / (confusion_matrix_divorced[0][0] + confusion_matrix_divorced[0][1] + confusion_matrix_divorced[1][0] + confusion_matrix_divorced[1][1])
accuracy_svm_divorced # 0.8718606782768102

CPU times: user 44 µs, sys: 0 ns, total: 44 µs
Wall time: 51.3 µs


0.701171875

In [79]:
%%time
#Demographic Parity
# positive rate = TP + TN

PR_svm_married = confusion_matrix_married[0,0] +confusion_matrix_married[1,1]

PR_svm_married

CPU times: user 46 µs, sys: 1 µs, total: 47 µs
Wall time: 54.1 µs


3700

In [80]:
%%time
PR_svm_single = confusion_matrix_single[0,0] +confusion_matrix_single[1,1]
PR_svm_single

CPU times: user 54 µs, sys: 1 µs, total: 55 µs
Wall time: 62.9 µs


1824

In [81]:
%%time
PR_svm_divorced = confusion_matrix_divorced[0,0] +confusion_matrix_divorced[1,1]
PR_svm_divorced 

CPU times: user 63 µs, sys: 1 µs, total: 64 µs
Wall time: 71.8 µs


718

In [82]:
%%time
# Equalized Opportunity
#TPR = TP/TP+FN

TPR_svm_married = confusion_matrix_married[0,0] / (confusion_matrix_married[0,0] + confusion_matrix_married[1,0])

TPR_svm_married 

CPU times: user 58 µs, sys: 1 µs, total: 59 µs
Wall time: 68.2 µs


0.8927850655903128

In [83]:
%%time
TPR_svm_single = confusion_matrix_single[0,0] / (confusion_matrix_single[0,0] + confusion_matrix_single[1,0])

TPR_svm_single 

CPU times: user 44 µs, sys: 1e+03 ns, total: 45 µs
Wall time: 49.8 µs


0.890992835209826

In [84]:
%%time
TPR_svm_divorced = confusion_matrix_divorced[0,0] / (confusion_matrix_divorced[0,0] + confusion_matrix_divorced[1,0])

TPR_svm_divorced 

CPU times: user 38 µs, sys: 1 µs, total: 39 µs
Wall time: 45.1 µs


0.8756281407035176

In [85]:
%%time
# Equalized Odds
#TPR = TP/TP+FN
#FNR = FN/FN+TP


FNR_svm_married = confusion_matrix_married[1,0] / (confusion_matrix_married[1,0] + confusion_matrix_married[0,0])

FNR_svm_married

CPU times: user 38 µs, sys: 1 µs, total: 39 µs
Wall time: 43.9 µs


0.10721493440968718

In [86]:
%%time
FNR_svm_single = confusion_matrix_single[1,0] / (confusion_matrix_single[1,0] + confusion_matrix_single[0,0])

FNR_svm_single 

CPU times: user 38 µs, sys: 1 µs, total: 39 µs
Wall time: 45.1 µs


0.109007164790174

In [87]:
%%time
FNR_svm_divorced = confusion_matrix_divorced[1,0] / (confusion_matrix_divorced[1,0] + confusion_matrix_divorced[0,0])

FNR_svm_divorced 

CPU times: user 38 µs, sys: 1 µs, total: 39 µs
Wall time: 45.1 µs


0.12437185929648241

In [88]:
%%time
# Fairness Through Unwareness

x_train_unawareness = x_train.copy()
x_train_unawareness
x_train_unawareness.drop('marital_married', inplace=True, axis=1)
x_train_unawareness.drop('marital_single', inplace=True, axis=1)
x_train_unawareness.drop('marital_divorced', inplace=True, axis=1)

# x_train_unawareness.columns.values
# x_train.columns.values

CPU times: user 18.9 ms, sys: 17.5 ms, total: 36.4 ms
Wall time: 35.6 ms


In [89]:
%%time
#Fairness through unawareness


x_test_unawareness = x_test.copy()
x_test_unawareness
x_test_married = x_test_unawareness[x_test_unawareness['marital_married'] == 1]
x_test_single = x_test_unawareness[x_test_unawareness['marital_single'] == 1]
x_test_divorced = x_test_unawareness[x_test_unawareness['marital_divorced'] == 1]


x_test_married.drop('marital_married', inplace=True, axis=1)
x_test_married.drop('marital_single', inplace=True, axis=1)
x_test_married.drop('marital_divorced', inplace=True, axis=1)

x_test_single.drop('marital_married', inplace=True, axis=1)
x_test_single.drop('marital_single', inplace=True, axis=1)
x_test_single.drop('marital_divorced', inplace=True, axis=1)

x_test_divorced.drop('marital_married', inplace=True, axis=1)
x_test_divorced.drop('marital_single', inplace=True, axis=1)
x_test_divorced.drop('marital_divorced', inplace=True, axis=1)



CPU times: user 27.7 ms, sys: 10.9 ms, total: 38.6 ms
Wall time: 36.3 ms


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/core/frame.py:4163: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


In [90]:
%%time
# Test on single set

svm_pred_single = svm.fit(x_train_unawareness, y_train).predict(x_test_single)

test_df = x_test_single.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(svm_pred_single, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_single = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_single


CPU times: user 4min 56s, sys: 2.17 s, total: 4min 58s
Wall time: 5min 11s


array([[1741,  529],
       [ 214,   82]])

In [91]:
%%time
accuracy_svm_single = (confusion_matrix_single[0][0] + confusion_matrix_single[1][1]) / (confusion_matrix_single[0][0] + confusion_matrix_single[0][1] + confusion_matrix_single[1][0] + confusion_matrix_single[1][1])
accuracy_svm_single

CPU times: user 65 µs, sys: 1 µs, total: 66 µs
Wall time: 73.9 µs


0.7104442712392829

In [92]:
%%time
# Test on married set

svm_pred_married = svm.fit(x_train_unawareness, y_train).predict(x_test_married)

test_df = x_test_married.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(svm_pred_married, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_married = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_married

CPU times: user 4min 56s, sys: 2.29 s, total: 4min 58s
Wall time: 5min 13s


array([[3539, 1294],
       [ 425,  161]])

In [93]:
%%time
accuracy_svm_married = (confusion_matrix_married[0][0] + confusion_matrix_married[1][1]) / (confusion_matrix_married[0][0] + confusion_matrix_married[0][1] + confusion_matrix_married[1][0] + confusion_matrix_married[1][1])
accuracy_svm_married # 0.8718606782768102

CPU times: user 49 µs, sys: 0 ns, total: 49 µs
Wall time: 56 µs


0.682782801254844

In [94]:
%%time
# Test on divorced subset

svm_pred_divorced = svm.fit(x_train_unawareness, y_train).predict(x_test_divorced)

test_df = x_test_divorced.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(svm_pred_divorced, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_divorced = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_divorced

CPU times: user 4min 33s, sys: 2.39 s, total: 4min 36s
Wall time: 4min 53s


array([[697, 207],
       [ 99,  21]])

In [95]:
%%time
accuracy_svm_divorced = (confusion_matrix_divorced[0][0] + confusion_matrix_divorced[1][1]) / (confusion_matrix_divorced[0][0] + confusion_matrix_divorced[0][1] + confusion_matrix_divorced[1][0] + confusion_matrix_divorced[1][1])
accuracy_svm_divorced 

CPU times: user 54 µs, sys: 1 µs, total: 55 µs
Wall time: 59.8 µs


0.701171875

Logistic Regression Model

In [96]:
%%time
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(random_state=0, class_weight='balanced')
clf_pred = clf.fit(x_train, y_train).predict(x_test)

CPU times: user 1.22 s, sys: 129 ms, total: 1.35 s
Wall time: 793 ms


In [97]:
%%time
test_df = x_test.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(clf_pred, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])
test_df.columns.values

CPU times: user 8.61 ms, sys: 6.22 ms, total: 14.8 ms
Wall time: 12.6 ms


array(['balance', 'day', 'duration', 'campaign', 'pdays', 'previous',
       'biDefault', 'biHousing', 'biLoan', 'catAge_30-40', 'catAge_40-50',
       'catAge_<=30', 'catAge_>=50', 'job_admin.', 'job_blue-collar',
       'job_entrepreneur', 'job_housemaid', 'job_management',
       'job_retired', 'job_self-employed', 'job_services', 'job_student',
       'job_technician', 'job_unemployed', 'marital_divorced',
       'marital_married', 'marital_single', 'education_primary',
       'education_secondary', 'education_tertiary', 'month_apr',
       'month_aug', 'month_dec', 'month_feb', 'month_jan', 'month_jul',
       'month_jun', 'month_mar', 'month_may', 'month_nov', 'month_oct',
       'month_sep', 'Fmonth_apr', 'Fmonth_aug', 'Fmonth_dec',
       'Fmonth_feb', 'Fmonth_jan', 'Fmonth_jul', 'Fmonth_jun',
       'Fmonth_mar', 'Fmonth_may', 'Fmonth_nov', 'Fmonth_oct', 'biY',
       'pred', 'accurate'], dtype=object)

In [98]:
%%time
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix

CPU times: user 35.2 ms, sys: 5.81 ms, total: 41 ms
Wall time: 26.2 ms


array([[3887, 4120],
       [ 484,  518]])

In [99]:
%%time
# Accuracy
# "Accuracy: ", test_df.accurate.mean()

accuracy_clf = (confusion_matrix[0][0] + confusion_matrix[1][1]) / (confusion_matrix[0][0] + confusion_matrix[0][1] + confusion_matrix[1][0] + confusion_matrix[1][1])
accuracy_clf


CPU times: user 56 µs, sys: 1 µs, total: 57 µs
Wall time: 62 µs


0.48895548895548896

In [100]:
%%time
# Split dataset based on marital status

test_df.columns.values
test_married = x_test[x_test['marital_married'] == 1]
test_single = x_test[x_test['marital_single'] == 1]
test_divorced = x_test[x_test['marital_divorced'] == 1]

CPU times: user 10.5 ms, sys: 3.65 ms, total: 14.1 ms
Wall time: 14.6 ms


In [101]:
%%time
# Test on single subset

clf_pred_single = clf.fit(x_train, y_train).predict(test_single)

test_df = test_single.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(clf_pred_single, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_single = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_single

CPU times: user 1.18 s, sys: 68.5 ms, total: 1.25 s
Wall time: 671 ms


array([[1080, 1190],
       [ 147,  149]])

In [102]:
%%time
accuracy_clf_single = (confusion_matrix_single[0][0] + confusion_matrix_single[1][1]) / (confusion_matrix_single[0][0] + confusion_matrix_single[0][1] + confusion_matrix_single[1][0] + confusion_matrix_single[1][1])
accuracy_clf_single

CPU times: user 83 µs, sys: 2 µs, total: 85 µs
Wall time: 94.9 µs


0.4789555728760717

In [103]:
%%time
# Test on married subset

clf_pred_married = clf.fit(x_train, y_train).predict(test_married)

test_df = test_married.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(clf_pred_married, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_married = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_married

CPU times: user 1.25 s, sys: 79.2 ms, total: 1.33 s
Wall time: 678 ms


array([[2307, 2526],
       [ 267,  319]])

In [104]:
%%time
accuracy_clf_married = (confusion_matrix_married[0][0] + confusion_matrix_married[1][1]) / (confusion_matrix_married[0][0] + confusion_matrix_married[0][1] + confusion_matrix_married[1][0] + confusion_matrix_married[1][1])
accuracy_clf_married 

CPU times: user 54 µs, sys: 1 µs, total: 55 µs
Wall time: 62 µs


0.48459125299870826

In [105]:
%%time
# Test on divorced subset

clf_pred_divorced = clf.fit(x_train, y_train).predict(test_divorced)
 
test_df = test_divorced.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(clf_pred_divorced, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])
 
from sklearn.metrics import confusion_matrix
 
confusion_matrix_divorced = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_divorced


CPU times: user 1.24 s, sys: 78.7 ms, total: 1.32 s
Wall time: 678 ms


array([[500, 404],
       [ 70,  50]])

In [106]:
%%time
accuracy_clf_divorced = (confusion_matrix_divorced[0][0] + confusion_matrix_divorced[1][1]) / (confusion_matrix_divorced[0][0] + confusion_matrix_divorced[0][1] + confusion_matrix_divorced[1][0] + confusion_matrix_divorced[1][1])
accuracy_clf_divorced 

CPU times: user 153 µs, sys: 12 µs, total: 165 µs
Wall time: 93 µs


0.537109375

In [107]:
%%time
#Demographic Parity
# positive rate = TP + TN

PR_clf_married = confusion_matrix_married[0,0] +confusion_matrix_married[1,1]
PR_clf_married # 4756

CPU times: user 113 µs, sys: 11 µs, total: 124 µs
Wall time: 69.1 µs


2626

In [108]:
%%time
PR_clf_single = confusion_matrix_single[0,0] +confusion_matrix_single[1,1]
PR_clf_single # 2136

CPU times: user 67 µs, sys: 2 µs, total: 69 µs
Wall time: 78 µs


1229

In [109]:
%%time
PR_clf_divorced = confusion_matrix_divorced[0,0] +confusion_matrix_divorced[1,1]
PR_clf_divorced # 2136

CPU times: user 48 µs, sys: 2 µs, total: 50 µs
Wall time: 56 µs


550

In [110]:
%%time
# Equalized Opportunity
#TPR = TP/TP+FN

TPR_clf_married = confusion_matrix_married[0,0] / (confusion_matrix_married[0,0] + confusion_matrix_married[1,0])

TPR_clf_married 

CPU times: user 65 µs, sys: 19 µs, total: 84 µs
Wall time: 207 µs


0.8962703962703963

In [111]:
%%time
TPR_clf_single = confusion_matrix_single[0,0] / (confusion_matrix_single[0,0] + confusion_matrix_single[1,0])

TPR_clf_single 

CPU times: user 52 µs, sys: 1 µs, total: 53 µs
Wall time: 62 µs


0.8801955990220048

In [112]:
%%time
TPR_clf_divorced = confusion_matrix_divorced[0,0] / (confusion_matrix_divorced[0,0] + confusion_matrix_divorced[1,0])

TPR_clf_divorced 

CPU times: user 113 µs, sys: 16 µs, total: 129 µs
Wall time: 1.73 ms


0.8771929824561403

In [113]:
%%time
# Equalized Odds
#TPR = TP/TP+FN
#FNR = FN/FN+TP


FNR_clf_married = confusion_matrix_married[1,0] / (confusion_matrix_married[1,0] + confusion_matrix_married[0,0])

FNR_clf_married # 0.11652109273369263

CPU times: user 49 µs, sys: 1 µs, total: 50 µs
Wall time: 57.7 µs


0.10372960372960373

In [114]:
%%time
FNR_clf_single = confusion_matrix_single[1,0] / (confusion_matrix_single[1,0] + confusion_matrix_single[0,0])

FNR_clf_single 

CPU times: user 48 µs, sys: 0 ns, total: 48 µs
Wall time: 56.7 µs


0.1198044009779951

In [115]:
%%time
FNR_clf_divorced = confusion_matrix_divorced[1,0] / (confusion_matrix_divorced[1,0] + confusion_matrix_divorced[0,0])

FNR_clf_divorced 

CPU times: user 56 µs, sys: 1e+03 ns, total: 57 µs
Wall time: 64.8 µs


0.12280701754385964

In [116]:
%%time
# Fairness Through Unwareness

x_train_unawareness = x_train.copy()
x_train_unawareness
x_train_unawareness.drop('marital_married', inplace=True, axis=1)
x_train_unawareness.drop('marital_single', inplace=True, axis=1)
x_train_unawareness.drop('marital_divorced', inplace=True, axis=1)

# x_train_unawareness.columns.values
# x_train.columns.values

CPU times: user 18.2 ms, sys: 7.38 ms, total: 25.6 ms
Wall time: 24.2 ms


In [117]:
%%time
#Fairness through unawareness

x_test_unawareness = x_test.copy()
x_test_unawareness
x_test_married = x_test_unawareness[x_test_unawareness['marital_married'] == 1]
x_test_single = x_test_unawareness[x_test_unawareness['marital_single'] == 1]
x_test_divorced = x_test_unawareness[x_test_unawareness['marital_divorced'] == 1]


x_test_married.drop('marital_married', inplace=True, axis=1)
x_test_married.drop('marital_single', inplace=True, axis=1)
x_test_married.drop('marital_divorced', inplace=True, axis=1)

x_test_single.drop('marital_married', inplace=True, axis=1)
x_test_single.drop('marital_single', inplace=True, axis=1)
x_test_single.drop('marital_divorced', inplace=True, axis=1)

x_test_divorced.drop('marital_married', inplace=True, axis=1)
x_test_divorced.drop('marital_single', inplace=True, axis=1)
x_test_divorced.drop('marital_divorced', inplace=True, axis=1)


# x_test_unawareness.columns.values
# x_test.columns.values

CPU times: user 25.3 ms, sys: 6.38 ms, total: 31.7 ms
Wall time: 32.4 ms


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/core/frame.py:4163: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


In [118]:
%%time
# Test on single set

clf_pred_single = clf.fit(x_train_unawareness, y_train).predict(x_test_single)

test_df = x_test_single.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(clf_pred_single, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_single = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_single

CPU times: user 667 ms, sys: 37.8 ms, total: 705 ms
Wall time: 387 ms


array([[1019, 1251],
       [ 142,  154]])

In [119]:
%%time
accuracy_clf_single = (confusion_matrix_single[0][0] + confusion_matrix_single[1][1]) / (confusion_matrix_single[0][0] + confusion_matrix_single[0][1] + confusion_matrix_single[1][0] + confusion_matrix_single[1][1])
accuracy_clf_single 

CPU times: user 162 µs, sys: 14 µs, total: 176 µs
Wall time: 97 µs


0.45713172252533124

In [120]:
%%time
# Test on married set

clf_pred_married = rf.fit(x_train_unawareness, y_train).predict(x_test_married)

test_df = x_test_married.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(clf_pred_married, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_married = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_married


CPU times: user 2.63 s, sys: 50.4 ms, total: 2.68 s
Wall time: 2.62 s


array([[2687, 2146],
       [ 313,  273]])

In [121]:
%%time
accuracy_clf_married = (confusion_matrix_married[0][0] + confusion_matrix_married[1][1]) / (confusion_matrix_married[0][0] + confusion_matrix_married[0][1] + confusion_matrix_married[1][0] + confusion_matrix_married[1][1])
accuracy_clf_married 

CPU times: user 96 µs, sys: 5 µs, total: 101 µs
Wall time: 116 µs


0.5462262410038753

In [122]:
%%time
# Test on divorced set

clf_pred_divorced = clf.fit(x_train_unawareness, y_train).predict(x_test_divorced)

test_df = x_test_divorced.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(clf_pred_divorced, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_divorced = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_divorced

CPU times: user 654 ms, sys: 57.6 ms, total: 712 ms
Wall time: 406 ms


array([[393, 511],
       [ 54,  66]])

In [123]:
%%time
accuracy_clf_divorced = (confusion_matrix_divorced[0][0] + confusion_matrix_divorced[1][1]) / (confusion_matrix_divorced[0][0] + confusion_matrix_divorced[0][1] + confusion_matrix_divorced[1][0] + confusion_matrix_divorced[1][1])
accuracy_clf_divorced # 0.8718606782768102

CPU times: user 145 µs, sys: 10 µs, total: 155 µs
Wall time: 86.1 µs


0.4482421875