Credit Scoring Fairness Criteria

Load the dataset

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.cm as cm

Load the dataset

In [2]:
import os
BANK_PATH = os.path.join(os.getcwd(), 'ML fairness/ml bank dataset/bankfullclean.csv') # Assign this to the location of the dataset
print(os.getcwd())
print(BANK_PATH)

# 5254 number of rows have 'biY' == 1
# 39787 number of rows have 'biY' == 0


/Users/xinyu/Desktop/Research/Machine-Learning-Fairness--main
/Users/xinyu/Desktop/Research/Machine-Learning-Fairness--main/ML fairness/ml bank dataset/bankfullclean.csv


In [3]:
bank = pd.read_csv(BANK_PATH)
df = pd.DataFrame(bank)
df.head()
dummy = df[['catAge', 'job', 'marital','education','balance','day', 'month', 'duration', 'campaign', 'pdays', 'previous', 'Fmonth', 'biDefault', 'biHousing', 'biLoan']]
# dummy.columns.values
dummy = pd.get_dummies(data=dummy)
# dummy.head()
dummy.columns.values
# df['marital'].unique()

# df['biY'].replace({0: False, 1: True}, inplace=True)
# print(df['biY'])


array(['balance', 'day', 'duration', 'campaign', 'pdays', 'previous',
       'biDefault', 'biHousing', 'biLoan', 'catAge_30-40', 'catAge_40-50',
       'catAge_<=30', 'catAge_>=50', 'job_admin.', 'job_blue-collar',
       'job_entrepreneur', 'job_housemaid', 'job_management',
       'job_retired', 'job_self-employed', 'job_services', 'job_student',
       'job_technician', 'job_unemployed', 'marital_divorced',
       'marital_married', 'marital_single', 'education_primary',
       'education_secondary', 'education_tertiary', 'month_apr',
       'month_aug', 'month_dec', 'month_feb', 'month_jan', 'month_jul',
       'month_jun', 'month_mar', 'month_may', 'month_nov', 'month_oct',
       'month_sep', 'Fmonth_apr', 'Fmonth_aug', 'Fmonth_dec',
       'Fmonth_feb', 'Fmonth_jan', 'Fmonth_jul', 'Fmonth_jun',
       'Fmonth_mar', 'Fmonth_may', 'Fmonth_nov', 'Fmonth_oct'],
      dtype=object)

Machine Learning Classification Model

In [4]:
%%time
from sklearn.model_selection import train_test_split
from sklearn.model_selection import LeaveOneOut

CPU times: user 1.31 s, sys: 335 ms, total: 1.64 s
Wall time: 5.44 s


In [5]:
%%time
def get_naive_dataset(dataset):
    dataset = dataset.sample(frac=1).reset_index(drop=True)
    X = dummy
    y = dataset['biY']
    x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
    
    return (x_train, y_train), (x_test, y_test)

CPU times: user 10 µs, sys: 2 µs, total: 12 µs
Wall time: 20 µs


In [6]:
%%time
(x_train, y_train), (x_test, y_test) = get_naive_dataset(df)

CPU times: user 80.3 ms, sys: 25.8 ms, total: 106 ms
Wall time: 115 ms


In [7]:
%%time
x_train.columns.values

CPU times: user 23 µs, sys: 1e+03 ns, total: 24 µs
Wall time: 28.8 µs


array(['balance', 'day', 'duration', 'campaign', 'pdays', 'previous',
       'biDefault', 'biHousing', 'biLoan', 'catAge_30-40', 'catAge_40-50',
       'catAge_<=30', 'catAge_>=50', 'job_admin.', 'job_blue-collar',
       'job_entrepreneur', 'job_housemaid', 'job_management',
       'job_retired', 'job_self-employed', 'job_services', 'job_student',
       'job_technician', 'job_unemployed', 'marital_divorced',
       'marital_married', 'marital_single', 'education_primary',
       'education_secondary', 'education_tertiary', 'month_apr',
       'month_aug', 'month_dec', 'month_feb', 'month_jan', 'month_jul',
       'month_jun', 'month_mar', 'month_may', 'month_nov', 'month_oct',
       'month_sep', 'Fmonth_apr', 'Fmonth_aug', 'Fmonth_dec',
       'Fmonth_feb', 'Fmonth_jan', 'Fmonth_jul', 'Fmonth_jun',
       'Fmonth_mar', 'Fmonth_may', 'Fmonth_nov', 'Fmonth_oct'],
      dtype=object)

In [8]:
%%time
y_train.values

CPU times: user 33 µs, sys: 1e+03 ns, total: 34 µs
Wall time: 44.1 µs


array([0, 0, 0, ..., 0, 1, 1])

In [9]:
%%time
x_test.columns.values

CPU times: user 28 µs, sys: 2 µs, total: 30 µs
Wall time: 39.1 µs


array(['balance', 'day', 'duration', 'campaign', 'pdays', 'previous',
       'biDefault', 'biHousing', 'biLoan', 'catAge_30-40', 'catAge_40-50',
       'catAge_<=30', 'catAge_>=50', 'job_admin.', 'job_blue-collar',
       'job_entrepreneur', 'job_housemaid', 'job_management',
       'job_retired', 'job_self-employed', 'job_services', 'job_student',
       'job_technician', 'job_unemployed', 'marital_divorced',
       'marital_married', 'marital_single', 'education_primary',
       'education_secondary', 'education_tertiary', 'month_apr',
       'month_aug', 'month_dec', 'month_feb', 'month_jan', 'month_jul',
       'month_jun', 'month_mar', 'month_may', 'month_nov', 'month_oct',
       'month_sep', 'Fmonth_apr', 'Fmonth_aug', 'Fmonth_dec',
       'Fmonth_feb', 'Fmonth_jan', 'Fmonth_jul', 'Fmonth_jun',
       'Fmonth_mar', 'Fmonth_may', 'Fmonth_nov', 'Fmonth_oct'],
      dtype=object)

In [10]:
%%time
y_test.values

CPU times: user 20 µs, sys: 0 ns, total: 20 µs
Wall time: 26.2 µs


array([0, 0, 1, ..., 0, 0, 0])

Naive Bayes Model

In [11]:
%%time
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb_pred = gnb.fit(x_train, y_train).predict(x_test)

CPU times: user 141 ms, sys: 72 ms, total: 213 ms
Wall time: 427 ms


Result

In [12]:
%%time
test_df = x_test.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(gnb_pred, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])
test_df.columns.values

CPU times: user 10.8 ms, sys: 4.46 ms, total: 15.2 ms
Wall time: 14.8 ms


array(['balance', 'day', 'duration', 'campaign', 'pdays', 'previous',
       'biDefault', 'biHousing', 'biLoan', 'catAge_30-40', 'catAge_40-50',
       'catAge_<=30', 'catAge_>=50', 'job_admin.', 'job_blue-collar',
       'job_entrepreneur', 'job_housemaid', 'job_management',
       'job_retired', 'job_self-employed', 'job_services', 'job_student',
       'job_technician', 'job_unemployed', 'marital_divorced',
       'marital_married', 'marital_single', 'education_primary',
       'education_secondary', 'education_tertiary', 'month_apr',
       'month_aug', 'month_dec', 'month_feb', 'month_jan', 'month_jul',
       'month_jun', 'month_mar', 'month_may', 'month_nov', 'month_oct',
       'month_sep', 'Fmonth_apr', 'Fmonth_aug', 'Fmonth_dec',
       'Fmonth_feb', 'Fmonth_jan', 'Fmonth_jul', 'Fmonth_jun',
       'Fmonth_mar', 'Fmonth_may', 'Fmonth_nov', 'Fmonth_oct', 'biY',
       'pred', 'accurate'], dtype=object)

In [13]:
%%time
from sklearn.metrics import confusion_matrix

CPU times: user 14 µs, sys: 1e+03 ns, total: 15 µs
Wall time: 19.3 µs


In [14]:
%%time
confusion_matrix = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix

CPU times: user 24.1 ms, sys: 4 ms, total: 28.1 ms
Wall time: 27.6 ms


array([[7694,  233],
       [1055,   27]])

In [15]:
%%time
# Accuracy
# "Accuracy: ", test_df.accurate.mean()
accuracy_naive_bayes = (confusion_matrix[0][0] + confusion_matrix[1][1]) / (confusion_matrix[0][0] + confusion_matrix[0][1] + confusion_matrix[1][0] + confusion_matrix[1][1])
accuracy_naive_bayes



CPU times: user 115 µs, sys: 277 µs, total: 392 µs
Wall time: 126 µs


0.857031857031857

In [16]:
%%time
# Split dataset based on marital status
test_df.columns.values
test_l30 = x_test[x_test['catAge_<=30'] == 1]
test_30to40 = x_test[x_test['catAge_30-40'] == 1]
test_40to50 = x_test[x_test['catAge_40-50'] == 1]
test_g50 = x_test[x_test['catAge_>=50'] == 1]

CPU times: user 14.1 ms, sys: 4.07 ms, total: 18.2 ms
Wall time: 17.1 ms


In [17]:
%%time
# Test on l30 subset
gnb_pred_l30 = gnb.fit(x_train, y_train).predict(test_l30)

test_df = test_l30.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(gnb_pred_l30, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_l30 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_l30


CPU times: user 143 ms, sys: 32.9 ms, total: 176 ms
Wall time: 350 ms


array([[1226,   25],
       [ 160,    5]])

In [18]:
%%time
accuracy_naive_bayes_l30 = (confusion_matrix_l30[0][0] + confusion_matrix_l30[1][1]) / (confusion_matrix_l30[0][0] + confusion_matrix_l30[0][1] + confusion_matrix_l30[1][0] + confusion_matrix_l30[1][1])
accuracy_naive_bayes_l30

CPU times: user 99 µs, sys: 2 µs, total: 101 µs
Wall time: 114 µs


0.8693502824858758

In [19]:
%%time
# Test on 30to40 subset
gnb_pred_30to40 = gnb.fit(x_train, y_train).predict(test_30to40)

test_df = test_30to40.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(gnb_pred_30to40, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_30to40 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_30to40

CPU times: user 140 ms, sys: 17.6 ms, total: 158 ms
Wall time: 405 ms


array([[2940,   94],
       [ 402,    8]])

In [20]:
%%time
accuracy_naive_bayes_30to40 = (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[1][1]) / (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[0][1] + confusion_matrix_30to40[1][0] + confusion_matrix_30to40[1][1])
accuracy_naive_bayes_30to40

CPU times: user 97 µs, sys: 2 µs, total: 99 µs
Wall time: 111 µs


0.8559814169570267

In [21]:
%%time
# Test on 40to50 subset
gnb_pred_40to50 = gnb.fit(x_train, y_train).predict(test_40to50)

test_df = test_40to50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(gnb_pred_40to50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_40to50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_40to50

CPU times: user 121 ms, sys: 15.4 ms, total: 137 ms
Wall time: 166 ms


array([[1947,   49],
       [ 270,    8]])

In [22]:
%%time
accuracy_naive_bayes_40to50 = (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[1][1]) / (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[0][1] + confusion_matrix_40to50[1][0] + confusion_matrix_40to50[1][1])
accuracy_naive_bayes_40to50 # 0.8718606782768102

CPU times: user 91 µs, sys: 2 µs, total: 93 µs
Wall time: 103 µs


0.8597185576077396

In [23]:
%%time
# Test on g50 subset

gnb_pred_g50 = gnb.fit(x_train, y_train).predict(test_g50)

test_df = test_g50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(gnb_pred_g50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_g50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_g50

CPU times: user 126 ms, sys: 17.7 ms, total: 143 ms
Wall time: 250 ms


array([[1581,   65],
       [ 223,    6]])

In [24]:
%%time
accuracy_naive_bayes_g50 = (confusion_matrix_g50[0][0] + confusion_matrix_g50[1][1]) / (confusion_matrix_g50[0][0] + confusion_matrix_g50[0][1] + confusion_matrix_g50[1][0] + confusion_matrix_g50[1][1])
accuracy_naive_bayes_g50 # 0.8718606782768102

CPU times: user 77 µs, sys: 1 µs, total: 78 µs
Wall time: 88.2 µs


0.8464

In [25]:
%%time
#Demographic Parity
# positive rate = TP + TN
PR_Naive_Bayes_l30 = confusion_matrix_l30[0,0] +confusion_matrix_l30[1,1]

PR_Naive_Bayes_l30 


CPU times: user 73 µs, sys: 2 µs, total: 75 µs
Wall time: 83.9 µs


1231

In [26]:
%%time
PR_Naive_Bayes_30to40 = confusion_matrix_30to40[0,0] +confusion_matrix_30to40[1,1]
PR_Naive_Bayes_30to40

CPU times: user 55 µs, sys: 2 µs, total: 57 µs
Wall time: 65.1 µs


2948

In [27]:
%%time
PR_Naive_Bayes_40to50 = confusion_matrix_40to50[0,0] +confusion_matrix_40to50[1,1]
PR_Naive_Bayes_40to50 

CPU times: user 75 µs, sys: 2 µs, total: 77 µs
Wall time: 86.8 µs


1955

In [28]:
%%time
PR_Naive_Bayes_g50 = confusion_matrix_g50[0,0] +confusion_matrix_g50[1,1]
PR_Naive_Bayes_g50 

CPU times: user 47 µs, sys: 1e+03 ns, total: 48 µs
Wall time: 54.8 µs


1587

In [29]:
%%time
# Equalized Opportunity
#TPR = TP/TP+FN

TPR_Naive_Bayes_l30 = confusion_matrix_l30[0,0] / (confusion_matrix_l30[0,0] + confusion_matrix_l30[1,0])

TPR_Naive_Bayes_l30


CPU times: user 74 µs, sys: 2 µs, total: 76 µs
Wall time: 87 µs


0.8845598845598845

In [30]:
%%time
TPR_Naive_Bayes_30to40 = confusion_matrix_30to40[0,0] / (confusion_matrix_30to40[0,0] + confusion_matrix_30to40[1,0])

TPR_Naive_Bayes_30to40

CPU times: user 73 µs, sys: 1e+03 ns, total: 74 µs
Wall time: 85.1 µs


0.8797127468581688

In [31]:
%%time
TPR_Naive_Bayes_40to50 = confusion_matrix_40to50[0,0] / (confusion_matrix_40to50[0,0] + confusion_matrix_40to50[1,0])

TPR_Naive_Bayes_40to50 

CPU times: user 88 µs, sys: 10 µs, total: 98 µs
Wall time: 139 µs


0.878213802435724

In [32]:
%%time
TPR_Naive_Bayes_g50 = confusion_matrix_g50[0,0] / (confusion_matrix_g50[0,0] + confusion_matrix_g50[1,0])

TPR_Naive_Bayes_g50 # 0.8925619834710744

CPU times: user 142 µs, sys: 11 µs, total: 153 µs
Wall time: 845 µs


0.8763858093126385

In [33]:
%%time
# Equalized Odds
#TPR = TP/TP+FN
#FNR = FN/FN+TP


FNR_Naive_Bayes_l30 = confusion_matrix_l30[1,0] / (confusion_matrix_l30[1,0] + confusion_matrix_l30[0,0])

FNR_Naive_Bayes_l30



CPU times: user 79 µs, sys: 3 µs, total: 82 µs
Wall time: 93 µs


0.11544011544011544

In [34]:
%%time
FNR_Naive_Bayes_30to40 = confusion_matrix_30to40[1,0] / (confusion_matrix_30to40[1,0] + confusion_matrix_30to40[0,0])

FNR_Naive_Bayes_30to40

CPU times: user 47 µs, sys: 1 µs, total: 48 µs
Wall time: 55.1 µs


0.12028725314183124

In [35]:
%%time
FNR_Naive_Bayes_40to50 = confusion_matrix_40to50[1,0] / (confusion_matrix_40to50[1,0] + confusion_matrix_40to50[0,0])

FNR_Naive_Bayes_40to50

CPU times: user 124 µs, sys: 15 µs, total: 139 µs
Wall time: 1.1 ms


0.12178619756427606

In [36]:
%%time
FNR_Naive_Bayes_g50 = confusion_matrix_g50[1,0] / (confusion_matrix_g50[1,0] + confusion_matrix_g50[0,0])

FNR_Naive_Bayes_g50

CPU times: user 80 µs, sys: 2 µs, total: 82 µs
Wall time: 94.9 µs


0.12361419068736142

In [37]:
%%time
# Fairness Through Unwareness

x_train_unawareness = x_train.copy()
x_train_unawareness
x_train_unawareness.drop('catAge_<=30', inplace=True, axis=1)
x_train_unawareness.drop('catAge_30-40', inplace=True, axis=1)
x_train_unawareness.drop('catAge_40-50', inplace=True, axis=1)
x_train_unawareness.drop('catAge_>=50', inplace=True, axis=1)

# x_train_unawareness.columns.values
# x_train.columns.values






CPU times: user 27.6 ms, sys: 11.5 ms, total: 39.1 ms
Wall time: 40.3 ms


In [38]:
%%time
#Fairness through unawareness

x_test_unawareness = x_test.copy()
x_test_unawareness
x_test_l30 = x_test_unawareness[x_test_unawareness['catAge_<=30'] == 1]
x_test_30to40 = x_test_unawareness[x_test_unawareness['catAge_30-40'] == 1]
x_test_40to50 = x_test_unawareness[x_test_unawareness['catAge_40-50'] == 1]
x_test_g50 = x_test_unawareness[x_test_unawareness['catAge_>=50'] == 1]


x_test_l30.drop('catAge_<=30', inplace=True, axis=1)
x_test_l30.drop('catAge_30-40', inplace=True, axis=1)
x_test_l30.drop('catAge_40-50', inplace=True, axis=1)
x_test_l30.drop('catAge_>=50', inplace=True, axis=1)

x_test_30to40.drop('catAge_<=30', inplace=True, axis=1)
x_test_30to40.drop('catAge_30-40', inplace=True, axis=1)
x_test_30to40.drop('catAge_40-50', inplace=True, axis=1)
x_test_30to40.drop('catAge_>=50', inplace=True, axis=1)

x_test_40to50.drop('catAge_<=30', inplace=True, axis=1)
x_test_40to50.drop('catAge_30-40', inplace=True, axis=1)
x_test_40to50.drop('catAge_40-50', inplace=True, axis=1)
x_test_40to50.drop('catAge_>=50', inplace=True, axis=1)

x_test_g50.drop('catAge_<=30', inplace=True, axis=1)
x_test_g50.drop('catAge_30-40', inplace=True, axis=1)
x_test_g50.drop('catAge_40-50', inplace=True, axis=1)
x_test_g50.drop('catAge_>=50', inplace=True, axis=1)




# x_test_unawareness.columns.values
# x_test.columns.values
# test_married

CPU times: user 70.4 ms, sys: 12.8 ms, total: 83.1 ms
Wall time: 182 ms


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/core/frame.py:4163: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


In [39]:
%%time
# Test on l30 set

gnb_pred_l30 = gnb.fit(x_train_unawareness, y_train).predict(x_test_l30)

test_df = x_test_l30.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(gnb_pred_l30, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_l30 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_l30



CPU times: user 136 ms, sys: 44.1 ms, total: 180 ms
Wall time: 481 ms


array([[1225,   26],
       [ 160,    5]])

In [40]:
%%time
accuracy_naive_bayes_l30 = (confusion_matrix_l30[0][0] + confusion_matrix_l30[1][1]) / (confusion_matrix_l30[0][0] + confusion_matrix_l30[0][1] + confusion_matrix_l30[1][0] + confusion_matrix_l30[1][1])
accuracy_naive_bayes_l30 

CPU times: user 125 µs, sys: 13 µs, total: 138 µs
Wall time: 175 µs


0.8686440677966102

In [41]:
%%time
# Test on 30to40 set

gnb_pred_30to40 = gnb.fit(x_train_unawareness, y_train).predict(x_test_30to40)

test_df = x_test_30to40.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(gnb_pred_30to40, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_30to40 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_30to40



CPU times: user 137 ms, sys: 14.4 ms, total: 151 ms
Wall time: 247 ms


array([[2940,   94],
       [ 402,    8]])

In [42]:
%%time
accuracy_naive_bayes_30to40 = (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[1][1]) / (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[0][1] + confusion_matrix_30to40[1][0] + confusion_matrix_30to40[1][1])
accuracy_naive_bayes_30to40 

CPU times: user 576 µs, sys: 379 µs, total: 955 µs
Wall time: 694 µs


0.8559814169570267

In [43]:
%%time
# Test on 40to50 set

gnb_pred_40to50 = gnb.fit(x_train_unawareness, y_train).predict(x_test_40to50)

test_df = x_test_40to50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(gnb_pred_40to50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_40to50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_40to50

CPU times: user 113 ms, sys: 14.2 ms, total: 128 ms
Wall time: 197 ms


array([[1947,   49],
       [ 270,    8]])

In [44]:
%%time
accuracy_naive_bayes_40to50 = (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[1][1]) / (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[0][1] + confusion_matrix_40to50[1][0] + confusion_matrix_40to50[1][1])
accuracy_naive_bayes_40to50 # 0.8718606782768102

CPU times: user 88 µs, sys: 2 µs, total: 90 µs
Wall time: 99.2 µs


0.8597185576077396

In [45]:
%%time
# Test on g50 set

gnb_pred_g50 = gnb.fit(x_train_unawareness, y_train).predict(x_test_g50)

test_df = x_test_g50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(gnb_pred_g50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_g50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_g50

CPU times: user 115 ms, sys: 12.7 ms, total: 128 ms
Wall time: 226 ms


array([[1581,   65],
       [ 223,    6]])

In [46]:
%%time
accuracy_naive_bayes_g50 = (confusion_matrix_g50[0][0] + confusion_matrix_g50[1][1]) / (confusion_matrix_g50[0][0] + confusion_matrix_g50[0][1] + confusion_matrix_g50[1][0] + confusion_matrix_g50[1][1])
accuracy_naive_bayes_g50 # 0.8718606782768102

CPU times: user 70 µs, sys: 1e+03 ns, total: 71 µs
Wall time: 79.2 µs


0.8464

Random Forest Model

In [47]:
%%time
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(max_depth=5, random_state=0, class_weight='balanced')
rf_pred = rf.fit(x_train, y_train).predict(x_test)

CPU times: user 4.72 s, sys: 86.6 ms, total: 4.81 s
Wall time: 6.74 s


In [48]:
%%time
test_df = x_test.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(rf_pred, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])
test_df.columns.values

CPU times: user 6.93 ms, sys: 2.63 ms, total: 9.57 ms
Wall time: 9.34 ms


array(['balance', 'day', 'duration', 'campaign', 'pdays', 'previous',
       'biDefault', 'biHousing', 'biLoan', 'catAge_30-40', 'catAge_40-50',
       'catAge_<=30', 'catAge_>=50', 'job_admin.', 'job_blue-collar',
       'job_entrepreneur', 'job_housemaid', 'job_management',
       'job_retired', 'job_self-employed', 'job_services', 'job_student',
       'job_technician', 'job_unemployed', 'marital_divorced',
       'marital_married', 'marital_single', 'education_primary',
       'education_secondary', 'education_tertiary', 'month_apr',
       'month_aug', 'month_dec', 'month_feb', 'month_jan', 'month_jul',
       'month_jun', 'month_mar', 'month_may', 'month_nov', 'month_oct',
       'month_sep', 'Fmonth_apr', 'Fmonth_aug', 'Fmonth_dec',
       'Fmonth_feb', 'Fmonth_jan', 'Fmonth_jul', 'Fmonth_jun',
       'Fmonth_mar', 'Fmonth_may', 'Fmonth_nov', 'Fmonth_oct', 'biY',
       'pred', 'accurate'], dtype=object)

In [49]:
%%time
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix

CPU times: user 30.5 ms, sys: 3.15 ms, total: 33.7 ms
Wall time: 134 ms


array([[5006, 2921],
       [ 700,  382]])

In [50]:
%%time
# Accuracy
# "Accuracy: ", test_df.accurate.mean()

accuracy_rf = (confusion_matrix[0][0] + confusion_matrix[1][1]) / (confusion_matrix[0][0] + confusion_matrix[0][1] + confusion_matrix[1][0] + confusion_matrix[1][1])
accuracy_rf


CPU times: user 94 µs, sys: 2 µs, total: 96 µs
Wall time: 106 µs


0.598068598068598

In [51]:
%%time
# Split dataset based on marital status

test_df.columns.values
test_l30 = x_test[x_test['catAge_<=30'] == 1]
test_30to40 = x_test[x_test['catAge_30-40'] == 1]
test_40to50 = x_test[x_test['catAge_40-50'] == 1]
test_g50 = x_test[x_test['catAge_>=50'] == 1]

CPU times: user 15 ms, sys: 3.74 ms, total: 18.7 ms
Wall time: 18.7 ms


In [52]:
%%time
# Test on single subset

rf_pred_l30 = rf.fit(x_train, y_train).predict(test_l30)

test_df = test_l30.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(rf_pred_l30, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_l30 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_l30

CPU times: user 4.61 s, sys: 93.2 ms, total: 4.7 s
Wall time: 9.73 s


array([[951, 300],
       [122,  43]])

In [53]:
%%time
accuracy_rf_l30 = (confusion_matrix_l30[0][0] + confusion_matrix_l30[1][1]) / (confusion_matrix_l30[0][0] + confusion_matrix_l30[0][1] + confusion_matrix_l30[1][0] + confusion_matrix_l30[1][1])
accuracy_rf_l30

CPU times: user 82 µs, sys: 1 µs, total: 83 µs
Wall time: 92 µs


0.7019774011299436

In [54]:
%%time
# Test on 30to40 subset

rf_pred_30to40 = rf.fit(x_train, y_train).predict(test_30to40)

test_df = test_30to40.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(rf_pred_30to40, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_30to40 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_30to40

CPU times: user 4.48 s, sys: 58.5 ms, total: 4.54 s
Wall time: 6.26 s


array([[1932, 1102],
       [ 261,  149]])

In [55]:
%%time
accuracy_rf_30to40 = (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[1][1]) / (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[0][1] + confusion_matrix_30to40[1][0] + confusion_matrix_30to40[1][1])
accuracy_rf_30to40

CPU times: user 81 µs, sys: 2 µs, total: 83 µs
Wall time: 93.2 µs


0.604239256678281

In [56]:
%%time
# Test on 40to50 subset

rf_pred_40to50 = rf.fit(x_train, y_train).predict(test_40to50)
 
test_df = test_40to50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(rf_pred_40to50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])
 
from sklearn.metrics import confusion_matrix
 
confusion_matrix_40to50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_40to50


CPU times: user 4.96 s, sys: 98.3 ms, total: 5.06 s
Wall time: 7.56 s


array([[1219,  777],
       [ 176,  102]])

In [57]:
%%time
accuracy_rf_40to50 = (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[1][1]) / (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[0][1] + confusion_matrix_40to50[1][0] + confusion_matrix_40to50[1][1])
accuracy_rf_40to50 

CPU times: user 148 µs, sys: 297 µs, total: 445 µs
Wall time: 192 µs


0.5809146877748461

In [58]:
%%time
# Test on g50 subset

rf_pred_g50 = rf.fit(x_train, y_train).predict(test_g50)
 
test_df = test_g50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(rf_pred_g50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])
 
from sklearn.metrics import confusion_matrix
 
confusion_matrix_g50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_g50

CPU times: user 5.02 s, sys: 86.5 ms, total: 5.11 s
Wall time: 6.89 s


array([[904, 742],
       [141,  88]])

In [59]:
%%time
accuracy_rf_g50 = (confusion_matrix_g50[0][0] + confusion_matrix_g50[1][1]) / (confusion_matrix_g50[0][0] + confusion_matrix_g50[0][1] + confusion_matrix_g50[1][0] + confusion_matrix_g50[1][1])
accuracy_rf_g50 

CPU times: user 65 µs, sys: 1 µs, total: 66 µs
Wall time: 74.9 µs


0.5290666666666667

In [60]:
%%time
#Demographic Parity
# positive rate = TP + TN

PR_rf_l30 = confusion_matrix_l30[0,0] +confusion_matrix_l30[1,1]
PR_rf_l30 # 4756

CPU times: user 67 µs, sys: 1 µs, total: 68 µs
Wall time: 77 µs


994

In [61]:
%%time
PR_rf_30to40 = confusion_matrix_30to40[0,0] +confusion_matrix_30to40[1,1]
PR_rf_30to40 # 2136

CPU times: user 71 µs, sys: 2 µs, total: 73 µs
Wall time: 81.8 µs


2081

In [62]:
%%time
PR_rf_40to50 = confusion_matrix_40to50[0,0] +confusion_matrix_40to50[1,1]
PR_rf_40to50 # 2136

CPU times: user 66 µs, sys: 1 µs, total: 67 µs
Wall time: 76.1 µs


1321

In [63]:
%%time
PR_rf_g50 = confusion_matrix_g50[0,0] +confusion_matrix_g50[1,1]
PR_rf_g50 # 2136

CPU times: user 90 µs, sys: 2 µs, total: 92 µs
Wall time: 105 µs


992

In [64]:
%%time
# Equalized Opportunity
#TPR = TP/TP+FN

TPR_rf_l30 = confusion_matrix_l30[0,0] / (confusion_matrix_l30[0,0] + confusion_matrix_l30[1,0])

TPR_rf_l30

CPU times: user 73 µs, sys: 2 µs, total: 75 µs
Wall time: 86.1 µs


0.8863000931966449

In [65]:
%%time
TPR_rf_30to40 = confusion_matrix_30to40[0,0] / (confusion_matrix_30to40[0,0] + confusion_matrix_30to40[1,0])

TPR_rf_30to40  

CPU times: user 68 µs, sys: 2 µs, total: 70 µs
Wall time: 80.1 µs


0.8809849521203831

In [66]:
%%time
TPR_rf_40to50  = confusion_matrix_40to50[0,0] / (confusion_matrix_40to50[0,0] + confusion_matrix_40to50[1,0])

TPR_rf_40to50 

CPU times: user 94 µs, sys: 27 µs, total: 121 µs
Wall time: 230 µs


0.8738351254480287

In [67]:
%%time
TPR_rf_g50  = confusion_matrix_g50[0,0] / (confusion_matrix_g50[0,0] + confusion_matrix_g50[1,0])

TPR_rf_g50 

CPU times: user 67 µs, sys: 2 µs, total: 69 µs
Wall time: 77.7 µs


0.8650717703349282

In [68]:
%%time
# Equalized Odds
#TPR = TP/TP+FN
#FNR = FN/FN+TP


FNR_rf_l30 = confusion_matrix_l30[1,0] / (confusion_matrix_l30[1,0] + confusion_matrix_l30[0,0])

FNR_rf_l30 # 0.11652109273369263


CPU times: user 71 µs, sys: 2 µs, total: 73 µs
Wall time: 81.1 µs


0.11369990680335508

In [69]:
%%time
FNR_rf_30to40 = confusion_matrix_30to40[1,0] / (confusion_matrix_30to40[1,0] + confusion_matrix_30to40[0,0])

FNR_rf_30to40

CPU times: user 80 µs, sys: 2 µs, total: 82 µs
Wall time: 99.2 µs


0.11901504787961696

In [70]:
%%time
FNR_rf_40to50 = confusion_matrix_40to50[1,0] / (confusion_matrix_40to50[1,0] + confusion_matrix_40to50[0,0])

FNR_rf_40to50

CPU times: user 51 µs, sys: 1 µs, total: 52 µs
Wall time: 58.9 µs


0.12616487455197134

In [71]:
%%time
FNR_rf_g50 = confusion_matrix_g50[1,0] / (confusion_matrix_g50[1,0] + confusion_matrix_g50[0,0])

FNR_rf_g50

CPU times: user 72 µs, sys: 2 µs, total: 74 µs
Wall time: 83 µs


0.13492822966507176

In [72]:
%%time
# Fairness Through Unwareness

x_train_unawareness = x_train.copy()
x_train_unawareness
x_train_unawareness.drop('catAge_<=30', inplace=True, axis=1)
x_train_unawareness.drop('catAge_30-40', inplace=True, axis=1)
x_train_unawareness.drop('catAge_40-50', inplace=True, axis=1)
x_train_unawareness.drop('catAge_>=50', inplace=True, axis=1)

# x_train_unawareness.columns.values
# x_train.columns.values

CPU times: user 27.6 ms, sys: 8.76 ms, total: 36.4 ms
Wall time: 39.2 ms


In [73]:
%%time
#Fairness through unawareness

x_test_unawareness = x_test.copy()
x_test_unawareness
x_test_l30 = x_test_unawareness[x_test_unawareness['catAge_<=30'] == 1]
x_test_30to40 = x_test_unawareness[x_test_unawareness['catAge_30-40'] == 1]
x_test_40to50 = x_test_unawareness[x_test_unawareness['catAge_40-50'] == 1]
x_test_g50 = x_test_unawareness[x_test_unawareness['catAge_>=50'] == 1]


x_test_l30.drop('catAge_<=30', inplace=True, axis=1)
x_test_l30.drop('catAge_30-40', inplace=True, axis=1)
x_test_l30.drop('catAge_40-50', inplace=True, axis=1)
x_test_l30.drop('catAge_>=50', inplace=True, axis=1)

x_test_30to40.drop('catAge_<=30', inplace=True, axis=1)
x_test_30to40.drop('catAge_30-40', inplace=True, axis=1)
x_test_30to40.drop('catAge_40-50', inplace=True, axis=1)
x_test_30to40.drop('catAge_>=50', inplace=True, axis=1)

x_test_40to50.drop('catAge_<=30', inplace=True, axis=1)
x_test_40to50.drop('catAge_30-40', inplace=True, axis=1)
x_test_40to50.drop('catAge_40-50', inplace=True, axis=1)
x_test_40to50.drop('catAge_>=50', inplace=True, axis=1)

x_test_g50.drop('catAge_<=30', inplace=True, axis=1)
x_test_g50.drop('catAge_30-40', inplace=True, axis=1)
x_test_g50.drop('catAge_40-50', inplace=True, axis=1)
x_test_g50.drop('catAge_>=50', inplace=True, axis=1)



# x_test_unawareness.columns.values
# x_test.columns.values

CPU times: user 51 ms, sys: 2.75 ms, total: 53.8 ms
Wall time: 59 ms


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/core/frame.py:4163: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


In [74]:
%%time
# Test on l30 set

rf_pred_l30 = rf.fit(x_train_unawareness, y_train).predict(x_test_l30)

test_df = x_test_l30.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(rf_pred_l30, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_l30 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_l30


CPU times: user 4.73 s, sys: 64.7 ms, total: 4.79 s
Wall time: 6.82 s


array([[882, 369],
       [108,  57]])

In [75]:
%%time
accuracy_rf_l30 = (confusion_matrix_l30[0][0] + confusion_matrix_l30[1][1]) / (confusion_matrix_l30[0][0] + confusion_matrix_l30[0][1] + confusion_matrix_l30[1][0] + confusion_matrix_l30[1][1])
accuracy_rf_l30

CPU times: user 89 µs, sys: 1 µs, total: 90 µs
Wall time: 102 µs


0.663135593220339

In [76]:
%%time
# Test on 30to40 set

rf_pred_30to40 = rf.fit(x_train_unawareness, y_train).predict(x_test_30to40)

test_df = x_test_30to40.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(rf_pred_30to40, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_30to40 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_30to40


CPU times: user 4.63 s, sys: 77.7 ms, total: 4.71 s
Wall time: 6.43 s


array([[1983, 1051],
       [ 274,  136]])

In [77]:
%%time
accuracy_rf_30to40 = (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[1][1]) / (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[0][1] + confusion_matrix_30to40[1][0] + confusion_matrix_30to40[1][1])
accuracy_rf_30to40 

CPU times: user 76 µs, sys: 1e+03 ns, total: 77 µs
Wall time: 86.1 µs


0.6152729384436701

In [78]:
%%time
# Test on 40to50 set

rf_pred_40to50 = rf.fit(x_train_unawareness, y_train).predict(x_test_40to50)

test_df = x_test_40to50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(rf_pred_40to50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_40to50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_40to50

CPU times: user 4.85 s, sys: 76 ms, total: 4.93 s
Wall time: 6.61 s


array([[1140,  856],
       [ 160,  118]])

In [79]:
%%time
accuracy_rf_40to50 = (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[1][1]) / (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[0][1] + confusion_matrix_40to50[1][0] + confusion_matrix_40to50[1][1])
accuracy_rf_40to50 # 0.8718606782768102

CPU times: user 98 µs, sys: 2 µs, total: 100 µs
Wall time: 112 µs


0.5532102022867195

In [80]:
%%time
# Test on g50 set

rf_pred_g50 = rf.fit(x_train_unawareness, y_train).predict(x_test_g50)

test_df = x_test_g50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(rf_pred_g50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_g50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_g50

CPU times: user 4.91 s, sys: 83.9 ms, total: 5 s
Wall time: 6.79 s


array([[943, 703],
       [129, 100]])

In [81]:
%%time
accuracy_rf_g50 = (confusion_matrix_g50[0][0] + confusion_matrix_g50[1][1]) / (confusion_matrix_g50[0][0] + confusion_matrix_g50[0][1] + confusion_matrix_g50[1][0] + confusion_matrix_g50[1][1])
accuracy_rf_g50 # 0.8718606782768102

CPU times: user 100 µs, sys: 2 µs, total: 102 µs
Wall time: 113 µs


0.5562666666666667

Support Vector Machine

In [82]:
%%time
from sklearn import svm as svm_model
svm = svm_model.SVC(class_weight='balanced') # add class_weight='balanced' is to avoid classifying all data as 0
svm_pred = svm.fit(x_train, y_train).predict(x_test)

CPU times: user 7min 5s, sys: 6.18 s, total: 7min 11s
Wall time: 11min 8s


In [83]:
%%time
test_df = x_test.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(svm_pred, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])
test_df.columns.values

CPU times: user 9.67 ms, sys: 13.7 ms, total: 23.4 ms
Wall time: 19.9 ms


array(['balance', 'day', 'duration', 'campaign', 'pdays', 'previous',
       'biDefault', 'biHousing', 'biLoan', 'catAge_30-40', 'catAge_40-50',
       'catAge_<=30', 'catAge_>=50', 'job_admin.', 'job_blue-collar',
       'job_entrepreneur', 'job_housemaid', 'job_management',
       'job_retired', 'job_self-employed', 'job_services', 'job_student',
       'job_technician', 'job_unemployed', 'marital_divorced',
       'marital_married', 'marital_single', 'education_primary',
       'education_secondary', 'education_tertiary', 'month_apr',
       'month_aug', 'month_dec', 'month_feb', 'month_jan', 'month_jul',
       'month_jun', 'month_mar', 'month_may', 'month_nov', 'month_oct',
       'month_sep', 'Fmonth_apr', 'Fmonth_aug', 'Fmonth_dec',
       'Fmonth_feb', 'Fmonth_jan', 'Fmonth_jul', 'Fmonth_jun',
       'Fmonth_mar', 'Fmonth_may', 'Fmonth_nov', 'Fmonth_oct', 'biY',
       'pred', 'accurate'], dtype=object)

In [84]:
%%time
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix

CPU times: user 34.6 ms, sys: 6.45 ms, total: 41.1 ms
Wall time: 47.8 ms


array([[5273, 2654],
       [ 717,  365]])

In [85]:
%%time
# Accuracy
# "Accuracy: ", test_df.accurate.mean()

accuracy_svm = (confusion_matrix[0][0] + confusion_matrix[1][1]) / (confusion_matrix[0][0] + confusion_matrix[0][1] + confusion_matrix[1][0] + confusion_matrix[1][1])
accuracy_svm


CPU times: user 89 µs, sys: 1 µs, total: 90 µs
Wall time: 105 µs


0.6258186258186258

In [86]:
%%time
# Split dataset based on marital status

test_df.columns.values
test_l30 = x_test[x_test['catAge_<=30'] == 1]
test_30to40 = x_test[x_test['catAge_30-40'] == 1]
test_40to50 = x_test[x_test['catAge_40-50'] == 1]
test_g50 = x_test[x_test['catAge_>=50'] == 1]

CPU times: user 10.2 ms, sys: 4.27 ms, total: 14.4 ms
Wall time: 14.6 ms


In [87]:
%%time
# Test on l30 subset

svm_pred_l30 = svm.fit(x_train, y_train).predict(test_l30)

test_df = test_l30.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(svm_pred_l30, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_l30 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_l30

CPU times: user 6min 18s, sys: 5.04 s, total: 6min 23s
Wall time: 8min 43s


array([[855, 396],
       [118,  47]])

In [88]:
%%time
accuracy_svm_l30 = (confusion_matrix_l30[0][0] + confusion_matrix_l30[1][1]) / (confusion_matrix_l30[0][0] + confusion_matrix_l30[0][1] + confusion_matrix_l30[1][0] + confusion_matrix_l30[1][1])
accuracy_svm_l30

CPU times: user 95 µs, sys: 2 µs, total: 97 µs
Wall time: 107 µs


0.6370056497175142

In [89]:
%%time
# Test on married subset

svm_pred_30to40 = svm.fit(x_train, y_train).predict(test_30to40)

test_df = test_30to40.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(svm_pred_30to40, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_30to40 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_30to40

CPU times: user 6min, sys: 3.41 s, total: 6min 4s
Wall time: 7min 21s


array([[2029, 1005],
       [ 275,  135]])

In [90]:
%%time
accuracy_svm_30to40 = (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[1][1]) / (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[0][1] + confusion_matrix_30to40[1][0] + confusion_matrix_30to40[1][1])
accuracy_svm_30to40 # 0.8718606782768102

CPU times: user 63 µs, sys: 18 µs, total: 81 µs
Wall time: 89.9 µs


0.6283391405342624

In [91]:
%%time
# Test on 40to50 subset

svm_pred_40to50 = svm.fit(x_train, y_train).predict(test_40to50)

test_df = test_40to50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(svm_pred_40to50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_40to50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_40to50

CPU times: user 4min 57s, sys: 2.54 s, total: 5min
Wall time: 5min 20s


array([[1342,  654],
       [ 190,   88]])

In [92]:
%%time
accuracy_svm_40to50 = (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[1][1]) / (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[0][1] + confusion_matrix_40to50[1][0] + confusion_matrix_40to50[1][1])
accuracy_svm_40to50 

CPU times: user 103 µs, sys: 3 µs, total: 106 µs
Wall time: 118 µs


0.6288478452066842

In [93]:
%%time
# Test on g50 subset

svm_pred_g50 = svm.fit(x_train, y_train).predict(test_g50)

test_df = test_g50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(svm_pred_g50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_g50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_g50

CPU times: user 4min 46s, sys: 2.19 s, total: 4min 48s
Wall time: 4min 59s


array([[1047,  599],
       [ 134,   95]])

In [94]:
%%time
accuracy_svm_g50 = (confusion_matrix_g50[0][0] + confusion_matrix_g50[1][1]) / (confusion_matrix_g50[0][0] + confusion_matrix_g50[0][1] + confusion_matrix_g50[1][0] + confusion_matrix_g50[1][1])
accuracy_svm_g50 # 0.8718606782768102

CPU times: user 81 µs, sys: 1 µs, total: 82 µs
Wall time: 93.9 µs


0.6090666666666666

In [95]:
%%time
#Demographic Parity
# positive rate = TP + TN

PR_svm_l30 = confusion_matrix_l30[0,0] +confusion_matrix_l30[1,1]

PR_svm_l30

CPU times: user 68 µs, sys: 1 µs, total: 69 µs
Wall time: 79.9 µs


902

In [96]:
%%time
PR_svm_30to40 = confusion_matrix_30to40[0,0] +confusion_matrix_30to40[1,1]
PR_svm_30to40

CPU times: user 225 µs, sys: 10 µs, total: 235 µs
Wall time: 277 µs


2164

In [97]:
%%time
PR_svm_40to50 = confusion_matrix_40to50[0,0] +confusion_matrix_40to50[1,1]
PR_svm_40to50

CPU times: user 83 µs, sys: 3 µs, total: 86 µs
Wall time: 95.1 µs


1430

In [98]:
%%time
PR_svm_g50 = confusion_matrix_g50[0,0] +confusion_matrix_g50[1,1]
PR_svm_g50

CPU times: user 41 µs, sys: 1e+03 ns, total: 42 µs
Wall time: 47 µs


1142

In [99]:
%%time
# Equalized Opportunity
#TPR = TP/TP+FN

TPR_svm_l30 = confusion_matrix_l30[0,0] / (confusion_matrix_l30[0,0] + confusion_matrix_l30[1,0])

TPR_svm_l30

CPU times: user 74 µs, sys: 2 µs, total: 76 µs
Wall time: 87 µs


0.8787255909558068

In [100]:
%%time
TPR_svm_30to40 = confusion_matrix_30to40[0,0] / (confusion_matrix_30to40[0,0] + confusion_matrix_30to40[1,0])

TPR_svm_30to40 

CPU times: user 48 µs, sys: 1e+03 ns, total: 49 µs
Wall time: 56 µs


0.8806423611111112

In [101]:
%%time
TPR_svm_40to50 = confusion_matrix_40to50[0,0] / (confusion_matrix_40to50[0,0] + confusion_matrix_40to50[1,0])

TPR_svm_40to50 

CPU times: user 64 µs, sys: 1 µs, total: 65 µs
Wall time: 75.1 µs


0.8759791122715405

In [102]:
%%time
TPR_svm_g50 = confusion_matrix_g50[0,0] / (confusion_matrix_g50[0,0] + confusion_matrix_g50[1,0])

TPR_svm_g50 

CPU times: user 45 µs, sys: 1 µs, total: 46 µs
Wall time: 51.7 µs


0.88653683319221

In [103]:
%%time
# Equalized Odds
#TPR = TP/TP+FN
#FNR = FN/FN+TP


FNR_svm_l30 = confusion_matrix_l30[1,0] / (confusion_matrix_l30[1,0] + confusion_matrix_l30[0,0])

FNR_svm_l30

CPU times: user 49 µs, sys: 1e+03 ns, total: 50 µs
Wall time: 56 µs


0.12127440904419322

In [104]:
%%time
FNR_svm_30to40 = confusion_matrix_30to40[1,0] / (confusion_matrix_30to40[1,0] + confusion_matrix_30to40[0,0])

FNR_svm_30to40 

CPU times: user 59 µs, sys: 1 µs, total: 60 µs
Wall time: 67.2 µs


0.1193576388888889

In [105]:
%%time
FNR_svm_40to50 = confusion_matrix_40to50[1,0] / (confusion_matrix_40to50[1,0] + confusion_matrix_40to50[0,0])

FNR_svm_40to50 

CPU times: user 96 µs, sys: 33 µs, total: 129 µs
Wall time: 233 µs


0.12402088772845953

In [106]:
%%time
FNR_svm_g50 = confusion_matrix_g50[1,0] / (confusion_matrix_g50[1,0] + confusion_matrix_g50[0,0])

FNR_svm_g50 

CPU times: user 55 µs, sys: 1 µs, total: 56 µs
Wall time: 62.9 µs


0.11346316680779

In [107]:
%%time
# Fairness Through Unwareness

x_train_unawareness = x_train.copy()
x_train_unawareness
x_train_unawareness.drop('catAge_<=30', inplace=True, axis=1)
x_train_unawareness.drop('catAge_30-40', inplace=True, axis=1)
x_train_unawareness.drop('catAge_40-50', inplace=True, axis=1)
x_train_unawareness.drop('catAge_>=50', inplace=True, axis=1)


# x_train_unawareness.columns.values
# x_train.columns.values

CPU times: user 26.5 ms, sys: 19.3 ms, total: 45.9 ms
Wall time: 45.6 ms


In [108]:
%%time
#Fairness through unawareness


x_test_unawareness = x_test.copy()
x_test_unawareness
x_test_l30 = x_test_unawareness[x_test_unawareness['catAge_<=30'] == 1]
x_test_30to40 = x_test_unawareness[x_test_unawareness['catAge_30-40'] == 1]
x_test_40to50 = x_test_unawareness[x_test_unawareness['catAge_40-50'] == 1]
x_test_g50 = x_test_unawareness[x_test_unawareness['catAge_>=50'] == 1]


x_test_l30.drop('catAge_<=30', inplace=True, axis=1)
x_test_l30.drop('catAge_30-40', inplace=True, axis=1)
x_test_l30.drop('catAge_40-50', inplace=True, axis=1)
x_test_l30.drop('catAge_>=50', inplace=True, axis=1)

x_test_30to40.drop('catAge_<=30', inplace=True, axis=1)
x_test_30to40.drop('catAge_30-40', inplace=True, axis=1)
x_test_30to40.drop('catAge_40-50', inplace=True, axis=1)
x_test_30to40.drop('catAge_>=50', inplace=True, axis=1)

x_test_40to50.drop('catAge_<=30', inplace=True, axis=1)
x_test_40to50.drop('catAge_30-40', inplace=True, axis=1)
x_test_40to50.drop('catAge_40-50', inplace=True, axis=1)
x_test_40to50.drop('catAge_>=50', inplace=True, axis=1)

x_test_g50.drop('catAge_<=30', inplace=True, axis=1)
x_test_g50.drop('catAge_30-40', inplace=True, axis=1)
x_test_g50.drop('catAge_40-50', inplace=True, axis=1)
x_test_g50.drop('catAge_>=50', inplace=True, axis=1)



CPU times: user 45.8 ms, sys: 16.4 ms, total: 62.3 ms
Wall time: 62.5 ms


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/core/frame.py:4163: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


In [109]:
%%time
# Test on l30 set

svm_pred_l30 = svm.fit(x_train_unawareness, y_train).predict(x_test_l30)

test_df = x_test_l30.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(svm_pred_l30, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_l30 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_l30


CPU times: user 4min 3s, sys: 1.3 s, total: 4min 4s
Wall time: 4min 10s


array([[855, 396],
       [118,  47]])

In [110]:
%%time
accuracy_svm_l30 = (confusion_matrix_l30[0][0] + confusion_matrix_l30[1][1]) / (confusion_matrix_l30[0][0] + confusion_matrix_l30[0][1] + confusion_matrix_l30[1][0] + confusion_matrix_l30[1][1])
accuracy_svm_l30

CPU times: user 104 µs, sys: 207 µs, total: 311 µs
Wall time: 113 µs


0.6370056497175142

In [111]:
%%time
# Test on 30to40 set

svm_pred_30to40 = svm.fit(x_train_unawareness, y_train).predict(x_test_30to40)

test_df = x_test_30to40.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(svm_pred_30to40, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_30to40 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_30to40

CPU times: user 4min 36s, sys: 3.4 s, total: 4min 39s
Wall time: 5min 7s


array([[2030, 1004],
       [ 275,  135]])

In [112]:
%%time
accuracy_svm_30to40 = (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[1][1]) / (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[0][1] + confusion_matrix_30to40[1][0] + confusion_matrix_30to40[1][1])
accuracy_svm_30to40 # 0.8718606782768102

CPU times: user 88 µs, sys: 2 µs, total: 90 µs
Wall time: 101 µs


0.6286295005807201

In [113]:
%%time
# Test on 40to50 subset

svm_pred_40to50 = svm.fit(x_train_unawareness, y_train).predict(x_test_40to50)

test_df = x_test_40to50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(svm_pred_40to50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_40to50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_40to50

CPU times: user 3min 36s, sys: 966 ms, total: 3min 37s
Wall time: 3min 39s


array([[1342,  654],
       [ 190,   88]])

In [114]:
%%time
accuracy_svm_40to50 = (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[1][1]) / (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[0][1] + confusion_matrix_40to50[1][0] + confusion_matrix_40to50[1][1])
accuracy_svm_40to50 

CPU times: user 52 µs, sys: 0 ns, total: 52 µs
Wall time: 59.8 µs


0.6288478452066842

In [115]:
%%time
# Test on g50 subset

svm_pred_g50 = svm.fit(x_train_unawareness, y_train).predict(x_test_g50)

test_df = x_test_g50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(svm_pred_g50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_g50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_g50

CPU times: user 3min 15s, sys: 1.46 s, total: 3min 17s
Wall time: 3min 19s


array([[1047,  599],
       [ 134,   95]])

In [116]:
%%time
accuracy_svm_g50 = (confusion_matrix_g50[0][0] + confusion_matrix_g50[1][1]) / (confusion_matrix_g50[0][0] + confusion_matrix_g50[0][1] + confusion_matrix_g50[1][0] + confusion_matrix_g50[1][1])
accuracy_svm_g50 

CPU times: user 65 µs, sys: 2 µs, total: 67 µs
Wall time: 73.9 µs


0.6090666666666666

Logistic Regression Model

In [117]:
%%time
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(random_state=0, class_weight='balanced')
clf_pred = clf.fit(x_train, y_train).predict(x_test)

CPU times: user 1.63 s, sys: 132 ms, total: 1.76 s
Wall time: 1.19 s


In [118]:
%%time
test_df = x_test.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(clf_pred, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])
test_df.columns.values

CPU times: user 4.06 ms, sys: 1.18 ms, total: 5.24 ms
Wall time: 4.82 ms


array(['balance', 'day', 'duration', 'campaign', 'pdays', 'previous',
       'biDefault', 'biHousing', 'biLoan', 'catAge_30-40', 'catAge_40-50',
       'catAge_<=30', 'catAge_>=50', 'job_admin.', 'job_blue-collar',
       'job_entrepreneur', 'job_housemaid', 'job_management',
       'job_retired', 'job_self-employed', 'job_services', 'job_student',
       'job_technician', 'job_unemployed', 'marital_divorced',
       'marital_married', 'marital_single', 'education_primary',
       'education_secondary', 'education_tertiary', 'month_apr',
       'month_aug', 'month_dec', 'month_feb', 'month_jan', 'month_jul',
       'month_jun', 'month_mar', 'month_may', 'month_nov', 'month_oct',
       'month_sep', 'Fmonth_apr', 'Fmonth_aug', 'Fmonth_dec',
       'Fmonth_feb', 'Fmonth_jan', 'Fmonth_jul', 'Fmonth_jun',
       'Fmonth_mar', 'Fmonth_may', 'Fmonth_nov', 'Fmonth_oct', 'biY',
       'pred', 'accurate'], dtype=object)

In [119]:
%%time
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix

CPU times: user 21.5 ms, sys: 6.07 ms, total: 27.5 ms
Wall time: 39 ms


array([[3904, 4023],
       [ 539,  543]])

In [120]:
%%time
# Accuracy
# "Accuracy: ", test_df.accurate.mean()

accuracy_clf = (confusion_matrix[0][0] + confusion_matrix[1][1]) / (confusion_matrix[0][0] + confusion_matrix[0][1] + confusion_matrix[1][0] + confusion_matrix[1][1])
accuracy_clf

CPU times: user 45 µs, sys: 1 µs, total: 46 µs
Wall time: 50.3 µs


0.49361749361749363

In [121]:
%%time
# Split dataset based on marital status

test_df.columns.values
test_l30 = x_test[x_test['catAge_<=30'] == 1]
test_30to40 = x_test[x_test['catAge_30-40'] == 1]
test_40to50 = x_test[x_test['catAge_40-50'] == 1]
test_g50 = x_test[x_test['catAge_>=50'] == 1]

CPU times: user 9.62 ms, sys: 2.74 ms, total: 12.4 ms
Wall time: 11.4 ms


In [122]:
%%time
# Test on l30 subset

clf_pred_l30 = clf.fit(x_train, y_train).predict(test_l30)

test_df = test_l30.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(clf_pred_l30, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_l30 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_l30

CPU times: user 1.4 s, sys: 61.8 ms, total: 1.46 s
Wall time: 773 ms


array([[865, 386],
       [104,  61]])

In [123]:
%%time
accuracy_clf_l30 = (confusion_matrix_l30[0][0] + confusion_matrix_l30[1][1]) / (confusion_matrix_l30[0][0] + confusion_matrix_l30[0][1] + confusion_matrix_l30[1][0] + confusion_matrix_l30[1][1])
accuracy_clf_l30

CPU times: user 84 µs, sys: 7 µs, total: 91 µs
Wall time: 50.8 µs


0.653954802259887

In [124]:
%%time
# Test on 30to40 subset

clf_pred_30to40 = clf.fit(x_train, y_train).predict(test_30to40)

test_df = test_30to40.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(clf_pred_30to40, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_30to40 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_30to40

CPU times: user 1.45 s, sys: 66.5 ms, total: 1.52 s
Wall time: 783 ms


array([[1689, 1345],
       [ 236,  174]])

In [125]:
%%time
accuracy_clf_30to40 = (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[1][1]) / (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[0][1] + confusion_matrix_30to40[1][0] + confusion_matrix_30to40[1][1])
accuracy_clf_30to40

CPU times: user 82 µs, sys: 6 µs, total: 88 µs
Wall time: 48.2 µs


0.5409407665505227

In [126]:
%%time
# Test on 40to50 subset

clf_pred_40to50 = clf.fit(x_train, y_train).predict(test_40to50)
 
test_df = test_40to50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(clf_pred_40to50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])
 
from sklearn.metrics import confusion_matrix
 
confusion_matrix_40to50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_40to50

CPU times: user 1.45 s, sys: 68.2 ms, total: 1.51 s
Wall time: 772 ms


array([[ 828, 1168],
       [ 114,  164]])

In [127]:
%%time
accuracy_clf_40to50 = (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[1][1]) / (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[0][1] + confusion_matrix_40to50[1][0] + confusion_matrix_40to50[1][1])
accuracy_clf_40to50 

CPU times: user 77 µs, sys: 6 µs, total: 83 µs
Wall time: 46 µs


0.436235708003518

In [128]:
%%time
# Test on g50 subset

clf_pred_g50 = clf.fit(x_train, y_train).predict(test_g50)
 
test_df = test_g50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(clf_pred_g50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])
 
from sklearn.metrics import confusion_matrix
 
confusion_matrix_g50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_g50

CPU times: user 1.45 s, sys: 79.8 ms, total: 1.53 s
Wall time: 789 ms


array([[ 522, 1124],
       [  85,  144]])

In [129]:
%%time
accuracy_clf_g50 = (confusion_matrix_g50[0][0] + confusion_matrix_g50[1][1]) / (confusion_matrix_g50[0][0] + confusion_matrix_g50[0][1] + confusion_matrix_g50[1][0] + confusion_matrix_g50[1][1])
accuracy_clf_g50 

CPU times: user 83 µs, sys: 6 µs, total: 89 µs
Wall time: 49.8 µs


0.3552

In [130]:
%%time
#Demographic Parity
# positive rate = TP + TN

PR_clf_l30 = confusion_matrix_l30[0,0] +confusion_matrix_l30[1,1]
PR_clf_l30 # 4756

CPU times: user 78 µs, sys: 8 µs, total: 86 µs
Wall time: 48.9 µs


926

In [131]:
%%time
PR_clf_30to40 = confusion_matrix_30to40[0,0] +confusion_matrix_30to40[1,1]
PR_clf_30to40 # 2136

CPU times: user 63 µs, sys: 4 µs, total: 67 µs
Wall time: 38.1 µs


1863

In [132]:
%%time
PR_clf_40to50 = confusion_matrix_40to50[0,0] +confusion_matrix_40to50[1,1]
PR_clf_40to50 # 2136

CPU times: user 37 µs, sys: 0 ns, total: 37 µs
Wall time: 42.2 µs


992

In [133]:
%%time
PR_clf_g50 = confusion_matrix_g50[0,0] +confusion_matrix_g50[1,1]
PR_clf_g50 # 2136

CPU times: user 46 µs, sys: 1 µs, total: 47 µs
Wall time: 53.9 µs


666

In [134]:
%%time
# Equalized Opportunity
#TPR = TP/TP+FN

TPR_clf_l30 = confusion_matrix_l30[0,0] / (confusion_matrix_l30[0,0] + confusion_matrix_l30[1,0])

TPR_clf_l30

CPU times: user 40 µs, sys: 0 ns, total: 40 µs
Wall time: 47 µs


0.8926728586171311

In [135]:
%%time
TPR_clf_30to40 = confusion_matrix_30to40[0,0] / (confusion_matrix_30to40[0,0] + confusion_matrix_30to40[1,0])

TPR_clf_30to40  

CPU times: user 54 µs, sys: 2 µs, total: 56 µs
Wall time: 64.1 µs


0.8774025974025974

In [136]:
%%time
TPR_clf_40to50  = confusion_matrix_40to50[0,0] / (confusion_matrix_40to50[0,0] + confusion_matrix_40to50[1,0])

TPR_clf_40to50 

CPU times: user 35 µs, sys: 1 µs, total: 36 µs
Wall time: 41 µs


0.8789808917197452

In [137]:
%%time
TPR_clf_g50  = confusion_matrix_g50[0,0] / (confusion_matrix_g50[0,0] + confusion_matrix_g50[1,0])

TPR_clf_g50 

CPU times: user 51 µs, sys: 1 µs, total: 52 µs
Wall time: 59.4 µs


0.8599670510708401

In [138]:
%%time
# Equalized Odds
#TPR = TP/TP+FN
#FNR = FN/FN+TP


FNR_clf_l30 = confusion_matrix_l30[1,0] / (confusion_matrix_l30[1,0] + confusion_matrix_l30[0,0])

FNR_clf_l30 # 0.11652109273369263

CPU times: user 51 µs, sys: 1 µs, total: 52 µs
Wall time: 58.9 µs


0.10732714138286893

In [139]:
%%time
FNR_clf_30to40 = confusion_matrix_30to40[1,0] / (confusion_matrix_30to40[1,0] + confusion_matrix_30to40[0,0])

FNR_clf_30to40

CPU times: user 49 µs, sys: 1 µs, total: 50 µs
Wall time: 58.2 µs


0.1225974025974026

In [140]:
%%time
FNR_clf_40to50 = confusion_matrix_40to50[1,0] / (confusion_matrix_40to50[1,0] + confusion_matrix_40to50[0,0])

FNR_clf_40to50

CPU times: user 51 µs, sys: 1 µs, total: 52 µs
Wall time: 58.7 µs


0.12101910828025478

In [141]:
%%time
FNR_clf_g50 = confusion_matrix_g50[1,0] / (confusion_matrix_g50[1,0] + confusion_matrix_g50[0,0])

FNR_clf_g50

CPU times: user 38 µs, sys: 1e+03 ns, total: 39 µs
Wall time: 43.2 µs


0.1400329489291598

In [142]:
%%time
# Fairness Through Unwareness

x_train_unawareness = x_train.copy()
x_train_unawareness
x_train_unawareness.drop('catAge_<=30', inplace=True, axis=1)
x_train_unawareness.drop('catAge_30-40', inplace=True, axis=1)
x_train_unawareness.drop('catAge_40-50', inplace=True, axis=1)
x_train_unawareness.drop('catAge_>=50', inplace=True, axis=1)

# x_train_unawareness.columns.values
# x_train.columns.values

CPU times: user 21.8 ms, sys: 10.4 ms, total: 32.2 ms
Wall time: 32.6 ms


In [143]:
%%time
#Fairness through unawareness

x_test_unawareness = x_test.copy()
x_test_unawareness
x_test_l30 = x_test_unawareness[x_test_unawareness['catAge_<=30'] == 1]
x_test_30to40 = x_test_unawareness[x_test_unawareness['catAge_30-40'] == 1]
x_test_40to50 = x_test_unawareness[x_test_unawareness['catAge_40-50'] == 1]
x_test_g50 = x_test_unawareness[x_test_unawareness['catAge_>=50'] == 1]


x_test_l30.drop('catAge_<=30', inplace=True, axis=1)
x_test_l30.drop('catAge_30-40', inplace=True, axis=1)
x_test_l30.drop('catAge_40-50', inplace=True, axis=1)
x_test_l30.drop('catAge_>=50', inplace=True, axis=1)

x_test_30to40.drop('catAge_<=30', inplace=True, axis=1)
x_test_30to40.drop('catAge_30-40', inplace=True, axis=1)
x_test_30to40.drop('catAge_40-50', inplace=True, axis=1)
x_test_30to40.drop('catAge_>=50', inplace=True, axis=1)

x_test_40to50.drop('catAge_<=30', inplace=True, axis=1)
x_test_40to50.drop('catAge_30-40', inplace=True, axis=1)
x_test_40to50.drop('catAge_40-50', inplace=True, axis=1)
x_test_40to50.drop('catAge_>=50', inplace=True, axis=1)

x_test_g50.drop('catAge_<=30', inplace=True, axis=1)
x_test_g50.drop('catAge_30-40', inplace=True, axis=1)
x_test_g50.drop('catAge_40-50', inplace=True, axis=1)
x_test_g50.drop('catAge_>=50', inplace=True, axis=1)



# x_test_unawareness.columns.values
# x_test.columns.values

CPU times: user 30.8 ms, sys: 5.09 ms, total: 35.9 ms
Wall time: 33.5 ms


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/core/frame.py:4163: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


In [144]:
%%time
# Test on l30 set

clf_pred_l30 = clf.fit(x_train_unawareness, y_train).predict(x_test_l30)

test_df = x_test_l30.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(clf_pred_l30, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_l30 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_l30

CPU times: user 1.17 s, sys: 60.1 ms, total: 1.23 s
Wall time: 833 ms


array([[788, 463],
       [ 86,  79]])

In [145]:
%%time
accuracy_clf_l30 = (confusion_matrix_l30[0][0] + confusion_matrix_l30[1][1]) / (confusion_matrix_l30[0][0] + confusion_matrix_l30[0][1] + confusion_matrix_l30[1][0] + confusion_matrix_l30[1][1])
accuracy_clf_l30

CPU times: user 75 µs, sys: 6 µs, total: 81 µs
Wall time: 44.1 µs


0.6122881355932204

In [146]:
%%time
# Test on 30to40 set

clf_pred_30to40 = clf.fit(x_train_unawareness, y_train).predict(x_test_30to40)

test_df = x_test_30to40.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(clf_pred_30to40, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_30to40 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_30to40


CPU times: user 1.23 s, sys: 71.4 ms, total: 1.3 s
Wall time: 689 ms


array([[1606, 1428],
       [ 229,  181]])

In [147]:
%%time
accuracy_clf_30to40 = (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[1][1]) / (confusion_matrix_30to40[0][0] + confusion_matrix_30to40[0][1] + confusion_matrix_30to40[1][0] + confusion_matrix_30to40[1][1])
accuracy_clf_30to40 

CPU times: user 83 µs, sys: 7 µs, total: 90 µs
Wall time: 50.1 µs


0.5188734030197445

In [148]:
%%time
# Test on 40to50 set

clf_pred_40to50 = clf.fit(x_train_unawareness, y_train).predict(x_test_40to50)

test_df = x_test_40to50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(clf_pred_40to50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_40to50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_40to50

CPU times: user 1.22 s, sys: 65.7 ms, total: 1.28 s
Wall time: 657 ms


array([[ 874, 1122],
       [ 121,  157]])

In [149]:
%%time
accuracy_clf_40to50 = (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[1][1]) / (confusion_matrix_40to50[0][0] + confusion_matrix_40to50[0][1] + confusion_matrix_40to50[1][0] + confusion_matrix_40to50[1][1])
accuracy_clf_40to50 # 0.8718606782768102

CPU times: user 78 µs, sys: 6 µs, total: 84 µs
Wall time: 46.7 µs


0.45338610378188215

In [150]:
%%time
# Test on g50 set

clf_pred_g50 = clf.fit(x_train_unawareness, y_train).predict(x_test_g50)

test_df = x_test_g50.copy()
test_df['biY'] = y_test
test_df['pred'] = pd.Series(clf_pred_g50, index=test_df.index)
test_df['accurate'] = (test_df['pred'] == test_df['biY'])

from sklearn.metrics import confusion_matrix

confusion_matrix_g50 = confusion_matrix(test_df['biY'], test_df['pred'])
confusion_matrix_g50

CPU times: user 1.27 s, sys: 70.6 ms, total: 1.34 s
Wall time: 698 ms


array([[ 641, 1005],
       [ 103,  126]])

In [151]:
%%time
accuracy_clf_g50 = (confusion_matrix_g50[0][0] + confusion_matrix_g50[1][1]) / (confusion_matrix_g50[0][0] + confusion_matrix_g50[0][1] + confusion_matrix_g50[1][0] + confusion_matrix_g50[1][1])
accuracy_clf_g50 # 0.8718606782768102

CPU times: user 92 µs, sys: 7 µs, total: 99 µs
Wall time: 56 µs


0.4090666666666667